### PR TITLE
upgrade to datasets-sars-cov-2; add SNF-A dataset to test layer

### PR DESCRIPTION
**Pull request by kapsakcj**
This PR adds a dockerfile for `datasets-sars-cov-2` v0.7.2. Partly done in response to #384 for adding a test for downloading a dataset that included assemblies/fasta files (e.g. SNF-A dataset), also done since the recent releases include updates to the checksums for the fastqs and fastas downloaded as part of the test.

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
Tests pass locally when building and testing locally by running `docker build -t kapsakcj/datasets-sars-cov-2:0.7.2 datasets-sars-cov-2/0.7.2/`, but fail on GH actions due to the SNF-A dataset being too large. The fastq files fill up the hard drive on the GH Actions runner pretty quick

**Comment by erinyoung** [comment]
That's kind of unfortunate

**Comment by kapsakcj** [comment]
The main purpose of this PR was to test the downloading of assemblies/FASTA files as requested in #384 and I think we have achieved that

**Review by erinyoung — APPROVED** [review]
If this works for you locally, then we can try it. 

I ran into the same issue when setting up my nextflow workflows. The github actions servers just don't have the space to use real data to test some of these bioinformatic things.

**Pull request merged**
