### PR TITLE
kma version update and README created

### PR DESCRIPTION
**Pull request by eetueklund**
Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
@kapsakcj , the test on the dockerfile is a little too sparse, but I'm not familiar enough with `kma` to make any suggestions.

**Comment by kapsakcj** [comment]
Great work on this so far, @eetueklund !

I think a good test would be to index a fasta file with `kma index` and then map some reads against the indexed database using `kma`

SerotypeFinder uses `kma` under the hood so perhaps we could test by indexing one or both of the `.fsa` files from here https://bitbucket.org/genomicepidemiology/serotypefinder_db/src/master/

Followed by mapping some E. coli reads against the database.

Here's the serotypefinder dockerfile where you can borrow the code to download reads for an O1:H7 E. coli. 

We don't really care that the correct serotype is identified, just that the `kma` commands run succesfully, so just checking for the outputs would be sufficient.

**Comment by erinyoung** [comment]
So... the test worked, but github actions thinks it failed. Let me look into this.

```
#12 15.13 2023-02-16 14:41:36 (17.8 MB/s) - 'SRR6903006_2.fastq.gz' saved [112804456]
#12 15.13 
#12 15.13 # Running KMA.
#12 15.15 # Reading inputfile:	SRR6903006_1.fastq.gz SRR6903006_2.fastq.gz
#12 15.15 # Phred scale:	33
#12 15.16 #
#12 15.16 # Total time used for DB loading: 0.05 s.
#12 15.16 #
#12 15.16 # Finding k-mer ankers
#12 43.95 #
#12 43.95 # Total number of query fragment after trimming:	594203
#12 43.95 #
#12 43.95 # Query converted
#12 43.95 #
#12 43.97 # Query ankered
#12 43.97 #
#12 43.97 # KMA mapping done
#12 43.97 #
#12 43.97 # Sort, output and select KMA alignments.
#12 45.60 # Total time for sorting and outputting KMA alignment	1.54 s.
#12 45.60 #
#12 45.60 # Doing local assemblies of found templates, and output results
#12 66.41 # Total time used for local assembly: 20.81 s.
#12 66.41 #
#12 66.41 # Closing files
#12 ERROR: process "/bin/sh -c wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR690/006/SRR6903006/SRR6903006_1.fastq.gz &&   wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR690/006/SRR6903006/SRR6903006_2.fastq.gz &&   kma -ipe SRR6903006_1.fastq.gz SRR6903006_2.fastq.gz -o test_output -t_db database" did not complete successfully: exit code: 95
```

**Comment by erinyoung** [comment]
The other test worked just fine, and if this one is like the other one, the failed one is missing 'Closing files'
```
#11 2.497 2023-02-16 14:41:14 (1.23 MB/s) - 'GCA_012224845.2_ASM1222484v2_genomic.fna.gz' saved [1556229/1556229]
#11 2.497 
#11 2.547 # Indexing databases.
#11 2.548 # Updating DBs
#11 2.549 # Reading inputfile: 	GCA_012224845.2_ASM1222484v2_genomic.fna
#11 6.072 # Added:	CP113091.1 Escherichia coli strain PNUSAE012694 chromosome, complete genome
#11 6.072 # Templates key-value pairs:	5114125.
#11 6.074 #
#11 6.074 # Total time used for DB indexing: 3.52 s.
#11 6.074 #
#11 6.074 # Compressing templates
#11 6.429 # Preparing compressed DB.
#11 6.459 # Calculating relative indexes.
#11 7.457 # Finalizing indexes.
#11 7.457 # Dumping compressed DB
#11 8.620 # Template database created.
#11 8.620 #
#11 8.620 # Total time used for DB compression: 2.55 s.
```

**Comment by eetueklund** [comment]
Thank you very much for all of your help. I really don't know what is giving the Error exit code 95 (Operation not supported). The Dockerfile builds and tests successfully on my machine. I tried looking at the kma code for any clues but did not see anything obvious. Seems like there is some operation that is not supported by github that happens after kma is done or as it is closing some files. I just don't see a reason why the test is successful for locally but not on github. 
Docker Screenshot 2023-02-16
Screenshot is the output text at the end of the local build.

**Comment by kapsakcj** [comment]
Sorry it took so long for me to circle back to this PR. I believe I've figured out the issue. 

I think the error code 95 is related to the temporary directory used by `kma`. Not exactly sure, but some operation, whether that be reading/writing files or something else, was not permitted. The error goes away when you specify `kma -tmp` and provide a directory. I'll push a commit in a moment which should fix the error

**Review by kapsakcj — APPROVED** [review]
Thanks for the PR and I hope you enjoyed the workshop! 

I appreciate you adding those tests at the end (despite the pain it may have caused 😬 ) as it will make the docker image more robust moving forward

I'll deploy to dockerhub and quay once the automated tests pass

**Comment by erinyoung** [comment]
@kapsakcj ... is the GOAT (I think I'm using that right)

**Comment by kapsakcj** [comment]
🐐

**Comment by kapsakcj** [comment]
Deploy workflow here if you'd like to follow along with progress: https://github.com/StaPH-B/docker-builds/actions/runs/4359168720

It should run very quickly and then the docker image will be publicly available under 4 tags on dockerhub and quay:
```
staphb/kma:latest
staphb/kma:1.4.10
quay.io/staphb/kma:latest
quay.io/staphb/kma:1.4.10
```

**Pull request merged**
