### PR TITLE
adds pangolin v4.2 & pangolin-data v1.19

### PR DESCRIPTION
**Pull request by kapsakcj**
🚨  ~~DRAFT PR for now, pangolin-data v.1.19 has not yet been released. Just prepping for when it is - folks are anxious to call new lingeages, e.g. XBB.1.16.1~~ 🚨 

📣 Ready for review - all necessary changes have been made and tests pass, including the new test for a new lineage XBB.1.16 (which was introduced in pangolin-data 1.19)

added dockerfile & README.md for pangolin 4.2 and pangolin-data 1.19 (~~not yet released, coming soon~~). also updated main README.md. ~~Docker image does not build yet, will re-build once there is a new pangolin-data release~~

Planning to use the docker image tag `staphb/pangolin:4.2-pdata-1.19` and overwrite `staphb/pangolin:latest` (as long as they use these version numbers)

Changes from previous dockerfile:

- upgraded base image to `mambaorg/micromamba:1.4.1` & LABEL for this
- reset `LABEL dockerfile.version` to `1` since this is a new dockerfile
- added a test for a recently collected XBB.1.16 that was used to define the new lineage

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
Reminder to self - update `pangolin/4.2-pdata-1.19/README.md` with appropriate version numbers & info on the included database files

**Comment by kapsakcj** [comment]
> Reminder to self - update `pangolin/4.2-pdata-1.19/README.md` with appropriate version numbers & info on the included database files

This step has been completed. PR is ready for review

**Comment by kapsakcj** [comment]
I don't need a review from everyone, just one person would suffice for checking my work! Hoping to deploy this image as quickly as we can

**Review by erinyoung — APPROVED** [review]
I don't see any major changes, and it looks like all tests passed.

I don't have any changes to recommend. 

I am going to
- merge this PR
- deploy to dockerhub and quay using the tag '4.2-pdata-1.19'
- overwrite the 'latest' tag

**Pull request merged**
