### PR TITLE
adds pasty 1.0.2 for P. aeruginosa serogrouping

### PR DESCRIPTION
**Pull request by kapsakcj**
~~Setting as a draft for now. Some of the test assemblies from the `pasty` GH repo are producing unexpected results so I'd like to resolve those issues before merging this PR.~~

Some of the test assemblies are expected to produce `NT` since they do not meet the default 95% ID and coverage thresholds. More info over here: https://github.com/rpetit3/pasty/issues/1

Docker image works great on my own P. aeruginosa assemblies though ✔️ 

This PR adds a dockerfile for `pasty`: https://github.com/rpetit3/pasty

This tool is new to our repo, so it includes a dockerfile, updated README.md and Program_Licenses.md, and a README.md specific to pasty

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
This... has a lot of dependencies. I can see why you went micromamba route:
```
#7 24.59 Transaction
#7 24.59 
#7 24.59   Prefix: /opt/conda
#7 24.59 
#7 24.59   Updating specs:
#7 24.59 
#7 24.59    - pasty=1.0.0
#7 24.59 
#7 24.59 
#7 24.59   Package                         Version  Build               Channel                   Size
#7 24.59 ───────────────────────────────────────────────────────────────────────────────────────────────
#7 24.59   Install:
#7 24.59 ───────────────────────────────────────────────────────────────────────────────────────────────
#7 24.59 
#7 24.59   + _libgcc_mutex                     0.1  conda_forge         conda-forge/linux-64       3kB
#7 24.59   + _openmp_mutex                     4.5  2_gnu               conda-forge/linux-64      24kB
#7 24.59   + blast                          2.13.0  hf3cf87c_0          bioconda/linux-64         24MB
#7 24.59   + bzip2                           1.0.8  h7f98852_4          conda-forge/linux-64     496kB
#7 24.59   + c-ares                         1.18.1  h7f98852_0          conda-forge/linux-64     115kB
#7 24.59   + ca-certificates             2022.9.24  ha878542_0          conda-forge/linux-64     154kB
#7 24.59   + click                           8.1.3  unix_pyhd8ed1ab_2   conda-forge/noarch        76kB
#7 24.59   + coloredlogs                    15.0.1  pyhd8ed1ab_3        conda-forge/noarch        41kB
#7 24.59   + commonmark                      0.9.1  py_0                conda-forge/noarch        47kB
#7 24.59   + curl                           7.86.0  h2283fc2_1          conda-forge/linux-64      93kB
#7 24.59   + dataclasses                       0.8  pyhc8e2a94_3        conda-forge/noarch        10kB
#7 24.59   + entrez-direct                    16.2  he881be0_1          bioconda/linux-64          8MB
#7 24.59   + executor                         23.2  pyhd3deb0d_0        conda-forge/noarch        64kB
#7 24.59   + fasteners                      0.17.3  pyhd8ed1ab_0        conda-forge/noarch        20kB
#7 24.59   + future                         0.18.2  pyhd8ed1ab_6        conda-forge/noarch       365kB
#7 24.59   + gettext                        0.21.1  h[270](https://github.com/StaPH-B/docker-builds/actions/runs/3587047240/jobs/6036954431#step:6:272)87fc_0          conda-forge/linux-64       4MB
#7 24.59   + humanfriendly                    10.0  py311h38be061_4     conda-forge/linux-64     156kB
#7 24.59   + keyutils                        1.6.1  h166bdaf_0          conda-forge/linux-64     118kB
#7 24.59   + krb5                           1.19.3  h08a2579_0          conda-forge/linux-64       2MB
#7 24.59   + ld_impl_linux-64                 2.39  hcc3a1bd_1          conda-forge/linux-64     691kB
#7 24.59   + libcurl                        7.86.0  h2283fc2_1          conda-forge/linux-64     360kB
#7 24.59   + libedit                  3.1.20191231  he28a2e2_2          conda-forge/linux-64     124kB
#7 24.59   + libev                            4.33  h516909a_1          conda-forge/linux-64     106kB
#7 24.59   + libffi                          3.4.2  h7f98852_5          conda-forge/linux-64      58kB
#7 24.59   + libgcc-ng                      12.2.0  h65d4601_19         conda-forge/linux-64     954kB
#7 24.59   + libgomp                        12.2.0  h65d4601_19         conda-forge/linux-64     466kB
#7 24.59   + libidn2                         2.3.4  h166bdaf_0          conda-forge/linux-64     160kB
#7 24.59   + libnghttp2                     1.47.0  hff17c54_1          conda-forge/linux-64     844kB
#7 24.59   + libnsl                          2.0.0  h7f98852_0          conda-forge/linux-64      31kB
#7 24.59   + libsqlite                      3.40.0  h753d[276](https://github.com/StaPH-B/docker-builds/actions/runs/3587047240/jobs/6036954431#step:6:278)_0          conda-forge/linux-64     810kB
#7 24.59   + libssh2                        1.10.0  hf14f497_3          conda-forge/linux-64     239kB
#7 24.59   + libstdcxx-ng                   12.2.0  h46fd767_19         conda-forge/linux-64       4MB
#7 24.59   + libunistring                   0.9.10  h7f98852_0          conda-forge/linux-64       1MB
#7 24.59   + libuuid                        2.32.1  h7f98852_1000       conda-forge/linux-64      28kB
#7 24.59   + libzlib                        1.2.13  h166bdaf_4          conda-forge/linux-64      66kB
#7 24.59   + ncurses                           6.3  h27087fc_1          conda-forge/linux-64       1MB
#7 24.59   + openssl                         3.0.7  h166bdaf_0          conda-forge/linux-64       3MB
#7 24.59   + pasty                           1.0.0  hdfd78af_0          bioconda/noarch           70kB
#7 24.59   + pcre                             8.45  h9c3ff4c_0          conda-forge/linux-64     259kB
#7 24.59   + perl                           5.32.1  2_h7f98852_perl5    conda-forge/linux-64      15MB
#7 24.59   + perl-archive-tar                 2.40  pl5321hdfd78af_0    bioconda/noarch           34kB
#7 24.59   + perl-carp                        1.50  pl5321hd8ed1ab_0    conda-forge/noarch        22kB
#7 24.59   + perl-common-sense                3.75  pl5321hd8ed1ab_0    conda-forge/noarch        20kB
#7 24.59   + perl-compress-raw-bzip2         2.201  pl5321h166bdaf_0    conda-forge/linux-64      55kB
#7 24.59   + perl-compress-raw-zlib          2.202  pl5321h166bdaf_0    conda-forge/linux-64      85kB
#7 24.59   + perl-encode                      3.19  pl5321h166bdaf_0    conda-forge/linux-64       2MB
#7 24.59   + perl-exporter                    5.74  pl5321hd8ed1ab_0    conda-forge/noarch        19kB
#7 24.59   + perl-exporter-tiny           1.002002  pl5321hd8ed1ab_0    conda-forge/noarch        29kB
#7 24.59   + perl-extutils-makemaker          7.64  pl5321hd8ed1ab_0    conda-forge/noarch       148kB
#7 24.59   + perl-io-compress                2.201  pl5321h87f3376_0    bioconda/linux-64         86kB
#7 24.59   + perl-io-zlib                     1.11  pl5321hdfd78af_0    bioconda/noarch           11kB
#7 24.59   + perl-json                        4.10  pl5321hdfd78af_0    bioconda/noarch           57kB
#7 24.59   + perl-json-xs                     2.34  pl5321h9f5acd7_5    bioconda/linux-64         65kB
#7 24.59   + perl-list-moreutils             0.430  pl5321hdfd78af_0    bioconda/noarch           32kB
#7 24.59   + perl-list-moreutils-xs          0.430  pl5321hec16e2b_1    bioconda/linux-64         50kB
#7 24.59   + perl-parent                     0.238  pl5321hd8ed1ab_0    conda-forge/noarch        12kB
#7 24.59   + perl-pathtools                   3.75  pl5321h166bdaf_0    conda-forge/linux-64      50kB
#7 24.59   + perl-scalar-list-utils           1.63  pl5321h166bdaf_0    conda-forge/linux-64      51kB
#7 24.59   + perl-storable                    3.15  pl5321h166bdaf_0    conda-forge/linux-64      72kB
#7 24.59   + perl-types-serialiser            1.01  pl5321hdfd78af_0    bioconda/noarch           13kB
#7 24.59   + pip                            22.3.1  pyhd8ed1ab_0        conda-forge/noarch         2MB
#7 24.59   + property-manager                  3.0  py_0                conda-forge/noarch        23kB
#7 24.59   + pygments                       2.13.0  pyhd8ed1ab_0        conda-forge/noarch       840kB
#7 24.59   + python                         3.11.0  ha86cf86_0_cpython  conda-forge/linux-64      38MB
#7 24.59   + python_abi                       3.11  3_cp311             conda-forge/linux-64       6kB
#7 24.59   + readline                        8.1.2  h0f457ee_0          conda-forge/linux-64     298kB
#7 24.59   + rich                           12.6.0  pyhd8ed1ab_0        conda-forge/noarch       175kB
#7 24.59   + rich-click                      1.5.2  pyhd8ed1ab_0        conda-forge/noarch        22kB
#7 24.59   + setuptools                     65.5.1  pyhd8ed1ab_0        conda-forge/noarch       748kB
#7 24.59   + six                            1.16.0  pyh6c4a22f_0        conda-forge/noarch        14kB
#7 24.59   + tk                             8.6.12  h[278](https://github.com/StaPH-B/docker-builds/actions/runs/3587047240/jobs/6036954431#step:6:280)26a3_0          conda-forge/linux-64       3MB
#7 24.59   + typing_extensions               4.4.0  pyha770c72_0        conda-forge/noarch        30kB
#7 24.59   + tzdata                          2022g  h191b570_0          conda-forge/noarch       108kB
#7 24.59   + verboselogs                       1.7  py_0                conda-forge/noarch         9kB
#7 24.59   + wget                           1.20.3  ha35d2d1_1          conda-forge/linux-64     835kB
#7 24.59   + wheel                          0.38.4  pyhd8ed1ab_0        conda-forge/noarch        33kB
#7 24.59   + xz                              5.2.6  h166bdaf_0          conda-forge/linux-64     418kB
#7 24.59   + zlib                           1.2.13  h166bdaf_4          conda-forge/linux-64      94kB
#7 24.59 
#7 24.59   Summary:
#7 24.59 
#7 24.59   Install: 78 packages
#7 24.59 
#7 24.59   Total download: 119MB
```

**Comment by kapsakcj** [comment]
FYI - I created blank repos on dockerhub and quay in prep for deployment

**Comment by erinyoung** [comment]
It looks like the tests all worked as intended 

```
#11 3.630                    Serogroup Results                   
#11 3.630 ┏━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓
#11 3.630 ┃ sample           ┃ serogroup ┃ coverage ┃ fragments ┃
#11 3.630 ┡━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩
#11 3.630 │ O6-GCF_000817165 │ O1        │ 11.17    │ 2         │
#11 3.630 │ O6-GCF_000817165 │ O2        │ 9.27     │ 2         │
#11 3.630 │ O6-GCF_000817165 │ O3        │ 10.66    │ 2         │
#11 3.630 │ O6-GCF_000817165 │ O4        │ 13.59    │ 2         │
#11 3.630 │ O6-GCF_000817165 │ O5        │ 0        │ 0         │
#11 3.630 │ O6-GCF_000817165 │ O6        │ 90.93    │ 3         │
#11 3.630 │ O6-GCF_000817165 │ O7        │ 10.98    │ 2         │
#11 3.630 │ O6-GCF_000817165 │ O9        │ 11.88    │ 2         │
#11 3.630 │ O6-GCF_000817165 │ O10       │ 11.62    │ 2         │
#11 3.630 │ O6-GCF_000817165 │ O11       │ 14.85    │ 2         │
#11 3.630 │ O6-GCF_000817165 │ O12       │ 1.12     │ 1         │
#11 3.630 │ O6-GCF_000817165 │ O13       │ 13.05    │ 1         │
#11 3.630 │ O6-GCF_000817165 │ WyzB      │ 0        │ 0         │
#11 3.630 └──────────────────┴───────────┴──────────┴───────────┘
#11 3.631 Serogroup Results written to ./O6-GCF_000817165.details.tsv
#11 3.631 
#11 3.632                   Predicted Serogroup                  
#11 3.632 ┏━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓
#11 3.632 ┃ sample           ┃ serogroup ┃ coverage ┃ fragments ┃
#11 3.632 ┡━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩
#11 3.632 │ O6-GCF_000817165 │ NT        │ 0        │ 0         │
#11 3.632 └──────────────────┴───────────┴──────────┴───────────┘
#11 3.632 Predicted serogroup result written to ./O6-GCF_000817165.tsv
```

```
#11 5.440 Running BLASTN...
#11 5.513 Writing outputs...
#11 5.514 BLASTN results written to ./empty.blastn.tsv
#11 5.514 
#11 5.522               Serogroup Results              
#11 5.522 ┏━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓
#11 5.522 ┃ sample ┃ serogroup ┃ coverage ┃ fragments ┃
#11 5.522 ┡━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩
#11 5.522 │ empty  │ O1        │ 0        │ 0         │
#11 5.522 │ empty  │ O2        │ 0        │ 0         │
#11 5.522 │ empty  │ O3        │ 0        │ 0         │
#11 5.522 │ empty  │ O4        │ 0        │ 0         │
#11 5.522 │ empty  │ O5        │ 0        │ 0         │
#11 5.522 │ empty  │ O6        │ 0        │ 0         │
#11 5.522 │ empty  │ O7        │ 0        │ 0         │
#11 5.522 │ empty  │ O9        │ 0        │ 0         │
#11 5.522 │ empty  │ O10       │ 0        │ 0         │
#11 5.522 │ empty  │ O11       │ 0        │ 0         │
#11 5.522 │ empty  │ O12       │ 0        │ 0         │
#11 5.522 │ empty  │ O13       │ 0        │ 0         │
#11 5.522 │ empty  │ WyzB      │ 0        │ 0         │
#11 5.522 └────────┴───────────┴──────────┴───────────┘
#11 5.523 Serogroup Results written to ./empty.details.tsv
#11 5.523 
#11 5.524              Predicted Serogroup             
#11 5.524 ┏━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓
#11 5.524 ┃ sample ┃ serogroup ┃ coverage ┃ fragments ┃
#11 5.524 ┡━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩
#11 5.524 │ empty  │ NT        │ 0        │ 0         │
#11 5.524 └────────┴───────────┴──────────┴───────────┘
#11 5.525 Predicted serogroup result written to ./empty.tsv
```

**Comment by rpetit3** [comment]
> This... has a lot of dependencies. I can see why you went micromamba route:

Many of these dependencies [come from blast](https://bioconda.github.io/recipes/blast/README.html#package-blast).

For a non-conda, `pasty` only needs blastn, python>3.7, [executor](https://executor.readthedocs.io/en/latest/), and [rich-click](https://github.com/ewels/rich-click)

**Comment by kapsakcj** [comment]
Thanks, Robert. I will try out using blast pre-compiled binaries and see if I can get the docker image smaller with a different base image, perhaps `ubuntu:focal`, and install other dependencies w/o use of conda

**Comment by kapsakcj** [comment]
Yep, much smaller with an ubuntu base image:
```bash
$ docker images | grep 'pasty'
kapsakcj/pasty     1.0.1-full-ubuntu-base                  46fb0ee18233   7 seconds ago    299MB
kapsakcj/pasty     1.0.1-app-only-ubuntu-base              d0b7bf8aba30   36 seconds ago   298MB
kapsakcj/pasty     1.0.1-full                              3d21d45d155e   19 minutes ago   698MB
kapsakcj/pasty     1.0.1-app-only                          a92ea6ee2948   20 minutes ago   678MB
```

I'll push a commit shortly with the new dockerfile

**Comment by kapsakcj** [comment]
OK this is ready for review now. In summary I have:

- switched to `ubuntu:jammy` base image (has a more recent version of blast available via `apt`)
- upgraded to pasty v1.0.2 which has a brand-spanking new set of test assemblies and a few bug fixes. Test data now included in docker image
- installed python3, pip3, & 2 python deps `rich-click` and `executor`
- updated main README.md
- updated pasty-specific README.md with new version

**Comment by kapsakcj** [comment]
Here's the relevant GHActions log with the updated dockerfile: https://github.com/StaPH-B/docker-builds/actions/runs/3595834395/jobs/6055802927

the most recent runs had all the alyers cached, so you can't really see the output of the image building process

**Comment by erinyoung** [comment]
Tests still ran great

**Review by erinyoung — APPROVED** [review]

**Comment by erinyoung** [comment]
I think it looks great, and I've approved this PR. Am I allowed to merge it?

**Comment by erinyoung** [comment]
I have merged this. 

Sending to dockerhub and quay and overwriting the 'latest' tag

**Pull request merged**
