### PR TITLE
add recent medaka versions

### PR DESCRIPTION
**Pull request by kapsakcj**
Need testing and potentially fixing before merging into master & building on dockerhub.

These 3 images built successfully, but need to run data through.

I'm testing the 1.4.3 version and keep getting an error, but this may be due to malformed input data...not sure.

So this is a draft PR for now.

cc @matt-plumb

### CODE REVIEW

**Comment by erinyoung** [comment]
Sorry for taking so long to look at this. I'm going to build the 1.3.3 and 1.4.4 and test those. It looks like there's now a 1.5.

How often does medaka update?

**Comment by kapsakcj** [comment]
Thanks for taking a look, Erin. Currently have this as a "draft" PR since it's not ready for prime time. It's been a while since I tested these docker images, but remember hitting an error with at least one of them when running `medaka consensus`. I would really appreciate testing if you have some nanopore data handy

Medaka updates every 3-4 months-ish (https://github.com/nanoporetech/medaka/releases). They are up to 1.5.0 as of today, which is missing from this PR.

**Comment by erinyoung** [comment]
I tried to test these out, but I can't build the image locally in my setup unfortunately. 

I pruned all my containers with 
```
docker container prune
```
Removed everything in `/var/lib/docker` and `/var/cache/apt/archives`

And followed with 
```
docker build --tag medaka_test:1.4.4 medaka_1.4.4
```

```
Error processing tar file(exit status 1): write /medaka/venv/lib/python3.6/site-packages/medaka-1.4.4-py3.6-linux-x86_64.egg/exes/bgzip: no space left on device
```

And a similar error with 1.3.3
```
Error processing tar file(exit status 1): open /medaka/venv/lib/python3.6/site-packages/networkx/algorithms/connectivity/tests/__pycache__/test_edge_kcomponents.cpython-36.pyc: no space left on device
```

I'll look into increasing the amount of space allocated to these relevant directories, but I thought I would let you know that I tried.

**Comment by kapsakcj** [comment]
Closing since I don't plan on revisiting this PR. ONT makes their own docker images available on dockerhub: https://hub.docker.com/r/ontresearch/medaka/tags

& dockerfile here: https://github.com/nanoporetech/medaka/blob/master/Dockerfile

**Pull request closed without merging**
