### PR TITLE
update to pangolin data 1.14

### PR DESCRIPTION
**Pull request by kapsakcj**
This PR updates the Pangolin 4.1.2 dockerfile to use pangolin-data 1.14. No other changes.

New lineages released via pangolin-data 1.14:

```
BA.2.9.6
BA.2.10.4
BA.2.38.3
BA.2.75.1
BA.2.75.2
BA.2.76.1
BA.2.76.2

BG.6
BH.1
BJ.1

BA.5.1.9
BA.5.1.10
BA.5.1.11
BA.5.5.1
BA.5.6.2
BA.5.10

BE.1.2
BF.13
BF.14
BK.1

XAQ
XAR

Withdrew BA.2.36.1, re-designated as BA.2.82
------
alias reminders:
"BE": "B.1.1.529.5.3.1"
"BF": "B.1.1.529.5.2.1"
"BG": "B.1.1.529.2.12.1"
"BH": "B.1.1.529.2.38.3"
"BJ": "B.1.1.529.2.10.1"
"BK": "B.1.1.529.5.1.10"
```

EDIT: added alias reminders and re-arranged the new lineages with an attempt to order/sort new lineages in numerical order

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
New docker image name and tag will be `staphb/pangolin:4.1.2-pdata-1.14`

For easy copy/paste when deploying: `4.1.2-pdata-1.14`

**Review by erinyoung — APPROVED** [review]
The only thing that I see as changed is the pangolin data version

**Comment by erinyoung** [comment]
Did you want @kevinlibuit 's review as well or should I merge this?

**Comment by kapsakcj** [comment]
Please go ahead and merge!

**Comment by erinyoung** [comment]
I'm going to merge this PR, but I'll let you deploy the container.

**Comment by kapsakcj** [comment]
Thank you, will do!

**Pull request merged**
