### PR TITLE
Replace per-tool deploy wfs with single wf that takes input

### PR DESCRIPTION
**Pull request by SarahNadeau**
This PR replaces the per-tool deploy workflows (e.g. `deploy-bbtools.yml`) with a single workflow `manual_deploy.yml` that takes the tool and version as manual input. 

The new workflow's input options look like this:
Screen Shot 2022-04-27 at 10 37 23 AM

I tested it out like this (https://github.com/SarahNadeau/docker-builds/actions/runs/2232155079):
Screen Shot 2022-04-27 at 10 37 35 AM

Which successfully deployed the DSK image to my docker hub: https://hub.docker.com/repository/docker/snads/dsk. This does make it easy for people to publish staphb images under their own account on docker hub. Is this a problem? Note: it's always possible for people to do this given we share the dockerfiles, this just makes it easier.

### CODE REVIEW

**Comment by erinyoung** [comment]
This looks so nice and shiny! I'd like to try this on Curtis's new Kraken container.

Right now I can't merge this because of conflicting files `.github/workflows/deploy-pangolin-v4.0.6.yml`, which I cannot resolve on my end.

**Comment by kapsakcj** [comment]
when I get some free time later this week, I'll resolve the conflict. Sarah has the yml file deleted in her PR, so it shouldn't be too bad.

thanks for your patience, I realize there's a few PRs that are awaiting my review!

**Comment by erinyoung** [comment]
With https://github.com/StaPH-B/docker-builds/pull/355, many of these files are not needed anymore. I've changed it back to draft until that one is merged, and then I will adjust my files.

**Review by erinyoung — APPROVED** [review]
There's just a file that I can't resolve issues for.

**Comment by kapsakcj** [comment]
Manually merged via the command line! Thanks, @SarahNadeau !

**Pull request merged**
