### PR TITLE
busco-prok fix

### PR DESCRIPTION
**Pull request by Kincekara**
bacteria_odb is not accessible when a volume binds to /data folder. This is a problem for cromwell and terra applications. Running "busco --download" command in root makes db path /busco_downloads/lineages/...

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Review by erinyoung — APPROVED** [review]
Good to know!

**Comment by erinyoung** [comment]
What tag do you want to use? `5.6.1-prok-bacteria_odb10_2024-01-08-1` ?

**Comment by Kincekara** [comment]
I don't think anyone except me pulled it yet.  We can override it 5.6.1-prok-bacteria_odb10_2024-01-08 🙊

**Comment by kapsakcj** [comment]
just chiming in to state my 2 cents - I would overwrite the existing tag since this image and tag are sow new. 

This PR is a bug fix anyways so if someone was using it previously, they shouldn't be caught off guard and will likely benefit from the change

**Pull request merged**
