### PR TITLE
Update Pangolin recipe to version 2.0.1

### PR DESCRIPTION
**Pull request by andersgs**
This update Includes installation of PangoLEARN, and pulling out version information to an ENV statement so it is easy to generate updates.

I also use the version numbers to specify the download of specific tagged releases in GitHub to aid in the reproducibility of the build.

### CODE REVIEW

**Comment by kapsakcj** [comment]
Hey @andersgs , thanks so much for the PR and for contributing to this repo. I'm more than happy to get this added and built on dockerhub for anyone to use.

Looks like Aine has released a few more minor releases, up to 2.0.4 for  `pangolin`. Is it OK if we update the dockerfile to the latest release? If so, please also rename the sub-dir `/pangolin/2.0.1/Dockerfile --> /pangolin/2.0.4/Dockerfile`

Either way - I tried building the docker image locally using your dockerfile and I hit a snag on line 55 of your Dockerfile:
```
Step 22/24 : RUN /bin/bash -c 'cd .. && source activate pangolin && wget https://github.com/cov-lineages/lineages/archive/${PANGOLIN_LEARN_VERSION}.tar.gz && tar -xf ${PANGOLIN_LEARN_VERSION}.tar.gz && cd pangoLEARN-${PANGOLIN_LEARN_VERSION} && pip install .'
 ---> Running in 7717612c90ce
--2020-07-23 13:12:16--  https://github.com/cov-lineages/lineages/archive/2020-07-20.tar.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/cov-lineages/lineages/tar.gz/2020-07-20 [following]
--2020-07-23 13:12:16--  https://codeload.github.com/cov-lineages/lineages/tar.gz/2020-07-20
Resolving codeload.github.com (codeload.github.com)... 140.82.113.9
Connecting to codeload.github.com (codeload.github.com)|140.82.113.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-23 13:12:16 ERROR 404: Not Found.

The command '/bin/sh -c /bin/bash -c 'cd .. && source activate pangolin && wget https://github.com/cov-lineages/lineages/archive/${PANGOLIN_LEARN_VERSION}.tar.gz && tar -xf ${PANGOLIN_LEARN_VERSION}.tar.gz && cd pangoLEARN-${PANGOLIN_LEARN_VERSION} && pip install .'' returned a non-zero code: 8
```

I'm not very familiar with Pangolin, so I'm not sure what needs to be done with that RUN layer (lines 56-61). Looks like that github repository doesn't exist anymore? https://github.com/cov-lineages/lineages/archive/

**Comment by kapsakcj** [comment]
Also, it would be great if you could add two more LABELS with your name and email (if you don't mind)
```Dockerfile
LABEL maintainer2="Anders Goncalves da Silva"
LABEL maintainer2.email="your@email.com"
```

**Comment by kapsakcj** [comment]
I think line 11 needs to be updated too? The url redirects me to here https://github.com/cov-lineages/pangolin

**Comment by andersgs** [comment]
@kapsakcj I have updated the recipe to 2.0.4, fixed the issue with line 55, and have added the extra labels. 

Thank you!

**Comment by andersgs** [comment]
And updated the URL.

**Comment by kapsakcj** [comment]
Thanks for making my requested changes, much appreciated. I was able to build the image successfully and pull up help options and various version numbers with no issues. I'll leave the testing of actually running tool on real data to you and others that want to use it.

I'll push this to dockerhub and it will be available under the docker hub repo and tag `staphb/pangolin:2.0.4` and (until a new dockerfile is written) `staphb/pangolin:latest`

Side note: disregard TravisCI failing - it's unrelated to your PR. I'm still going to merge.

**Pull request merged**
