### PR TITLE
revamping artic with updated medaka

### PR DESCRIPTION
**Pull request by erinyoung**
This is a new container with the most-current artic and medaka versions. I've also finally added artic to the licenses.

Both of these tools' bioconda packages lag significantly, and I'd like the current medaka models.

I've changed the directory structure of this image. It's now 
```
artic/${artic_version}-${medaka_version}/
```

I would like the tag to also follow the pattern of ${artic_version}-${medaka_version}, so this one would be tagged `1.2.4-1.9.1`.

I have not included any primers in this. It's already fairly large and my use-case is with non-artic primers at the moment anyway.

Lastly, in a future PR, I'd like to move the old artic* files into /artic for cleanliness purposes.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Sorry! Since I'm downloading files from the ENA, I can't test my 'test' locally. I'll fix this in gitpod and then convert this from draft stage.

**Comment by erinyoung** [comment]
@kevinlibuit , I hope you have time to review this image. It's now ready for review (I had some typos in the test layer that I needed to resolve). 

Once I finish this image, I'm going to apply the same ideas to the artic-ncov2019-epi2me Dockerfile (https://github.com/StaPH-B/docker-builds/issues/689)

**Comment by erinyoung** [comment]
@kevinlibuit , does this look like it would work?

**Comment by erinyoung** [comment]
There's a current version of this on UPHL's quay repo : quay.io/uphl/artic tag 1.2.4-1.9.4-1

**Comment by kevinlibuit** [comment]
Will also need to test availabilities of updated models, e.g. `r103_fast_snp_g507`

**Comment by erinyoung** [comment]
@kevinlibuit , medaka has gone through a few updates recently, so I've updated the Dockerfile to use the most recent version of medaka.

The readme now lists all the supported models for medaka, or did you have something else in mind?

There's a current version of this image at quay.io/uphl/artic tag 1.2.4-1.11.1

**Comment by erinyoung** [comment]
@kevinlibuit , do you have time to review this?

**Comment by kevinlibuit** [comment]
Apologies for the delay! Tested this both locally and used the uphl quay image to ensure no issues with our workflows on Terra. Thanks, also, for adding info on available models.

**Comment by kevinlibuit** [comment]
Accidentally closed!

**Review by kevinlibuit — APPROVED** [review]

**Pull request merged**
