### PR TITLE
Kgl abricate insaflu

### PR DESCRIPTION
**Pull request by kevinlibuit**
Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
Everything looks great, the only addition I might recommend is adding to the test layer to specifically test the insaflu database.

Not required, but would be good to test the custom DB.

Steps:
- download one or a couple of complete Flu genome with known subtypes (via NCBI `datasets` or perhaps `wget`'ing an assembly from NCBI FTP or ENA FTP)
- run through ABRicate
- grep output TSV for expected strings, example `Yamagata` or H or N subtypes

**Comment by kevinlibuit** [comment]
Great suggestion! Added a type_b flu assembly for a quick test

**Review by kapsakcj — APPROVED** [review]
Thanks for adding that test! GHActions workflow output looks good, I'm going to merge and deploy the docker image under the custom docker image name & tag `staphb/abricate:1.0.1-insaflu`

```
#16 [test 3/4] RUN abricate --db insaflu /data/SRR10013255.irma.consensus.fasta > /data/abricate_flu.tsv
#16 0.149 Using nucl database insaflu:  34 sequences -  2022-Nov-16
#16 0.149 Processing: /data/SRR10013255.irma.consensus.fasta
#16 0.212 Found 2 genes in /data/SRR10013255.irma.consensus.fasta
#16 0.212 Tip: abricate can also find virulence factors; use --list to see all supported databases.
#16 0.212 Done.
#16 DONE 0.2s

#17 [test 4/4] RUN grep "Type_B" /data/abricate_flu.tsv && echo done
#0 0.060 /data/SRR10013255.irma.consensus.fasta	SRR10013255_7	31	1171	+	M1	1-1141/1141	===============	0/0	100.00	96.67	insaflu	AF100378	AF100378.1 Influenza B virus B/Yamagata/16/88 segment 7 M1 matrix protein (M) and BM2 protein (BM2) genes complete cds	Type_B
#17 0.060 done
#17 DONE 0.1s
```

**Comment by kapsakcj** [comment]
OK to delete your dev branch?

**Comment by kevinlibuit** [comment]
May want to keep that date on the tag (I used 220727 as that's when it was [populated to the wf-flu repo](https://github.com/epi2me-labs/wf-flu/blob/prerelease/data/primer_schemes/V1/blastdb/insaflu/sequences)) in the event that there's an updated db before a new abricate release

**Comment by kevinlibuit** [comment]
> OK to delete your dev branch?

Yup!

**Comment by kapsakcj** [comment]
OK, I used this as the docker image name and tag instead `staphb/abricate:1.0.1-insaflu-220727`. Should be available on dockerhub and quay shortly

**Pull request merged**
