### PR TITLE
adds pangolin 4.3.1 and pangolin-data 1.23

### PR DESCRIPTION
**Pull request by kapsakcj**
added dockerfile for pangolin 4.3.1 and pdata 1.23. 

~~Still need to upgrade to usher 0.6.3 when it is available on bioconda due to the edge case bug mentioned in the pangolin-assignment release: https://github.com/cov-lineages/pangolin-assignment/releases/tag/v1.23 . Set this PR as a draft for now.~~

Changes from previous dockerfile:

- upgraded to micromamba 1.5.1 (which looks to be a debian:bookworm base image)
- upgraded to pangolin-data 1.23
- upgraded to scorpio 0.3.19
- upgraded to constellations 0.1.12
- ~~(when available) upgrade to usher 0.6.3~~ We are sticking with v0.6.2

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Sorry for getting to this so late!

**Comment by kapsakcj** [comment]
OK this is ready for review & deployment. I don't want to wait for the next version of usher to be released to get this image published & available.

I added a warning to the README.md for this docker image and will communicate the edge case bug when announcing that the docker image is available to slacks/elsewhere

We can upgrade to usher v0.6.3 the next time we release a docker image for `pangolin`

**Review by erinyoung — APPROVED** [review]
Everything looks good!

**Comment by erinyoung** [comment]
I have merged this PR, but I am going to let you push to dockehub and quay.

I think that it would use the tag '4.3.1-pdata-1.23', but I'd rather be "safe than sorry". :D

**Pull request merged**
