### PR TITLE
Add gitpod environment

### PR DESCRIPTION
**Pull request by kapsakcj**
Please disregard the older commits from June - they do not include any code changes in this PR. I couldn't figure out how to sync my fork properly. 

Anyways... this PR adds basic GitPod functionality for this repo. TY @rpetit3 for the [inspiration & code](https://github.com/rpetit3/pasty/commit/baa0a49f5e72370ded3e186e90578f20ada0833a) 😄 

Once the PR is merged, anyone can visit the link https://gitpod.io/#https://github.com/StaPH-B/docker-builds

And then magically a web-based Visual Studio Code environment is launched in GitPod. This environment is based on the nf-core training environment (actually managed via a docker image: `nfcore/gitpod:latest`) that includes `nextflow`, `docker`, `nf-core`, `conda`, `mamba`, and probably others. I wonder if we can get `singularity` installed in the environment too??

As long as you are signed in with your GitHub account, you get 50 free hours running the GitPod environment.

Perfect environment for trainings considering trainees don't need to bring their own compute infrastructure.

I spun the GitPod environment up on my fork and was able to build a spades docker image using the dockerfile from the repo. 

This is my first attempt at having a functional GitPod environment - there's a lot more we could do with it, but I thought it would be nice to have this in place for future trainings

### CODE REVIEW

**Comment by erinyoung** [comment]
Nice! Singularity would be nice. 

I think the StaPH-B toolkit would be nice, too.

**Review by erinyoung — APPROVED** [review]

**Comment by erinyoung** [comment]
I've approved this idea, but I'd like to test it first.

**Comment by kapsakcj** [comment]
According to Seqera's docs, singularity will not work in GitPod? https://training.seqera.io/#_singularity

but we could definitely include the staphb-toolkit code somewhere. perhaps `git clone` it upon startup of the environment.

I think you can test by going https://gitpod.io/#https://github.com/kapsakcj/docker-builds

**Comment by erinyoung** [comment]
Actually, after some thought I think this should go in its own StaPH-B repo because it doesn't really have anything to do with Dockerfiles or the the goals of StaPH-B/docker-builds

**Comment by kapsakcj** [comment]
Can we re-visit this PR? It would be super handy to have gitpod available if we don't have access to a computer and want to do some quick development and testing

Additionally it will be useful for trainings in the future.

I'm happy to demo at the next maintainer's meeting

**Pull request merged**
