### PR TITLE
Adding bakta light

### PR DESCRIPTION
**Pull request by erinyoung**
This is the same as https://github.com/StaPH-B/docker-builds/pull/866, except there's now a 1.5 G downloaded and decompressed in it.

Please complete the prior PR first.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by Kincekara** [comment]
It may be good to have the database version or date in the name tag like in other images in the repo. I think this is database version 5.1 released on  2024-01-19

https://zenodo.org/records/10522951

**Comment by erinyoung** [comment]
Good idea! 

Something like 1.9.2-5.1-light ?

There's a full database for 5.1 as well.

**Comment by Kincekara** [comment]
"1.9.2-5.1-light" is good!

**Comment by erinyoung** [comment]
@Kincekara , were there any changes you wanted me to make? Did you want me to change the directory?

**Comment by Kincekara** [comment]
@erinyoung Sorry, I forgot this. It may be good to change the directory, too.

**Comment by erinyoung** [comment]
@Kincekara , I've changed the name of the directory. Was there anything you noticed?

**Comment by Kincekara** [comment]
@erinyoung Looks good to me. I am merging this.

**Review by Kincekara — APPROVED** [review]

**Comment by Kincekara** [comment]
Thank you for PR!
You can follow the image deployment from here: https://github.com/StaPH-B/docker-builds/actions/runs/7995413834.

**Pull request merged**
