### PR TITLE
update tbprofiler v6.4.0

### PR DESCRIPTION
**Pull request by sage-wright**
This PR updates TBProfiler to v6.4.0

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
The tests looked like worked:
```
#12 [test 3/3] RUN wget -q ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR166/009/ERR1664619/ERR1664619_1.fastq.gz &&     wget -q ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR166/009/ERR1664619/ERR1664619_2.fastq.gz &&     tb-profiler profile -1 ERR1664619_1.fastq.gz -2 ERR1664619_2.fastq.gz -t 2 -p ERR1664619 --txt
#12 117.5 [18:46:09] INFO     Using ref file:                                    db.py:610
#12 117.5                     /opt/conda/share/tbprofiler//tbdb.fasta                     
#12 117.5            INFO     Using gff file:                                    db.py:610
#12 117.5                     /opt/conda/share/tbprofiler//tbdb.gff                       
#12 117.5            INFO     Using bed file:                                    db.py:610
#12 117.5                     /opt/conda/share/tbprofiler//tbdb.bed                       
#12 117.5            INFO     Using json_db file:                                db.py:610
#12 117.5                     /opt/conda/share/tbprofiler//tbdb.dr.json                   
#12 117.6            INFO     Using variables file:                              db.py:610
#12 117.6                     /opt/conda/share/tbprofiler//tbdb.variables.json            
#12 117.6            INFO     Using spoligotype_spacers file:                    db.py:610
#12 117.6                     /opt/conda/share/tbprofiler//tbdb.spoligotype_spac          
#12 117.6                     ers.txt                                                     
#12 117.6            INFO     Using spoligotype_annotations file:                db.py:610
#12 117.6                     /opt/conda/share/tbprofiler//tbdb.spoligotype_list          
#12 117.6                     .csv                                                        
#12 117.6            INFO     Using bedmask file:                                db.py:610
#12 117.6                     /opt/conda/share/tbprofiler//tbdb.mask.bed                  
#12 117.6            INFO     Using barcode file:                                db.py:610
#12 117.6                     /opt/conda/share/tbprofiler//tbdb.barcode.bed               
#12 117.6            INFO     Using rules file:                                  db.py:610
#12 117.6                     /opt/conda/share/tbprofiler//tbdb.rules.txt                 
#12 117.6            INFO     Trimming reads                                   fastq.py:39
#12 120.5 [18:46:12] INFO     Mapping to reference genome                      fastq.py:53
#12 165.5 
Calling variants:   0%|          | 0/73 [00:00<?, ?it/s]
Calling variants:   1%|▏         | 1/73 [00:00<00:31,  2.25it/s]
Calling variants:   4%|▍         | 3/73 [00:00<00:11,  5.84it/s]
Calling variants:   7%|▋         | 5/73 [00:00<00:07,  8.74it/s]
Calling variants:  10%|▉         | 7/73 [00:00<00:06, 10.92it/s]
Calling variants:  12%|█▏        | 9/73 [00:00<00:04, 12.82it/s]
Calling variants:  15%|█▌        | 11/73 [00:01<00:04, 13.90it/s]
Calling variants:  18%|█▊        | 13/73 [00:01<00:04, 13.07it/s]
Calling variants:  21%|██        | 15/73 [00:01<00:04, 14.00it/s]
Calling variants:  23%|██▎       | 17/73 [00:01<00:03, 14.65it/s]
Calling variants:  26%|██▌       | 19/73 [00:01<00:03, 14.49it/s]
Calling variants:  29%|██▉       | 21/73 [00:01<00:03, 15.04it/s]
Calling variants:  32%|███▏      | 23/73 [00:01<00:03, 14.76it/s]
Calling variants:  34%|███▍      | 25/73 [00:02<00:03, 14.90it/s]
Calling variants:  37%|███▋      | 27/73 [00:02<00:03, 15.33it/s]
Calling variants:  40%|███▉      | 29/73 [00:02<00:02, 15.66it/s]
Calling variants:  42%|████▏     | 31/73 [00:02<00:02, 15.17it/s]
Calling variants:  45%|████▌     | 33/73 [00:02<00:02, 14.82it/s]
Calling variants:  48%|████▊     | 35/73 [00:02<00:02, 14.60it/s]
Calling variants:  51%|█████     | 37/73 [00:02<00:02, 15.48it/s]
Calling variants:  53%|█████▎    | 39/73 [00:02<00:02, 16.16it/s]
Calling variants:  56%|█████▌    | 41/73 [00:03<00:02, 15.50it/s]
Calling variants:  59%|█████▉    | 43/73 [00:03<00:01, 15.79it/s]
Calling variants:  62%|██████▏   | 45/73 [00:03<00:01, 15.99it/s]
Calling variants:  64%|██████▍   | 47/73 [00:03<00:01, 16.14it/s]
Calling variants:  67%|██████▋   | 49/73 [00:03<00:01, 16.65it/s]
Calling variants:  70%|██████▉   | 51/73 [00:03<00:01, 15.78it/s]
Calling variants:  73%|███████▎  | 53/73 [00:03<00:01, 15.19it/s]
Calling variants:  75%|███████▌  | 55/73 [00:03<00:01, 15.55it/s]
Calling variants:  78%|███████▊  | 57/73 [00:04<00:01, 15.46it/s]
Calling variants:  81%|████████  | 59/73 [00:04<00:00, 15.70it/s]
Calling variants:  84%|████████▎ | 61/73 [00:04<00:00, 15.91it/s]
Calling variants:  86%|████████▋ | 63/73 [00:04<00:00, 15.70it/s]
Calling variants:  89%|████████▉ | 65/73 [00:04<00:00, 14.22it/s]
Calling variants:  92%|█████████▏| 67/73 [00:04<00:00, 13.90it/s]
Calling variants:  95%|█████████▍| 69/73 [00:04<00:00, 14.23it/s]
Calling variants:  97%|█████████▋| 71/73 [00:05<00:00, 14.85it/s]
Calling variants: 100%|██████████| 73/73 [00:05<00:00, 15.66it/s]
Calling variants: 100%|██████████| 73/73 [00:05<00:00, 14.23it/s]
#12 170.6 
Indexing variants:   0%|          | 0/73 [00:00<?, ?it/s]
Indexing variants:  18%|█▊        | 13/73 [00:00<00:00, 98.52it/s]
Indexing variants:  40%|███▉      | 29/73 [00:00<00:00, 123.28it/s]
Indexing variants:  86%|████████▋ | 63/73 [00:00<00:00, 211.62it/s]
Indexing variants: 100%|██████████| 73/73 [00:00<00:00, 184.69it/s]
#12 171.2 [18:47:02] INFO     Running delly                                      bam.py:84
#12 171.2            ERROR    delly: error while loading shared libraries:    utils.py:534
#12 171.2                     libboost_iostreams.so.1.85.0: cannot open                   
#12 171.2                     shared object file: No such file or directory               
#12 171.2                                                                                 
#12 171.2            ERROR    Delly failed, skipping                             bam.py:96
#12 171.3            INFO     Running snpEff                                    vcf.py:125
#12 173.3 [18:47:04] INFO     Loading snpEff annotations                        vcf.py:163
#12 174.1 [18:47:05] INFO     Getting genotypes for positions in bed file       bam.py:291
#12 176.4 [18:47:07] INFO     Calculating bamstats                              bam.py:351
#12 178.9 [18:47:10] INFO     Getting qc metrics for regions                    bam.py:388
#12 178.9            INFO     Calculating depth in regions                       bam.py:54
#12 182.2 [18:47:13] INFO     Calculating median depth using samtools           bam.py:221
#12 184.4 [18:47:16] INFO     Getting missing genomic positions                 bam.py:381
#12 185.0            INFO     Writing outputs                                  output.py:8
#12 185.0            INFO     Writing json file:                              output.py:15
#12 185.0                     /tests/results/ERR1664619.results.json                      
#12 185.0            INFO     Writing text file:                              output.py:19
#12 185.0                     /tests/results/ERR1664619.results.txt                       
#12 185.1            INFO     Profiling finished sucessfully!              tb-profiler:208
```

**Comment by erinyoung** [comment]
@sage-wright , does Delly failing mean anything?

**Comment by kapsakcj** [comment]
I haven't read into this but wanted to share this: https://github.com/bioconda/bioconda-recipes/pull/50412

**Comment by kapsakcj** [comment]
and this: https://github.com/jodyphelan/TBProfiler/issues/393

**Comment by sage-wright** [comment]
We were able to fix this issue by pinning Delly to v1.2.6. This is because the latest bioconda recipe for tb-profiler doesn't have a pinned version of Delly so it grabbed v1.3.1 which doesn't have the boost-cpp=1.78.0 pin. The v1.2.6 _did_ have this pin. We let Jody know about this [here](https://github.com/jodyphelan/TBProfiler/issues/393#issuecomment-2452076859)

**Review by kapsakcj — APPROVED** [review]
the libboost shared object error went away after pinning to an older version of delly. We inspected the tb-profiler output files and everything looked normal/expected.

Thanks for this update, Sage!

**Comment by jodyphelan** [comment]
Updating the tb-profiler recipe now

**Comment by kapsakcj** [comment]
deploy workflow here: https://github.com/StaPH-B/docker-builds/actions/runs/11632155906

the new docker image should be available on dockerhub and quay in the next 10-20 minutes.

Thank you @jodyphelan ! We will update the dockerfile upon the next tb-profiler release to not specifically pin delly.

**Pull request merged**
