### PR TITLE
NCBI-amrfinderplus version 3.11.14

### PR DESCRIPTION
**Pull request by erinyoung**
There's a new version of amrfinder ([3.11.14](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.11.14
)). This new version has existed since May, and I haven't created a new dockerfile because there's normally a new database released closely thereafter. 

This new version has a new feature : works on gz files (but only if gunzip is in path). This would be really handy for *me*. 

For this version I:
- copied the prior version's dockerfile and readme.md file
- added tabs
- put path on one line
- added gzip to the apt-get layer
- added CMD layer

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Ignore all the "revert" commits. I added CMD to the wrong Dockerfile, and then it took me too long to fix that file and get CMD onto the right one. 🤦‍♀️

**Comment by kapsakcj** [comment]
I removed `make` and `g++` from the list of stuff installed via `apt` since it reduces the final size of the image a considerable amount. They are also not required since we install amrfinder from pre-compiled linux binary instead of compiling source code. Reduced the uncompressed image size by ~220MB:
```
$ docker images | grep amrfinder
erin/amrfinder   3.11.14-2023-04-17.1-deps-removed   c8fb1a7836a6   9 minutes ago    970MB
erin/amrfinder   3.11.14-2023-04-17.1                0802048350a0   25 minutes ago   1.19GB
```

Due to removing these, I had to install `libgomp1` as it's required by by `makeblastdb`.

I also added a test at the end of the test stage to make sure `gunzip` is installed

**Review by kapsakcj — APPROVED** [review]
Everything looks good to me. Thanks for the PR!

I'll merge and deploy to dockerhub and quay using the new tag `3.11.14-2023-04-17.1` and overwrite `latest` tag

**Comment by kapsakcj** [comment]
deploy workflow here: https://github.com/StaPH-B/docker-builds/actions/runs/5393976586

don't forget to delete your dev branch

**Pull request merged**
