### PR TITLE
Updated DNAAPLER and Mykrobe 

### PR DESCRIPTION
**Pull request by evagunawan**
Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

Updated main README.md for mykrobe and dnaapler for docker workshop. Updated both mykrobe and dnaapler to next version indicated by Dr. Young. Added README.md for both new versions.

### CODE REVIEW

**Comment by erinyoung** [comment]
These look great!

Is there any reason why dnaapler is version 0.2.0 instead of [0.4.0](https://github.com/gbouras13/dnaapler/releases/tag/v0.4.0), which is the latest version?

Did you intend to have mykrobe be part of this PR or should I look for another PR?

**Comment by erinyoung** [comment]
Closes https://github.com/StaPH-B/docker-builds/issues/737 and https://github.com/StaPH-B/docker-builds/issues/715

**Comment by evagunawan** [comment]
Hi Dr. Young! 

I upgraded to dnaapler 2.0 since that was the version defined in the request an update section. 

I just assumed I needed to add both mykrobe and dnaapler in the same request since they are both from the workshop. Sorry about that!

**Comment by erinyoung** [comment]
Generally we have one Dockerfile per PR for reviewer simplicity, but it's not going to break anything.

**Comment by erinyoung** [comment]
I updated the version of dnaapler to 0.4.0 and resolved some merge conflicts. Once the tests complete, I think these files are good to merge into main.

**Review by erinyoung — APPROVED** [review]
Thank you for your contribution!!!

I'm going to 
1. merge this PR
2. push the new mykrobe image to dockerhub and quay using the 0.12.2 tag and overwrite the 'latest' tag
3. push the new dnaapler image to dockerhub and quay using teh 0.4.0 tag and overwrite the 'latest' tag

**Comment by erinyoung** [comment]
Thank you, again, for your contribution!!!

You can check the status of the mykrobe deploy here : https://github.com/StaPH-B/docker-builds/actions/runs/6855078851
You can check the status of the dnaapler deploy here : https://github.com/StaPH-B/docker-builds/actions/runs/6855081475

**Pull request merged**
