### PR TITLE
add quast-5.2.0-slim

### PR DESCRIPTION
**Pull request by Kincekara**
slim version of quast with basic functionality.

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Review by erinyoung — APPROVED** [review]
I have no changes to recommend.

I'm going to
1. merge this PR
2. push this to dockerhub and quay using the tag `5.2.0-slim`

Do you think we should overwrite the `latest` tag?

**Comment by Kincekara** [comment]
I left using the latest tags long ago :) I think it may be better to have full versions in the latest tags. People can get unexpected failures.

**Comment by erinyoung** [comment]
Works for me!

**Comment by erinyoung** [comment]
Thank you for putting this together!

You can check the status of the deploy here : https://github.com/StaPH-B/docker-builds/actions/runs/7745693104

**Pull request merged**
