### PR TITLE
Updating the README and templates

### PR DESCRIPTION
**Pull request by erinyoung**
UPDATE : THIS PR IS READY TO REVIEW!!!

It's always good to go through the documentation of a repo every once and awhile. Most things are not changed, but I do have some suggestions.

### CODE REVIEW

**Comment by kapsakcj** [comment]
OK, I'm happy with the way this PR is at this point, but another set of eyes on the rendered markdown & dockerfile templates would be good.

I made some small edits to your changes for clarity & cleaned up some of the links & markdown formatting. I use VSCode to edit Markdown and now I get all kinds of warnings like how bullet points need to be surrounded above and below by empty lines

I also added a template dockerfile with micromamba as the base image

obviously the github actions has failed and I'm fine to override and merge the PR

**Comment by kapsakcj** [comment]
also forgot to say that the mermaid diagram is awesome, thanks for adding that! Super helpful visual

**Comment by erinyoung** [comment]
This PR is now ready to review!!!

This is going to fail the GA tests because the Dockerfile template isn't functional - so ignore the GA tests.

This PR is to update and double check the documentation of the StaPH-B/docker-builds repo. This is just to ensure the language and examples are in harmony with current recommended practices.

In the dockerfile-template directory there are three dockerfiles to use for examples:
- Dockerfile (which causes GA to crash)
- Dockerfile_builder - which shows adding an additional stage prior to 'app'
- Dockerfile_mamba - which shows using mamba to install something
- README.md - as a template for a tool-specific readme

In the docker directory there are several files that are used to help those creating Dockerfiles. I only have suggested edits for a subset of docs.
 - contribute.md
 - get_containers.md * no edits
 - make_containers.md * no edits
 - run_containers.md
 - useful_links.md * no edits

**Comment by erinyoung** [comment]
I added in a python-centric Dockerfile template for those tools that are installed via pip. 

I am not going to add any additional files to his PR because I would like this PR merged before the docker training in October.

**Review by kapsakcj — APPROVED** [review]
Everything looks good, thanks for adding the additional python dockerfile template!

**Pull request merged**
