### PR TITLE
Erin deploy

### PR DESCRIPTION
**Pull request by erinyoung**
All I did was simplify and reuse some variables

- [X] Update relevant GitHub actions workflow files
- [NA] Any files required for building are located in the same directory as the Dockerfile (i.e. spades/3.12.0/my_spades_tests.sh)
- [X] Have successfully run the workflow "Test <program name> image" in your forked repository

### CODE REVIEW

**Comment by erinyoung** [comment]
I took some initiative from https://github.com/StaPH-B/docker-builds/pull/322/ and @fanninpm and am using variables instead of hard coding some thing.

I want to adjust the deploy script a little bit, but I need to do that when nothing is getting merged so I can test it. 

Basically, I'm unsure of the utility in evaluating secrets during the tool specific deployment when it could probably just be in the main script.

**Comment by erinyoung** [comment]
Also, I made the vibrant directory lowercase

**Comment by kapsakcj** [comment]
I'm done merging stuff for tonight 👍

**Comment by erinyoung** [comment]
Secrets must be defined in the workflow that is being run.

If workflow 1 calls another workflow (workflow 2), the secrets must be defined in workflow 1. 

Good to know. Curiosity resolved.

**Pull request closed without merging**
