### PR TITLE
adding GenoVi version 0.4.3

### PR DESCRIPTION
**Pull request by erinyoung**
I find GenoVi really useful in quickly drawing cool figures of completed circular genomes.

GenoVi is really easy to use, but has circos as a dependency and isn't directly on conda (so it can be tricky to install).

The images it creates look like this:
genovi

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Closes https://github.com/StaPH-B/docker-builds/issues/650

**Comment by Kincekara** [comment]
@erinyoung did you check the size of the image? pip installs nvidia-cuda libraries. I mean this image will be huge. I believe it happens because of the tensorboard requirement of deepnog.  I am curious what happens if we try to remove cuda.

**Review by Kincekara — APPROVED** [review]

**Comment by erinyoung** [comment]
deepnog is definitely required, and it lists tensorboard as a dependency. 

Have you used deepnog without tensorboard?

I'm expecting the built image to be ~4.54GB in size.

**Comment by Kincekara** [comment]
No, I was just curious. I am merging this.

**Comment by Kincekara** [comment]
Thank you for your PR! 
You can follow its deployment progress from here: https://github.com/StaPH-B/docker-builds/actions/runs/6880864829

**Comment by erinyoung** [comment]
Thank you!

**Pull request merged**
