### PR TITLE
Adding MultiQC version 1.17

### PR DESCRIPTION
**Pull request by hutchinsonmiri**
* Updated MultiQC to version 1.17 and added app layer and test layer

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [N/A] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [N/A] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
This looks great!

Do you think it'd be worthwhile to skip 1.17 and go for the latest version (1.18) or would you like to stick with version 1.17?

**Comment by erinyoung** [comment]
The kaiju modules broke? How strange. Everything else looked fine.

```
#16 51.89 |             kaiju | Found 4 reports
#16 51.92 ╭───────────────── Oops! The 'kaiju' MultiQC module broke... ──────────────────╮
#16 51.92 │ Please copy this log and report it at                                        │
#16 51.92 │ https://github.com/ewels/MultiQC/issues                                      │
#16 51.92 │ Please attach a file that triggers the error. The last file found was:       │
#16 51.92 │ ./MultiQC_TestData/data/modules/kaiju/issue_1540/test.txt                    │
#16 51.92 │                                                                              │
#16 51.92 │ Traceback (most recent call last):                                           │
#16 51.92 │   File "/usr/local/lib/python3.10/dist-packages/multiqc/multiqc.py", line 68 │
#16 51.92 │     output = mod()                                                           │
#16 51.92 │   File "/usr/local/lib/python3.10/dist-packages/multiqc/modules/kaiju/kaiju. │
#16 51.92 │     self.kaiju_stats_table()                                                 │
#16 51.92 │   File "/usr/local/lib/python3.10/dist-packages/multiqc/modules/kaiju/kaiju. │
#16 51.92 │     self.kaiju_sample_unclassified[s_name] * 100 / self.kaiju_sample_total_r │
#16 51.92 │ ZeroDivisionError: division by zero                                          │
#16 51.92 │                                                                              │
#16 51.92 ╰──────────────────────────────────────────────────────────────────────────────╯
#16 51.93 |            kraken | Found 1 reports
```

**Comment by hutchinsonmiri** [comment]
Oh, I hadn't realized there was a later version! I am happy to upgrade. Do
you think the kaiju module problem will be an issue?

Thanks!!!

**Comment by erinyoung** [comment]
Do you think that the Kaiju module is fixed for version 1.18?

**Comment by erinyoung** [comment]
My apologies for all the emails from failed tests. I wanted to reduce pandoc's footprint a little, but didn't really put time into testing it until today.

It looks like everything is working now.

I did make a small change of adding in a test for pandoc, just to make sure it was installed correctly.

If this Dockerfile looks good to you, I think I can merge and deploy this image of multiqc.

**Comment by erinyoung** [comment]
Closes https://github.com/StaPH-B/docker-builds/issues/451

**Comment by hutchinsonmiri** [comment]
Sorry for the late reply! Yes, that sounds fine. Thanks for all the your
additional help!!

**Comment by erinyoung** [comment]
Perfect!

I'm going to merge this PR and deploy your image to dockerub and quay.

**Review by erinyoung — APPROVED** [review]

**Comment by hutchinsonmiri** [comment]
Fantastic!!! Thank you!!Sent from my iPhoneOn Dec 8, 2023, at 2:25 PM, Young ***@***.***> wrote:﻿
Merged #801 into master.

**Comment by erinyoung** [comment]
You can check the status of the deploy here : https://github.com/StaPH-B/docker-builds/actions/runs/7146446086

Thank you for working on this. If you see a tool that needs an update or should be included, don't hesitate to put together another PR!

**Pull request merged**
