### PR TITLE
Add additional arguments to GAMBIT dockerfile

### PR DESCRIPTION
**Pull request by jlumpe**
GAMBIT author here. Added some more `ARG` lines to the GAMBIT Dockerfile to make it more configurable, to aid in testing.

### CODE REVIEW

**Comment by jlumpe** [comment]
@kevinlibuit is the one to review this

**Comment by kevinlibuit** [comment]
Taking a look at this now!
- [ ] successful build
- [ ] local tests

**Comment by kevinlibuit** [comment]
Details on review:
<details>
  <summary>Successful build</summary>

```
$ git fetch origin pull/278/head:gambit-args
$ get checkout gambit-args
$ docker build --tag jl/gambit:0.3.0 ~/docker-builds/gambit/0.3.0/
Sending build context to Docker daemon  3.584kB
Step 1/33 : FROM ubuntu:xenial

[...]

Successfully built 28a23da5a963
Successfully tagged jl/gambit:0.3.0
```
</details>

<details>
  <summary>Successful Local Test</summary>
  
```

$ docker run --rm=True -it -v $PWD:/data jl/gambit:0.3.0
$ gambit query ./sample_01.fasta -o sample_01_gambit_out.csv
Classifying  [####################################]  100%
$ cat sample_01_gambit_out.csv
query.name,query.path,predicted.name,predicted.rank,predicted.ncbi_id,predicted.threshold,closest.distance,closest.description
sample_01.fasta,sample_01.fasta,Escherichia coli/Shigella,species,,0.6825377941131592,0.015710022,[GCF_000021125.1] Escherichia coli O157:H7 str. EC4115 (E. coli)

```
</details>

**Comment by kevinlibuit** [comment]
Looks good, @jlumpe! Though I only built and tested using the default args. What other Python versions are compatible?

**Review by kevinlibuit — APPROVED** [review]

**Pull request merged**
