### PR TITLE
Added latest version of dragonflye and updated main README

### PR DESCRIPTION
**Pull request by JLB423**
Pull Request (PR) checklist:
- [X ] Include a description of what is in this pull request in this message.
- [ X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [ X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [ X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X ] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [ X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [ X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

---
#### Requested Updates : 
Added  dragonflye/1.1.1; dockerfile and readme file for latest version of dragonflye
Updated the main README file to include the addition of dragonflye version 1.1.1

### CODE REVIEW

**Comment by kapsakcj** [comment]
Hi Jessie, thanks for the PR!

I will soon do a more in depth review but for now I just wanted to resolve the merge conflict with the main `/README.md` and get the github actions workflow going to test the docker image build.

You can view the logs here if interested: https://github.com/StaPH-B/docker-builds/actions/runs/5280346435/jobs/9552338390

P.S. I added a relative link in the `/README.md` which brings users directly to `dragonflye/1.1.1/` so they can easily find the tool-specific documentation

**Comment by kapsakcj** [comment]
Hi Jessie, here are my suggested changes for this pull request. Please add additional commits to your pull request with these changes. You can check these boxes below once completed to help keep track.

- [ ] (optional) Please add yourself to the list of authors/maintainers in the main `/README.md`. Only add if you are comfortable, it's not required, just want to give you credit for contributing!
- [ ] Please upgrade the base image on line 1 of the dockerfile to use `mambaorg/micromamba:1.4.4`. I think it's a good idea to use a recent release of `micromamba` and the base docker image
  - [ ] update LABEL on line 12 to reflect this new base image
- [ ] (optional) Add these lines below line 21 if you'd like to be listed as a maintainer. Totally fine if not, I'm happy to be listed as the maintainer.
```Dockerfile
LABEL maintainer2="Jessie Bologna"
LABEL maintainer2.email="your.email@email.com"
```

- [ ] I think `git` is unnecessary in this docker image. I don't see it used directly in the Dockerfile, but might be needed elsewhere(?). Can you try removing that from the `apt-get install` step? Essentially delete line 27 from the dockerfile

Please let me know if you have any questions!

**Comment by erinyoung** [comment]
Hi @JLB423 ! 

I hope everything is going well. Have you had a chance to look at the suggested changes?

**Comment by erinyoung** [comment]
@kapsakcj and @JLB423 , my apologies, but I'd like to use this version of dragonflye. 

I took the liberty to edit the Dockerfile with the recommended edits plus more including:
1. adding a CMD layer
2. updating the base image version
3. added myself as maintainer

**Comment by kapsakcj** [comment]
Thanks, Erin. I'll reach out to Jessie via email and give her a heads up

**Comment by kapsakcj** [comment]
@erinyoung Could you please adjust the CMD block on line 44 to use the bracket notation? That is the preferred syntax: https://docs.docker.com/engine/reference/builder/#cmd

**Comment by kapsakcj** [comment]
Everything else looks good, once that CMD line is changed and the tests pass, I can merge and deploy the docker image

**Comment by erinyoung** [comment]
@kapsakcj ,

The link your provided gives this information:

> CMD
> The CMD instruction has three forms:
> 
> CMD ["executable","param1","param2"] (exec form, this is the preferred form)
> CMD ["param1","param2"] (as default parameters to ENTRYPOINT)
> CMD command param1 param2 (shell form)

I just used shell form. There isn't any information for which exec form is preferred above shell form.

**Review by kapsakcj — APPROVED** [review]

**Comment by kapsakcj** [comment]
Deploy workflow here: https://github.com/StaPH-B/docker-builds/actions/runs/5764706050

the docker image should be available shortly on dockerhub and quay under the name `staphb/dragonflye:1.1.1` and `staphb/dragonflye:latest` (as well as the quay.io copies)

Thanks for the PR and thank you @erinyoung for pushing it over the finish line 👍 

I hope you enjoyed the Docker training! Really appreciate your participation @JLB423 🎉

**Pull request merged**
