### PR TITLE
add polkapox graph reconstruction container

### PR DESCRIPTION
**Pull request by jessicarowell**
Pull Request (PR) checklist:
- [x ] Include a description of what is in this pull request in this message.
- [x ] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x ] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x ] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [ x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by jessicarowell** [comment]
I replaced the old PR because it was getting too complicated. I deleted my fork, re-forked, added only polkapox, and ran the test again.  What's here is everything that had already been approved for the polkapox graph reconstruction container. Once this is merged, I will add tostadas update and submit another PR for that.

**Comment by erinyoung** [comment]
Actually, I found the line from your prior PR and added that... so... nevermind!

Once the tests pass (which should be soon), I'll merge this PR and deploy it.

**Review by erinyoung — APPROVED** [review]

**Comment by erinyoung** [comment]
Hmm... it's looking like something is happening, and the test isn't working

```
#19 [test 8/8] RUN bash my_tests.sh
#19 0.052 /test
#19 0.053 /test/LIY15561A68_2022_1748_IN.assembly.gfa.gz
#19 0.053 /test/LIY15561A68_2022_1748_IN.assembly.log
#19 0.053 /test/LIY15561A68_2022_1748_IN.assembly_longest.fasta
#19 0.053 /test/mpxv-AssemblyGraph_gfaPy.py
#19 0.053 /test/my_tests.sh
#19 0.054 gzip: LIY15561A65_2022_1744_NE.assembly.gfa.gz: No such file or directory
#19 0.056 cat: LIY15561A65_2022_1744_NE.assembly.gfa: No such file or directory
#19 DONE 0.6s
```

**Comment by jessicarowell** [comment]
should be fixed now

**Comment by erinyoung** [comment]
@jessicarowell , could you look at the changes that I made to your test? Your original test was referencing a file that didn't exist 

If this is acceptable, I'd like to remove LIY15561A68_2022_1748_IN.assembly.gfa.gz, LIY15561A68_2022_1748_IN.assembly.log, LIY15561A68_2022_1748_IN.assembly_longest.fasta, and my_tests.sh from your PR.

**Comment by jessicarowell** [comment]
I just updated my_tests.sh to correct the file name and add the necessary file.
All of these files are there because we wanted to include test data in this docker image...

**Comment by erinyoung** [comment]
Do you have time to meet with me for a moment?

**Comment by erinyoung** [comment]
@jessicarowell , if this Dockerfile is alright with you, I'll merge this PR and deploy the image.

**Comment by erinyoung** [comment]
Thank you for your hard work!

Here's the status of the deploy: https://github.com/StaPH-B/docker-builds/actions/runs/8456651866

It should be up on dockerhub and quay within minutes.

Let me know if you run into any issues!

**Pull request merged**
