### PR TITLE
Trycycler version 0.5.3

### PR DESCRIPTION
**Pull request by erinyoung**
This is for the latest version of trycycler. I've been using the biocontainers one, and decided to make a staphb one.

I updated the Dockerfile from 0.5.0 doing the following
- updated the version of Trycycler to 0.5.0
- updated the version of Minimap2 to 2.24
- added no-install-recommends to apt-get
  - added corresponding libz-dev, procps, and ca-certificates to apt-get layer
- add test layer using pytest to test trycycler

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
This should close https://github.com/StaPH-B/docker-builds/issues/521 and https://github.com/StaPH-B/docker-builds/issues/266

**Comment by erinyoung** [comment]
And something happened with the R packages installs. Just a sec.

**Comment by erinyoung** [comment]
Sorry about the R package debacle. Everything should work now and this is ready for review.

**Comment by kapsakcj** [comment]
I tested with the "Great Dataset" & example commands from here: https://github.com/rrwick/Trycycler/wiki/Great-dataset-analysis

Everything ran as expected ✔️ 

Would be nice to eventually incorporate this into the test stage of the dockerfile, pending that it may doesn't take too long to run. I don't have exact numbers but it might take 10+ min for all `trycycler` commands to run to completion. Test data files & output files aren't too huge, all less than 1GB disk consumed

I think the test stage is fine with the unit tests, no need to update. Those tests help ensure functionality without the long(er) run time & not-tiny test dataset

**Comment by kapsakcj** [comment]
Made a few changes to the trycycler README.md

I'm good to merge if you are! Just let me know how you would like to proceed and I can complete the process

**Review by kapsakcj — APPROVED** [review]

**Review by erinyoung — COMMENTED** [review]
Those changes look good to me! Thank you for the improvements!

**Comment by erinyoung** [comment]
I'm going to deploy this to dockerhub and quay and overwrite the 'latest' tag.

**Pull request merged**
