### PR TITLE
Cjk pangolin update

### PR DESCRIPTION
**Pull request by kapsakcj**
- [x] This comment contains a description of what is in the pull request.

Updates the Pangolin 3.1.20 dockerfile to a new release of pangolearn 2022-02-28 and new release of pango-designation 1.2.132. 

This PR also contains commits from Kevin's last PR #306 which has already been merged into the `master` branch. No need to review & test these (already completed).

I must have forgotten to `git pull` before editing the pangolin dockerfile

- [x] Build your own docker image using a Dockerfile
  - [x] Includes the recommended LABELS
- [x] (Optional) Dockerfile is built with best practices and has been approved by a linter (such as https://hadolint.github.io/hadolint/)
- [x] Ensure tool is listed in Program_Licenses.md
- [x] Ensure a simple container-specific README.md exists in the same directory as the Dockerfile (i.e. spades/3.12.0/README.md)
- [x] Update GitHub actions workflow if needed
- [x] Any files required for building are located in the same directory as the Dockerfile (i.e. spades/3.12.0/my_spades_tests.sh)
- [ ] Have successfully run the workflow "Test <program name> image" in your forked repository

### CODE REVIEW

**Comment by fanninpm** [comment]
> This PR also contains commits from Kevin's last PR #306 which has already been merged into the `master` branch. No need to review & test these (already completed).
> 
> I must have forgotten to `git pull` before editing the pangolin dockerfile

I think all you would need to do is rebase your branch on an up-to-date master branch (`git rebase -i master`), followed by `git push --force`.

**Comment by kapsakcj** [comment]
Spot on with the instructions @fanninpm . thank you for your help!

Looks like the only files now changed w/ this PR are the appropriate ones 👍

**Comment by fanninpm** [comment]
> EDIT: maybe I spoke too soon. Looks like this would actually delete `/gambit/0.4.0/dockerfile` grimacing . Darn

Did you make sure to `git checkout master && git pull upstream master`?

**Comment by kapsakcj** [comment]
Just going to do a table flip and start from the beginning. It's only 2 lines of code difference.

Appreciate the help @fanninpm

**Pull request closed without merging**
