### PR TITLE
Add latest version of BBTools (v38.95)

### PR DESCRIPTION
**Pull request by fanninpm**
- [x] This comment contains a description of what is in the pull request.

Version bump of BBTools. The Dockerfile here is almost identical to the one submitted in #262.

- [x] Build your own docker image using a Dockerfile
  - [x] Directory structure should be name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. spades/3.12.0/Dockerfile)
  - [x] Includes the recommended LABELS
- [x] (Optional) Dockerfile is built with best practices and has been approved by a linter (such as https://hadolint.github.io/hadolint/)
- [x] Edit main README.md
- [x] Ensure tool is listed in Program_Licenses.md
- [ ] Create a simple container-specific README.md in the same directory as the Dockerfile (i.e. spades/3.12.0/README.md)
- [ ] Update GitHub actions workflow if needed
- [ ] Any files required for building are located in the same directory as the Dockerfile (i.e. spades/3.12.0/my_spades_tests.sh)
- [ ] Have successfully run the workflow "Test <program name> image" in your forked repository

### CODE REVIEW

**Comment by kapsakcj** [comment]
Hi Padraic, thanks for the PR.

Taking a look and testing now.

**Comment by kapsakcj** [comment]
Docker image builds successfully ✔️ 
```
$ docker build -t fanninpm/bbtools:38.95 bbtools/38.95/
Sending build context to Docker daemon  3.072kB
Step 1/19 : FROM ubuntu:xenial
 ---> 065cf14a189c

[...]

Step 19/19 : WORKDIR /data
 ---> Running in 00c69d5f81d0
Removing intermediate container 00c69d5f81d0
 ---> e4a91734b88b
Successfully built e4a91734b88b
Successfully tagged fanninpm/bbtools:38.95

real    1m56.384s
user    0m0.267s
sys     0m0.263s
```

help options show up for `bbduk.sh` ✔️ (and other bbtools executables)
```
$ bbduk.sh --help

Written by Brian Bushnell
Last modified January 26, 2021

Description:  Compares reads to the kmers in a reference dataset, optionally
allowing an edit distance. Splits the reads into two outputs - those that
match the reference, and those that don't. Can also trim (remove) the matching
parts of the reads rather than binning the reads.
Please read bbmap/docs/guides/BBDukGuide.txt for more information.

Usage:  bbduk.sh in=<input file> out=<output file> ref=<contaminant files>

[...]
```

And it runs successfully on a pair of ILMN reads I had handy:
```
$ repair.sh in1=testdata/sarscov2/ilmn-reads-VBL-omicron/3000299930_S377_L001_R1_001.fastq.gz in2=testdata/sarscov2/ilmn-reads-VBL-omicron/3000299930_S377_L001_R2_001.fastq.gz out1=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_1.fastq.gz out2=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_2.fastq.gz
java -ea -Xmx11482m -cp /bbmap/current/ jgi.SplitPairsAndSingles rp in1=testdata/sarscov2/ilmn-reads-VBL-omicron/3000299930_S377_L001_R1_001.fastq.gz in2=testdata/sarscov2/ilmn-reads-VBL-omicron/3000299930_S377_L001_R2_001.fastq.gz out1=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_1.fastq.gz out2=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_2.fastq.gz
Executing jgi.SplitPairsAndSingles [rp, in1=testdata/sarscov2/ilmn-reads-VBL-omicron/3000299930_S377_L001_R1_001.fastq.gz, in2=testdata/sarscov2/ilmn-reads-VBL-omicron/3000299930_S377_L001_R2_001.fastq.gz, out1=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_1.fastq.gz, out2=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_2.fastq.gz]

Set INTERLEAVED to false
Started output stream.

Input:                          1628628 reads           82341956 bases.
Result:                         1628628 reads (100.00%)         82341956 bases (100.00%)
Pairs:                          1628628 reads (100.00%)         82341956 bases (100.00%)
Singletons:                     0 reads (0.00%)         0 bases (0.00%)

Time:                           3.316 seconds.
Reads Processed:       1628k    491.14k reads/sec
Bases Processed:      82341k    24.83m bases/sec

```
followed by `bbduk.sh`
```
$ bbduk.sh in1=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_1.fastq.gz in2=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_2.fastq.gz out1=outputs/2022-02-08-bbtools-docker-testing/3000299930.rmadpt_1.fastq.gz out2=outputs/2022-02-08-bbtools-docker-testing/3000299930.rmadpt_2.fastq.gz ref=/bbmap/resources/adapters.fa stats=outputs/2022-02-08-bbtools-docker-testing/3000299930.adapters.stats.txt ktrim=r k=23 mink=11 hdist=1 tpe tbo
java -ea -Xmx5741m -Xms5741m -cp /bbmap/current/ jgi.BBDuk in1=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_1.fastq.gz in2=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_2.fastq.gz out1=outputs/2022-02-08-bbtools-docker-testing/3000299930.rmadpt_1.fastq.gz out2=outputs/2022-02-08-bbtools-docker-testing/3000299930.rmadpt_2.fastq.gz ref=/bbmap/resources/adapters.fa stats=outputs/2022-02-08-bbtools-docker-testing/3000299930.adapters.stats.txt ktrim=r k=23 mink=11 hdist=1 tpe tbo
Executing jgi.BBDuk [in1=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_1.fastq.gz, in2=outputs/2022-02-08-bbtools-docker-testing/3000299930.paired_2.fastq.gz, out1=outputs/2022-02-08-bbtools-docker-testing/3000299930.rmadpt_1.fastq.gz, out2=outputs/2022-02-08-bbtools-docker-testing/3000299930.rmadpt_2.fastq.gz, ref=/bbmap/resources/adapters.fa, stats=outputs/2022-02-08-bbtools-docker-testing/3000299930.adapters.stats.txt, ktrim=r, k=23, mink=11, hdist=1, tpe, tbo]
Version 38.95

maskMiddle was disabled because useShortKmers=true
0.021 seconds.
Initial:
Memory: max=5770m, total=5770m, free=5649m, used=121m

Added 217135 kmers; time:       0.089 seconds.
Memory: max=5770m, total=5770m, free=5439m, used=331m

Input is being processed as paired
Started output streams: 0.082 seconds.
Processing time:                3.570 seconds.

Input:                          1628628 reads           82341956 bases.
KTrimmed:                       19913 reads (1.22%)     266206 bases (0.32%)
Trimmed by overlap:             27274 reads (1.67%)     140969 bases (0.17%)
Total Removed:                  322 reads (0.02%)       407175 bases (0.49%)
Result:                         1628306 reads (99.98%)  81934781 bases (99.51%)

Time:                           3.751 seconds.
Reads Processed:       1628k    434.15k reads/sec
Bases Processed:      82341k    21.95m bases/sec
```

**Comment by kapsakcj** [comment]
I'll build the images on dockerhub and quay. Thank you!

**Comment by kapsakcj** [comment]
Alrighty, the new image is available. https://hub.docker.com/r/staphb/bbtools/tags

and https://quay.io/repository/staphb/bbtools?tab=tags

**Comment by fanninpm** [comment]
Thanks!

**Pull request merged**
