### PR TITLE
Circlator version 1.5.5

### PR DESCRIPTION
**Pull request by erinyoung**
I KNOW the prior version was 1.5.6. Abigail wasn't wrong. I don't know why they started using 1.5.5. 

I also know this has the wrong version of spades, but I couldn't get spades version 3.7.1 to download and install.

Also, will not work with Canu 2.2.

I initially tried to download this from source, but came across enough pip errors to decide to install with pip.

This should address https://github.com/StaPH-B/docker-builds/issues/601

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
All the code changes look good and the tests pass. I wanted to check before merging - if you build this image locally, does it resolve the error you described in issue #601 ?

Want to make sure the bug has been squashed before we merge

**Comment by erinyoung** [comment]
I think so. As I was waiting for this one to get approved, I built the image and put it for UPHL's repo on quay (without the test layer). https://quay.io/repository/uphl/circlator

This hasn't triggered an error for me (yet)

**Review by kapsakcj — APPROVED** [review]
OK, sounds like the issue has been resolved, but we can revisit if you hit the error again in the future. going to merge and deploy this docker image

**Comment by kapsakcj** [comment]
Deploy workflow is here: https://github.com/StaPH-B/docker-builds/actions/runs/4457068667

I'll let you delete your dev branch if you're done with it

I just used the version for the docker image tag, so it will shortly be available under `staphb/circlator:1.5.5` & `staphb/circlator:latest` and the same tags on quay

**Pull request merged**
