### PR TITLE
update multiple GHActions workflows & new mlst update

### PR DESCRIPTION
**Pull request by kapsakcj**
Lots of versions upgraded across the GitHub Actions workflows. Mostly done to suppress the node.js warnings, but I assumethat later versions are better/improved.

~~Might have to edit a dockerfile in order to trigger the updated workflows....just starting a draft PR for now, and then I can test later when adding a new dockerfile~~

I added a new dockerfile for `mlst` that tests to ensure the databases were updated.

This E. coli genome [GCA_032604515.1](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_032604515.1/) is used as a test because we expect the result to be ST15199 which was designated on 2023-10-16 according to: https://pubmlst.org/bigsdb?page=profileInfo&db=pubmlst_escherichia_seqdef&scheme_id=1&profile_id=15199

Thank you @Kincekara for providing this genome! Thank you to you & your team at CT PHL!

I propose that we call this docker image `staphb/mlst:2.23.0-2024-03`. @erinyoung Let me know if you have a better idea for a docker image tag that will work well with the upcoming GHActions workflow & it's resulting docker image tags

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
The only remaining action to be upgraded is `Ana06/get-changed-files@v2.2.0` which needs to be done by the maintainer before we can upgrade the version used in our workflows. So there will be one warning present until that is completed

**Comment by kapsakcj** [comment]
Here are the differences from the previous dockerfile that I used as a starting point:

- deleted `COPY` line as it's unnecessary
- added LABELs with my contact info
- added a few `-v` flags to `rm` and `mkdir` commands
- added `datasets` to the test stage
- added test for E. coli with ST15199 as well as links to genome & pubMLST page showing when that ST was assigned/designated.

```
$ diff mlst/2.23.0-2024-01/Dockerfile mlst/2.23.0-2024-03/Dockerfile 
15,17c15,16
< 
< # copy README for posterity
< COPY README.md .
---
> LABEL maintainer2="Curtis Kapsak"
> LABEL maintainer2.email="kapsakcj@gmail.com"
47c46
<  rm v${MLST_VER}.tar.gz
---
>  rm -v v${MLST_VER}.tar.gz
59c58
<  mkdir db-downloaded-$(date -I) && \
---
>  mkdir -v db-downloaded-$(date -I) && \
70a70,71
> ### start of test stage ###
> # using app stage as base image for test stage
76a78,104
> 
> # need unzip for the datasets tool
> RUN apt-get update && apt-get install -y --no-install-recommends unzip
> 
> # for pinning the version of NCBI datasets that is downloaded for this test
> ARG DATASETS_VER="16.2.0"
> 
> # install ncbi datasets tool (pre-compiled binary)
> RUN wget https://github.com/ncbi/datasets/releases/download/v${DATASETS_VER}/linux-amd64.cli.package.zip && \
>   unzip linux-amd64.cli.package.zip && \
>   rm linux-amd64.cli.package.zip && \
>   chmod +x dataformat datasets
> 
> # downloading an E. coli (from CT) with a known newer sequence type ST15199 which was designated on 2023-10-16
> # MLST scheme info here (from Enterobase): https://pubmlst.org/bigsdb?page=profileInfo&db=pubmlst_escherichia_seqdef&scheme_id=1&profile_id=15199
> # E. coli genome: https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_032604515.1/
> # BioSample: SAMN37796909
> ARG GENBANK_ACCESSION="GCA_032604515.1"
> RUN datasets download genome accession ${GENBANK_ACCESSION} --filename ${GENBANK_ACCESSION}.zip && \
>     mkdir -v ${GENBANK_ACCESSION}-download && \
>     unzip ${GENBANK_ACCESSION}.zip -d ${GENBANK_ACCESSION}-download && \
>     rm -v ${GENBANK_ACCESSION}.zip && \
>     mv -v ${GENBANK_ACCESSION}-download/ncbi_dataset/data/${GENBANK_ACCESSION}/${GENBANK_ACCESSION}*.fna ${GENBANK_ACCESSION}-download/ncbi_dataset/data/${GENBANK_ACCESSION}/${GENBANK_ACCESSION}.genomic.fna && \
>     mlst ${GENBANK_ACCESSION}-download/ncbi_dataset/data/${GENBANK_ACCESSION}/${GENBANK_ACCESSION}.genomic.fna | tee mlst.${GENBANK_ACCESSION}.tsv && \
>     echo && \
>     echo "Checking for ST15199 in the mlst results now..." && \
>     grep "15199" mlst.${GENBANK_ACCESSION}.tsv
```

**Review by Kincekara — APPROVED** [review]
Everything seems good. I am merging this.. 🤞

**Comment by Kincekara** [comment]
Thank you for putting all this together @kapsakcj.
You can check the mlst image from here: https://github.com/StaPH-B/docker-builds/actions/runs/8208199568.

**Pull request merged**
