### PR TITLE
Update pangolin to pangolin-data 1.21 and constellations 0.1.11

### PR DESCRIPTION
**Pull request by kapsakcj**
Changes from previous dockerfile:

- upgraded to pangolin-data v1.21
- upgraded to constellations v0.1.11
- upgraded base image to `mambaorg/micromamba:1.4.4` from 1.4.3
- added test for another XBB.1.16 genome to test new `constellations`/`scorpio` functionality

Other:

- updated main `/README.md` so that the list of versions for pangolin is shorter

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
Need to update constellations again, please don't review yet

**Comment by kapsakcj** [comment]
OK, upgraded to constellations 0.1.12. Was patched for a simple version mismatch: https://github.com/cov-lineages/constellations/compare/v0.1.11...v0.1.12

ready for review 👍

**Comment by erinyoung** [comment]
My apologies for the delay. I have no suggestions. 

I am going to merge this PR, but I'll let you deploy to dockerhub and quay.

**Review by erinyoung — APPROVED** [review]

**Comment by kapsakcj** [comment]
TY! deploy workflow here: https://github.com/StaPH-B/docker-builds/actions/runs/5414940450

I used the image tag of `4.3-pdata-1.21`

**Pull request merged**
