### PR TITLE
adds bbtools 39.10

### PR DESCRIPTION
**Pull request by Kincekara**
I have updated samtools and htslib along with the BBTools. I removed the loop from CMD since it had created a novel from help. Now, it shows a table of tools. 

I also renewed the legacy readme.

```
$ diff bbtools/39.06/Dockerfile bbtools/39.10/Dockerfile 
1,2c1,2
< FROM staphb/samtools:1.19 as samtools
< FROM staphb/htslib:1.19 as htslib
---
> FROM staphb/samtools:1.21 as samtools
> FROM staphb/htslib:1.21 as htslib
11c11
< ARG BBTOOLSVER=39.06
---
> ARG BBTOOLSVER=39.10
58c58
< CMD for tool in $(ls /bbmap/*sh | cut -f 3 -d "/") ; do $tool -h ; done
---
> CMD tail -n 90 /bbmap/docs/TableOfContents.txt
65,66c65,66
< # testing that '-h' works for all tools
< RUN for tool in $(ls /bbmap/*sh | cut -f 3 -d "/") ; do $tool -h ; done
---
> # testing all tools
> RUN for tool in $(ls /bbmap/*sh | cut -f 3 -d "/") ; do $tool; done
```

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Review by erinyoung — APPROVED** [review]
I have no changes to recommend. Thank you for putting this together!

I'm going to deploy this to dockerhub and quay for the 'staphb/bbtools' image with the tag '39.10' and I'll overwrite the 'latest' tag.

**Comment by erinyoung** [comment]
Actually, do we think this message matters?

```
#18 0.564 java -ea -Xmx16000m -Xms16000m -cp /bbmap/current/ align2.BBMap minratio=0.75 maxindel=8 bwr=0.22 bw=26 minhits=1 path=/global/cfs/cdirs/bbtools/hg19 build=2 pigz unpigz zl=6 qtrim=r trimq=10 untrim idtag usemodulo printunmappedcount ztd=2 maxsites=1 k=14 tipsearch=0 kfilter=25 bloomfilter
#18 0.663 Executing align2.BBMap [minratio=0.75, maxindel=8, bwr=0.22, bw=26, minhits=1, path=/global/cfs/cdirs/bbtools/hg19, build=2, pigz, unpigz, zl=6, qtrim=r, trimq=10, untrim, idtag, usemodulo, printunmappedcount, ztd=2, maxsites=1, k=14, tipsearch=0, kfilter=25, bloomfilter]
#18 0.663 Version 39.10
#18 0.663 
#18 0.677 Set MINIMUM_ALIGNMENT_SCORE_RATIO to 0.750
#18 0.699 No output file.
#18 0.701 java.lang.RuntimeException: Can't find file /global/cfs/cdirs/bbtools/hg19/ref/genome/2/summary.txt
#18 0.701 	at fileIO.ReadWrite.getRawInputStream(ReadWrite.java:937)
#18 0.701 	at fileIO.ReadWrite.getInputStream(ReadWrite.java:900)
#18 0.702 	at fileIO.TextFile.open(TextFile.java:280)
#18 0.702 	at fileIO.TextFile.<init>(TextFile.java:123)
#18 0.702 	at dna.Data.setGenome2(Data.java:823)
#18 0.702 	at dna.Data.setGenome(Data.java:769)
#18 0.702 	at align2.BBMap.loadIndex(BBMap.java:318)
#18 0.702 	at align2.BBMap.main(BBMap.java:32)
```

**Comment by erinyoung** [comment]
This test passed:
```
#19 [test 2/2] RUN wget -q https://raw.githubusercontent.com/StaPH-B/docker-builds/master/tests/SARS-CoV-2/SRR13957123.primertrim.sorted.bam &&     streamsam.sh in='SRR13957123.primertrim.sorted.bam' out='test_SRR13957123.primertrim.sorted.fastq.gz' &&     test -f test_SRR13957123.primertrim.sorted.fastq.gz
#19 0.478 java -ea -Xmx1g -cp /bbmap/current/ stream.SamStreamerWrapper in=SRR13957123.primertrim.sorted.bam out=test_SRR13957123.primertrim.sorted.fastq.gz
#19 0.555 Executing stream.SamStreamerWrapper [in=SRR13957123.primertrim.sorted.bam, out=test_SRR13957123.primertrim.sorted.fastq.gz]
#19 0.555 
#19 0.625 Found sambamba.
#19 1.237 Time:                         	0.708 seconds.
#19 1.237 Reads Processed:    153310 	216.51k reads/sec
#19 1.237 Bases Processed:    21265977 	30.03 Mbp/sec
#19 1.238 Reads Out:          153310
#19 1.238 Bases Out:          21265977
#19 DONE 1.3s
```

**Comment by Kincekara** [comment]
I couldn't reproduce the error. I also realized there are 218 scripts and we don't see most of the output. That loop in the test is not very useful so I removed it completely.

**Comment by erinyoung** [comment]
Thank you for putting this together!

You can check the status of the deployment here : https://github.com/StaPH-B/docker-builds/actions/runs/11184915234

**Comment by erinyoung** [comment]
Looks like the deployment didn't work, so I've re-launched it : https://github.com/StaPH-B/docker-builds/actions/runs/11184915234

**Comment by Kincekara** [comment]
fixed #1085

**Pull request merged**
