### PR TITLE
adding pilon 1.24

### PR DESCRIPTION
**Pull request by erinyoung**
Updates pilon to version 1.24

Basically the same dockerfile as 1.23.0, but now
- uses jammy
- adds a test which uses a bam file from this repo, indexes it with samtools, and then runs that through pilon
- now has a readme

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Should close https://github.com/StaPH-B/docker-builds/issues/300

**Comment by kapsakcj** [comment]
made a slight change in an effort to save space in the pilon docker image - rename the pilon jarfile instead of copying it, which saves 11MB

Looks like test pass and everything else looks good. I'll go ahead and merge & deploy the new docker image

**Review by kapsakcj — APPROVED** [review]

**Comment by kapsakcj** [comment]
I'll let you delete the dev branch if you're done with it

deploy workflow kicked off here: https://github.com/StaPH-B/docker-builds/actions/runs/4361584686

docker image name & tag will be `staphb/pilon:1.24` as well as `:latest` & the quay permutations of each

**Comment by tbazilegith** [comment]
Hi Erin,
Thanks for the answer. 
I am using nextflow, I pulled the container in my config. I can only see the image in 
work/singularity/staphb-pilon-1.24.img

In my process, I have 
        """
         java -jar -Xmx16G /pilon/pilon-1.24.jar
        pilon -Xmx16G --genome ${can_asb} --bam ${alnbam} --outdir ${sample_id}
      """
But the process failed, saying 
Error: Unable to access jarfile /pilon/pilon-1.24.jar

Where does this " /pilon/pilon.jar " after pulling the container?
Thanks!

**Comment by tbazilegith** [comment]
Think I got it.  
java -jar -Xmx16G /pilon/pilon.jar --genome ${can_asb} --bam ${alnbam} --outdir ${sample_id}
Thanks!

**Pull request merged**
