### PR TITLE
Adding Dr. PRG

### PR DESCRIPTION
**Pull request by erinyoung**
This is for [Dr. PRG](https://github.com/mbhall88/drprg/issues/32), another tool for assessing antimicrobial resistance in TB. This is currently set as a draft so that I remember to finish this. It's missing a README plus other features.

EDIT : This PR is now ready for review!

This Dockerfile has three stages and a cheat from the bcftools image hosted by StaPH-B. Dr. PRG and its dependencies are downloaded as binaries in builder, staphb/bcftools is used in builder2, and the relevant executables from builder and builder2 are copied into the 'app' stage. Mafft is then installed in the 'app' stage. 

In the test stage, I opted to download some fastq files from the ENA. I think Dr. PRG comes with tests, but I ran out of time looking how to implement them. 

My current test is known to not run successfully. This is the error:
```
> [test 4/4] RUN wget -q ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR230/005/SRR23086705/SRR23086705_1.fastq.gz &&     wget -q ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR230/005/SRR23086705/SRR23086705_2.fastq.gz &&     cat SRR23086705_1.fastq.gz SRR23086705_2.fastq.gz > test.fastq.gz &&     drprg predict -x mtb -i test.fastq.gz --illumina -o outdir/ &&     ls outdir/*:
250.9 [2023-10-26T22:27:08Z INFO ] Outdir doesn't exist...creating...
250.9 [2023-10-26T22:27:08Z INFO ] Discovering variants...
299.3 Error: Failed to update discover PRG
299.3 
299.3 Caused by:
299.3     Missing expected output file /test/outdir/discover/denovo_sequences.fa
```

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [ ] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [ ] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [ ] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [ ] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Closes https://github.com/StaPH-B/docker-builds/issues/762

**Comment by Kincekara** [comment]
@erinyoung, why don't you start with staphb/bcftools:1.18 as "builder" and build other tools in it? Its base is jammy, too. This way, you will have fewer layers.

**Comment by erinyoung** [comment]
Why? Legacy reasons. The first "builder" was originally built on a rust base. Generally I get things working, and then I clean them up. This one isn't working.

I just tried building from the bcftools image as the first base, and it still doesn't work. Doesn't seem to add any extra errors, though.

**Comment by erinyoung** [comment]
This PR is now ready to review.

Turns out Dr. PRG has dependencies that aren't listed. The first hidden missing dependency that I found was for htslib. I added in htslib, but continued to run into issues. My error message was still the same, however, so it was not clear as to what was missing. I have given up building a smaller image and I am using a conda install instead.

I also tried creating the image from the Dockerfile in the [Dr. PRG repo](https://github.com/mbhall88/drprg/blob/main/Dockerfile). I had to make a small change by replacing COPY with RUN wget, but that Dockerfile did not build successfully either.

This was the modified Dockerfile
```
FROM rust:1.65 AS builder

# COPY . /drprg
RUN wget https://github.com/mbhall88/drprg/archive/refs/tags/0.1.1.tar.gz && \
    tar -xvf 0.1.1.tar.gz && \
    mv /drprg-0.1.1 /drprg

ARG JUST_URL="https://just.systems/install.sh"
ARG V_JUST="1.2.0"
ARG MAFFT_URL="https://mafft.cbrc.jp/alignment/software/mafft_7.505-1_amd64.deb"
ARG DEB="/mafft.deb"

RUN apt update \
    && apt install -y cmake \
    && cargo install --locked --path /drprg --root /usr \
    && (wget -O - "$JUST_URL" | bash -s -- --to /usr/bin --tag "$V_JUST") \
    && just -f /drprg/justfile EXTDIR=/usr/bin pandora \
    && just -f /drprg/justfile EXTDIR=/usr/bin bcftools \
    && just -f /drprg/justfile EXTDIR=/usr/bin makeprg \
    && wget -O "$DEB" "$MAFFT_URL" \
    && dpkg -i "$DEB" \
    && apt remove -y cmake \
    && rm -rf /drprg "$DEB" /var/lib/apt/lists/*

RUN drprg --help && pandora --help && make_prg --help && mafft --version && bcftools --version

# These two are required for the paper pipeline
RUN cargo install --root /usr --version 0.7.0 rasusa && rasusa --version

ARG SEQFU_URL="https://github.com/telatin/seqfu2/releases/download/v1.16.0/SeqFu-v1.16.0-Linux-x86_64.zip"
RUN wget -qO /seqfu.zip $SEQFU_URL && unzip -d /usr/bin /seqfu.zip && rm /seqfu.zip && seqfu version
```

This was the error when I tried to build from that Dockerfile
```
=> [2/6] RUN wget https://github.com/mbhall88/drprg/archive/refs/tags/0.1.1.tar.gz &&     tar -xvf 0.1.1.tar.gz &&     mv /drprg-0.1.1 /drprg                     2.9s
 => ERROR [3/6] RUN apt update     && apt install -y cmake     && cargo install --locked --path /drprg --root /usr     && (wget -O - "https://just.systems/inst  388.0s
------
 > [3/6] RUN apt update     && apt install -y cmake     && cargo install --locked --path /drprg --root /usr     && (wget -O - "https://just.systems/install.sh" | bash -s -- --to /usr/bin --tag "1.2.0")     && just -f /drprg/justfile EXTDIR=/usr/bin pandora     && just -f /drprg/justfile EXTDIR=/usr/bin bcftools     && just -f /drprg/justfile EXTDIR=/usr/bin makeprg     && wget -O "/mafft.deb" "https://mafft.cbrc.jp/alignment/software/mafft_7.505-1_amd64.deb"     && dpkg -i "/mafft.deb"     && apt remove -y cmake     && rm -rf /drprg "/mafft.deb" /var/lib/apt/lists/*:
1.574 
1.574 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
1.574 
1.979 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
2.077 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
2.114 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
2.187 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8062 kB]
2.420 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [258 kB]
2.424 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [17.7 kB]
3.371 Fetched 8546 kB in 2s (4795 kB/s)
3.371 Reading package lists...
3.783 Building dependency tree...
3.885 Reading state information...
3.895 91 packages can be upgraded. Run 'apt list --upgradable' to see them.
3.900 
3.900 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
3.900 
3.908 Reading package lists...
4.344 Building dependency tree...
4.475 Reading state information...
4.578 The following additional packages will be installed:
4.579   cmake-data libarchive13 libjsoncpp24 librhash0 libuv1
4.579 Suggested packages:
4.579   cmake-doc ninja-build lrzip
4.623 The following NEW packages will be installed:
4.624   cmake cmake-data libarchive13 libjsoncpp24 librhash0 libuv1
4.745 0 upgraded, 6 newly installed, 0 to remove and 91 not upgraded.
4.745 Need to get 8000 kB of archives.
4.745 After this operation, 34.3 MB of additional disk space will be used.
4.745 Get:1 http://deb.debian.org/debian bullseye/main amd64 cmake-data all 3.18.4-2+deb11u1 [1725 kB]
4.946 Get:2 http://deb.debian.org/debian bullseye/main amd64 libarchive13 amd64 3.4.3-2+deb11u1 [343 kB]
4.951 Get:3 http://deb.debian.org/debian bullseye/main amd64 libjsoncpp24 amd64 1.9.4-4 [78.9 kB]
4.952 Get:4 http://deb.debian.org/debian bullseye/main amd64 librhash0 amd64 1.4.1-2 [129 kB]
4.953 Get:5 http://deb.debian.org/debian bullseye/main amd64 libuv1 amd64 1.40.0-2 [132 kB]
4.954 Get:6 http://deb.debian.org/debian bullseye/main amd64 cmake amd64 3.18.4-2+deb11u1 [5593 kB]
5.132 debconf: delaying package configuration, since apt-utils is not installed
5.161 Fetched 8000 kB in 0s (20.5 MB/s)
5.184 Selecting previously unselected package cmake-data.
(Reading database ... 22790 files and directories currently installed.)
5.196 Preparing to unpack .../0-cmake-data_3.18.4-2+deb11u1_all.deb ...
5.198 Unpacking cmake-data (3.18.4-2+deb11u1) ...
5.629 Selecting previously unselected package libarchive13:amd64.
5.632 Preparing to unpack .../1-libarchive13_3.4.3-2+deb11u1_amd64.deb ...
5.634 Unpacking libarchive13:amd64 (3.4.3-2+deb11u1) ...
5.676 Selecting previously unselected package libjsoncpp24:amd64.
5.678 Preparing to unpack .../2-libjsoncpp24_1.9.4-4_amd64.deb ...
5.680 Unpacking libjsoncpp24:amd64 (1.9.4-4) ...
5.701 Selecting previously unselected package librhash0:amd64.
5.703 Preparing to unpack .../3-librhash0_1.4.1-2_amd64.deb ...
5.705 Unpacking librhash0:amd64 (1.4.1-2) ...
5.727 Selecting previously unselected package libuv1:amd64.
5.729 Preparing to unpack .../4-libuv1_1.40.0-2_amd64.deb ...
5.731 Unpacking libuv1:amd64 (1.40.0-2) ...
5.754 Selecting previously unselected package cmake.
5.757 Preparing to unpack .../5-cmake_3.18.4-2+deb11u1_amd64.deb ...
5.758 Unpacking cmake (3.18.4-2+deb11u1) ...
6.208 Setting up libarchive13:amd64 (3.4.3-2+deb11u1) ...
6.211 Setting up libuv1:amd64 (1.40.0-2) ...
6.214 Setting up libjsoncpp24:amd64 (1.9.4-4) ...
6.217 Setting up librhash0:amd64 (1.4.1-2) ...
6.220 Setting up cmake-data (3.18.4-2+deb11u1) ...
6.225 Setting up cmake (3.18.4-2+deb11u1) ...
6.228 Processing triggers for libc-bin (2.31-13+deb11u5) ...
6.360   Installing drprg v0.1.1 (/drprg)
6.371     Updating crates.io index
232.2 warning: package `crossbeam-channel v0.5.7` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
232.2 warning: package `hermit-abi v0.3.1` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
232.5  Downloading crates ...
232.8   Downloaded lazy_static v1.4.0
232.8   Downloaded adler v1.0.2
232.8   Downloaded futures-task v0.3.28
232.8   Downloaded futures-channel v0.3.28
232.8   Downloaded proc-macro2 v1.0.56
232.8   Downloaded thiserror-impl v1.0.40
232.8   Downloaded tinyvec_macros v0.1.1
232.8   Downloaded tokio-native-tls v0.3.1
232.8   Downloaded tower-service v0.3.2
232.8   Downloaded tokio-util v0.7.7
232.8   Downloaded unicode-normalization v0.1.22
232.8   Downloaded cfg-if v1.0.0
232.8   Downloaded crc32fast v1.3.2
232.8   Downloaded dirs-sys-next v0.1.2
232.8   Downloaded xattr v0.2.3
232.8   Downloaded uuid v1.3.0
232.8   Downloaded tokio v1.27.0
232.9   Downloaded hashbrown v0.12.3
232.9   Downloaded itoa v1.0.6
232.9   Downloaded unicode-ident v1.0.8
232.9   Downloaded native-tls v0.2.11
232.9   Downloaded tar v0.4.38
232.9   Downloaded term v0.7.0
232.9   Downloaded scopeguard v1.1.0
232.9   Downloaded rustversion v1.0.12
232.9   Downloaded toml v0.5.11
232.9   Downloaded rustc_version v0.1.7
232.9   Downloaded want v0.3.0
232.9   Downloaded pkg-config v0.3.26
232.9   Downloaded serde_json v1.0.95
233.0   Downloaded termcolor v1.2.0
233.0   Downloaded syn v1.0.109
233.0   Downloaded regex v1.7.3
233.0   Downloaded tempfile v3.5.0
233.0   Downloaded syn v2.0.13
233.0   Downloaded slab v0.4.8
233.0   Downloaded thiserror v1.0.40
233.0   Downloaded serde_urlencoded v0.7.1
233.0   Downloaded ipnet v2.7.2
233.0   Downloaded encoding_rs v0.8.32
233.1   Downloaded bio-types v0.13.0
233.1   Downloaded h2 v0.3.16
233.1   Downloaded prettytable-rs v0.10.0
233.1   Downloaded jobserver v0.1.26
233.1   Downloaded mio v0.8.6
233.1   Downloaded idna v0.3.0
233.1   Downloaded futures-io v0.3.28
233.1   Downloaded rustix v0.37.7
233.1   Downloaded libc v0.2.140
233.2   Downloaded iana-time-zone v0.1.56
233.2   Downloaded lzma-sys v0.1.20
233.2   Downloaded csv v1.2.1
233.3   Downloaded bstr v0.2.17
233.3   Downloaded linux-raw-sys v0.3.1
233.3   Downloaded anstyle v0.3.5
233.3   Downloaded crossbeam-epoch v0.9.14
233.3   Downloaded anyhow v1.0.70
233.3   Downloaded strum v0.24.1
233.3   Downloaded semver v0.1.20
233.3   Downloaded openssl-macros v0.1.1
233.3   Downloaded autocfg v1.1.0
233.3   Downloaded libz-sys v1.1.8
233.4   Downloaded percent-encoding v2.2.0
233.4   Downloaded is-terminal v0.4.6
233.4   Downloaded io-lifetimes v1.0.9
233.4   Downloaded linear-map v1.2.0
233.4   Downloaded fs-utils v1.1.4
233.4   Downloaded noodles-gff v0.6.1
233.4   Downloaded noodles-bgzf v0.12.0
233.4   Downloaded noodles-core v0.7.0
233.4   Downloaded newtype_derive v0.1.6
233.4   Downloaded openssl-sys v0.9.84
233.4   Downloaded noodles v0.24.0
233.4   Downloaded rust-htslib v0.39.5
233.4   Downloaded reqwest v0.11.16
233.5   Downloaded noodles-fasta v0.11.0
233.5   Downloaded ieee754 v0.2.6
233.5   Downloaded custom_derive v0.1.7
233.5   Downloaded openssl v0.10.49
233.5   Downloaded hyper v0.14.25
233.5   Downloaded curl-sys v0.4.61+curl-8.0.1
233.8   Downloaded filetime v0.2.20
233.8   Downloaded crossbeam-channel v0.5.7
233.8   Downloaded num-traits v0.2.15
233.9   Downloaded serde v1.0.159
233.9   Downloaded clap_lex v0.4.1
233.9   Downloaded encode_unicode v1.0.0
233.9   Downloaded hts-sys v2.0.3
234.0   Downloaded foreign-types-shared v0.1.1
234.0   Downloaded clap v4.2.1
234.0   Downloaded openssl-src v111.25.2+1.1.1t
234.3   Downloaded concolor-query v0.3.3
234.3   Downloaded clap_builder v4.2.1
234.3   Downloaded regex-automata v0.1.10
234.3   Downloaded rayon v1.7.0
234.3   Downloaded clap_derive v4.2.0
234.3   Downloaded chrono v0.4.24
234.3   Downloaded rayon-core v1.11.0
234.3   Downloaded quote v1.0.26
234.3   Downloaded quick-error v1.2.3
234.3   Downloaded pin-utils v0.1.0
234.3   Downloaded pin-project-lite v0.2.9
234.3   Downloaded openssl-probe v0.1.5
234.3   Downloaded once_cell v1.17.1
234.3   Downloaded memoffset v0.8.0
234.3   Downloaded anstyle-parse v0.1.1
234.3   Downloaded strum_macros v0.24.3
234.3   Downloaded strsim v0.10.0
234.3   Downloaded socket2 v0.4.9
234.3   Downloaded num_cpus v1.15.0
234.3   Downloaded num-integer v0.1.45
234.4   Downloaded bzip2-sys v0.1.11+1.0.8
234.4   Downloaded anstream v0.2.6
234.4   Downloaded miniz_oxide v0.6.2
234.4   Downloaded memchr v2.5.0
234.4   Downloaded glob v0.3.1
234.4   Downloaded fs_extra v1.3.0
234.4   Downloaded mime v0.3.17
234.4   Downloaded log v0.4.17
234.4   Downloaded foreign-types v0.3.2
234.4   Downloaded float-cmp v0.9.0
234.4   Downloaded env_logger v0.9.3
234.4   Downloaded concolor-override v1.0.0
234.4   Downloaded indexmap v1.9.3
234.4   Downloaded hyper-tls v0.5.0
234.4   Downloaded humantime v2.1.0
234.4   Downloaded httpdate v1.0.2
234.4   Downloaded httparse v1.8.0
234.4   Downloaded http-body v0.4.5
234.4   Downloaded http v0.2.9
234.4   Downloaded heck v0.4.1
234.4   Downloaded getrandom v0.2.8
234.4   Downloaded fastrand v1.9.0
234.4   Downloaded crossbeam-utils v0.8.15
234.4   Downloaded cmake v0.1.50
234.4   Downloaded cc v1.0.79
234.4   Downloaded byteorder v1.4.3
234.4   Downloaded futures-sink v0.3.28
234.4   Downloaded bytes v1.4.0
234.4   Downloaded base64 v0.21.0
234.5   Downloaded futures-util v0.3.28
234.5   Downloaded futures-core v0.3.28
234.5   Downloaded form_urlencoded v1.1.0
234.5   Downloaded flate2 v1.0.25
234.5   Downloaded atty v0.2.14
234.5   Downloaded aho-corasick v0.7.20
234.5   Downloaded fnv v1.0.7
234.5   Downloaded either v1.8.1
234.5   Downloaded derive-new v0.5.9
234.5   Downloaded utf8parse v0.2.1
234.5   Downloaded url v2.3.1
234.5   Downloaded unicode-width v0.1.10
234.5   Downloaded unicode-bidi v0.3.13
234.5   Downloaded try-lock v0.2.4
234.5   Downloaded tracing-core v0.1.30
234.5   Downloaded tracing v0.1.37
234.5   Downloaded serde_derive v1.0.159
234.5   Downloaded dirs-next v2.0.0
234.5   Downloaded csv-core v0.1.10
234.5   Downloaded crossbeam-deque v0.8.3
234.5   Downloaded ryu v1.0.13
234.5   Downloaded tinyvec v1.6.0
234.5   Downloaded bitflags v1.3.2
234.5   Downloaded regex-syntax v0.6.29
234.6   Downloaded time v0.1.45
234.6    Compiling libc v0.2.140
234.6    Compiling cfg-if v1.0.0
234.6    Compiling autocfg v1.1.0
234.6    Compiling pkg-config v0.3.26
234.6    Compiling proc-macro2 v1.0.56
234.6    Compiling quote v1.0.26
234.6    Compiling unicode-ident v1.0.8
234.6    Compiling memchr v2.5.0
234.7    Compiling log v0.4.17
234.7    Compiling bitflags v1.3.2
234.7    Compiling once_cell v1.17.1
234.7    Compiling bytes v1.4.0
234.7    Compiling pin-project-lite v0.2.9
234.7    Compiling itoa v1.0.6
234.7    Compiling futures-core v0.3.28
234.7    Compiling io-lifetimes v1.0.9
234.9    Compiling serde v1.0.159
235.0    Compiling rustix v0.37.7
235.2    Compiling futures-task v0.3.28
235.2    Compiling percent-encoding v2.2.0
235.4    Compiling crossbeam-utils v0.8.15
236.3    Compiling linux-raw-sys v0.3.1
236.7    Compiling tracing-core v0.1.30
236.7    Compiling tokio v1.27.0
236.8    Compiling slab v0.4.8
236.8    Compiling indexmap v1.9.3
237.3    Compiling memoffset v0.8.0
237.3    Compiling tinyvec_macros v0.1.1
237.7    Compiling foreign-types-shared v0.1.1
237.7    Compiling syn v1.0.109
238.0    Compiling crc32fast v1.3.2
238.1    Compiling openssl v0.10.49
238.2    Compiling futures-util v0.3.28
238.3    Compiling fnv v1.0.7
238.8    Compiling tracing v0.1.37
238.9    Compiling http v0.2.9
239.7    Compiling foreign-types v0.3.2
239.9    Compiling tinyvec v1.6.0
240.1    Compiling crossbeam-epoch v0.9.14
240.2    Compiling num-traits v0.2.15
240.3    Compiling syn v2.0.13
241.1    Compiling semver v0.1.20
241.4    Compiling adler v1.0.2
241.4    Compiling rustversion v1.0.12
241.6    Compiling ryu v1.0.13
241.7    Compiling pin-utils v0.1.0
241.9    Compiling httparse v1.8.0
242.2    Compiling quick-error v1.2.3
242.7    Compiling futures-io v0.3.28
242.8    Compiling heck v0.4.1
243.0    Compiling futures-sink v0.3.28
243.1    Compiling hashbrown v0.12.3
243.2    Compiling futures-channel v0.3.28
243.6    Compiling native-tls v0.2.11
243.7    Compiling fs-utils v1.1.4
244.0    Compiling jobserver v0.1.26
244.2    Compiling num_cpus v1.15.0
244.5    Compiling mio v0.8.6
244.6    Compiling socket2 v0.4.9
244.7    Compiling unicode-normalization v0.1.22
245.0    Compiling rustc_version v0.1.7
245.0    Compiling cc v1.0.79
245.2    Compiling miniz_oxide v0.6.2
248.7    Compiling openssl-src v111.25.2+1.1.1t
249.1    Compiling cmake v0.1.50
250.1    Compiling aho-corasick v0.7.20
250.1    Compiling form_urlencoded v1.1.0
250.5    Compiling openssl-probe v0.1.5
250.5    Compiling scopeguard v1.1.0
251.1    Compiling unicode-bidi v0.3.13
251.3    Compiling regex-syntax v0.6.29
251.7    Compiling openssl-sys v0.9.84
251.8    Compiling libz-sys v1.1.8
252.1    Compiling bzip2-sys v0.1.11+1.0.8
252.3    Compiling curl-sys v0.4.61+curl-8.0.1
252.5    Compiling lzma-sys v0.1.20
252.6    Compiling utf8parse v0.2.1
253.4    Compiling lazy_static v1.4.0
253.9    Compiling try-lock v0.2.4
254.5    Compiling byteorder v1.4.3
254.5    Compiling thiserror v1.0.40
255.0    Compiling glob v0.3.1
255.2    Compiling want v0.3.0
256.2    Compiling is-terminal v0.4.6
256.3    Compiling anstyle-parse v0.1.1
256.3    Compiling idna v0.3.0
256.9    Compiling flate2 v1.0.25
257.6    Compiling hts-sys v2.0.3
257.7    Compiling newtype_derive v0.1.6
260.2    Compiling dirs-sys-next v0.1.2
260.6    Compiling regex v1.7.3
261.5    Compiling http-body v0.4.5
261.5    Compiling num-integer v0.1.45
261.7    Compiling serde_json v1.0.95
262.9    Compiling httpdate v1.0.2
263.0    Compiling noodles-core v0.7.0
263.7    Compiling concolor-override v1.0.0
264.0    Compiling rayon-core v1.11.0
264.2    Compiling tower-service v0.3.2
264.3    Compiling concolor-query v0.3.3
264.4    Compiling anstyle v0.3.5
264.7    Compiling tokio-util v0.7.7
264.9    Compiling dirs-next v2.0.0
265.5    Compiling anstream v0.2.6
265.6    Compiling noodles-bgzf v0.12.0
265.7    Compiling url v2.3.1
265.8    Compiling openssl-macros v0.1.1
266.1    Compiling thiserror-impl v1.0.40
266.2    Compiling crossbeam-deque v0.8.3
266.5    Compiling crossbeam-channel v0.5.7
266.6    Compiling csv-core v0.1.10
267.2    Compiling h2 v0.3.16
267.3    Compiling anyhow v1.0.70
269.2    Compiling clap_lex v0.4.1
269.2    Compiling serde_derive v1.0.159
269.2    Compiling strsim v0.10.0
270.4    Compiling clap_builder v4.2.1
271.5    Compiling csv v1.2.1
271.6    Compiling noodles-fasta v0.11.0
273.0    Compiling clap_derive v4.2.0
275.1    Compiling term v0.7.0
276.6    Compiling noodles-gff v0.6.1
278.0    Compiling serde_urlencoded v0.7.1
279.2    Compiling xattr v0.2.3
280.5    Compiling time v0.1.45
281.6    Compiling hyper v0.14.25
282.4    Compiling strum_macros v0.24.3
282.5    Compiling derive-new v0.5.9
284.1    Compiling filetime v0.2.20
284.5    Compiling getrandom v0.2.8
285.8    Compiling atty v0.2.14
286.3    Compiling encoding_rs v0.8.32
286.4    Compiling linear-map v1.2.0
286.4    Compiling ieee754 v0.2.6
287.3    Compiling regex-automata v0.1.10
287.5    Compiling ipnet v2.7.2
287.6    Compiling fastrand v1.9.0
287.9    Compiling custom_derive v0.1.7
288.5    Compiling termcolor v1.2.0
289.0    Compiling unicode-width v0.1.10
289.5    Compiling base64 v0.21.0
289.7    Compiling humantime v2.1.0
290.6    Compiling encode_unicode v1.0.0
292.6    Compiling mime v0.3.17
292.9    Compiling iana-time-zone v0.1.56
293.0    Compiling either v1.8.1
293.6    Compiling chrono v0.4.24
293.8    Compiling bio-types v0.13.0
293.9    Compiling rayon v1.7.0
295.1    Compiling prettytable-rs v0.10.0
295.2    Compiling env_logger v0.9.3
295.7    Compiling tempfile v3.5.0
295.8    Compiling bstr v0.2.17
296.6    Compiling clap v4.2.1
297.3    Compiling uuid v1.3.0
301.3    Compiling tar v0.4.38
301.5    Compiling noodles v0.24.0
303.3    Compiling float-cmp v0.9.0
304.1    Compiling toml v0.5.11
306.3    Compiling fs_extra v1.3.0
307.4    Compiling strum v0.24.1
371.4    Compiling tokio-native-tls v0.3.1
371.7    Compiling hyper-tls v0.5.0
372.0    Compiling reqwest v0.11.16
374.3    Compiling rust-htslib v0.39.5
375.3    Compiling drprg v0.1.1 (/drprg)
387.8 error[E0658]: use of unstable library feature 'map_first_last'
387.8    --> src/index.rs:167:27
387.8     |
387.8 167 |                 spec_conf.last_key_value()
387.8     |                           ^^^^^^^^^^^^^^
387.8     |
387.8     = note: see issue #62924 <https://github.com/rust-lang/rust/issues/62924> for more information
387.8 
387.9 For more information about this error, try `rustc --explain E0658`.
387.9 error: could not compile `drprg` due to previous error
387.9 error: failed to compile `drprg v0.1.1 (/drprg)`, intermediate artifacts can be found at `/drprg/target`
------
Dockerfile:13
--------------------
  12 |     
  13 | >>> RUN apt update \
  14 | >>>     && apt install -y cmake \
  15 | >>>     && cargo install --locked --path /drprg --root /usr \
  16 | >>>     && (wget -O - "$JUST_URL" | bash -s -- --to /usr/bin --tag "$V_JUST") \
  17 | >>>     && just -f /drprg/justfile EXTDIR=/usr/bin pandora \
  18 | >>>     && just -f /drprg/justfile EXTDIR=/usr/bin bcftools \
  19 | >>>     && just -f /drprg/justfile EXTDIR=/usr/bin makeprg \
  20 | >>>     && wget -O "$DEB" "$MAFFT_URL" \
  21 | >>>     && dpkg -i "$DEB" \
  22 | >>>     && apt remove -y cmake \
  23 | >>>     && rm -rf /drprg "$DEB" /var/lib/apt/lists/*
  24 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt update     && apt install -y cmake     && cargo install --locked --path /drprg --root /usr     && (wget -O - \"$JUST_URL\" | bash -s -- --to /usr/bin --tag \"$V_JUST\")     && just -f /drprg/justfile EXTDIR=/usr/bin pandora     && just -f /drprg/justfile EXTDIR=/usr/bin bcftools     && just -f /drprg/justfile EXTDIR=/usr/bin makeprg     && wget -O \"$DEB\" \"$MAFFT_URL\"     && dpkg -i \"$DEB\"     && apt remove -y cmake     && rm -rf /drprg \"$DEB\" /var/lib/apt/lists/*" did not complete successfully: exit code: 101
```

**Comment by Kincekara** [comment]
It seems it is pretty complex to build from scratch. Thank you for trying! I am merging this PR...

**Review by Kincekara — APPROVED** [review]

**Comment by Kincekara** [comment]
Thank you for your PR! You can check the status of the deploy here: https://github.com/StaPH-B/docker-builds/actions/runs/6896754243

**Pull request merged**
