### PR TITLE
updating datasets to 14.27.0, 15.1.0, and 15.2.0

### PR DESCRIPTION
**Pull request by erinyoung**
This updates ncbi-datasets to the most recent version. This includes the most recent ProkDataFreeze.

I didn't change anything other than the version.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Since it's been two weeks, I added in the datasets version of TODAY - which is May 26, 2023

https://github.com/ncbi/datasets/releases/tag/v15.0.0

So this PR actually contains the Dockerfiles for 14.27.0 AND [15.1.0](https://github.com/ncbi/datasets/releases/tag/v15.1.0)

Datasets version 15.1.0 has several changes from the 14.* versions:

⚠ BREAKING CHANGES
Features: Update v2alpha assembly report field from submission_date to release_date

Bug Fixes: Restore right navbar
ProkDataFreeze
Bug Fixes: Automatically generate new prok data freeze (May 23, 2023)

Services
Features: Add Assembly DB sort order by default to assembly requests
Bug Fixes: Fix species-level check in taxtree builder and name-match
Bug Fixes: Make data name change backwards compatible for rev. history
Features: Sort order by default is honored

**Comment by erinyoung** [comment]
I have now added a dockerfile for version [15.2.0](https://github.com/ncbi/datasets/releases/tag/v15.2.0). This has a bug fix for tax building.

**Review by kapsakcj — APPROVED** [review]
Everything looks good, I'll deploy docker images for these 3 versions and make sure that `:latest` tag includes v15.2.0

**Comment by kapsakcj** [comment]
14.27.0 deploy: https://github.com/StaPH-B/docker-builds/actions/runs/5195198872

15.1.0 deploy: https://github.com/StaPH-B/docker-builds/actions/runs/5195199992

15.2.0 deploy: https://github.com/StaPH-B/docker-builds/actions/runs/5195201755

**Pull request merged**
