### PR TITLE
adding dsk version 2.3.3

### PR DESCRIPTION
**Pull request by erinyoung**
There's a new version of dsk!

Well, actually a few. There are some new features, but most of the updates are basically bug fixes.

For example:
> No new features, just a collection of bugfixes accumulated since last year
- Found in https://github.com/GATB/dsk/releases/tag/v2.3.1

I updated the base image to ubuntu:jammy, updated the DSK version, and added a version for GATB-CORE. I also removed the requirement for git.

This image would probably benefit from a builder stage, but I did not attempt that option.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by Kincekara** [comment]
@erinyoung Did you check the prebuild binary?
https://github.com/GATB/dsk/releases/download/v2.3.3/dsk-v2.3.3-bin-Linux.tar.gz

**Comment by erinyoung** [comment]
Adjusting dsk to just download the executable would probably decrease the image size, but the tests stop working.

```
> [test 4/5] RUN bash /dsk-v2.3.3-bin-Linux/test/simple_test.sh:                                                                                                                                
1.375 Testing ../bin/dsk
1.375 Testing single gz file .........../dsk-v2.3.3-bin-Linux/test/simple_test.sh: line 37: ../bin/gatb-h5dump: No such file or directory
1.673 FAILED
------
```

**Comment by erinyoung** [comment]
@Kincekara , I decided to take a look at the binaries again. Turns out the binaries for the dependency needed to be downloaded as well, and then moved/copied to a specific location.

I also added a test with an actual file.

**Review by Kincekara — APPROVED** [review]
@erinyoung thank you for the changes. It looks great. I am merging and deploying this.

**Pull request merged**
