### PR TITLE
Fastp version 0.23.4

### PR DESCRIPTION
**Pull request by erinyoung**
There's a new version of fastp out! This one fixes the bug where fastp hangs if there's an issue with the fastq file. More information here : https://github.com/OpenGene/fastp/issues/486

Edit: This was originally for fastp version 0.23.2, but has been updated to be for version 0.23.4. This is now ready for review.

I created this Dockerfile from copying the version 0.23.2, but I made the following changes
- I changed the image to jammy 
- I added myself as maintianer2
- I added --no-install-recommends to the apt-get line
- I moved the `fastp --help` to a CMD layer instead of a RUN layer in the test stage
- I changed path so that fastp is first

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Sorry for not putting this as a draft request initially! 

I ran into problems (https://github.com/OpenGene/fastp/issues/491), but didn't want to lose my work, and didn't want anyone else to have to replicate my errors.

**Comment by erinyoung** [comment]
I think we are going to need to skip fastp version 0.23.3. There is an error reading certain files based on how they were compressed. 0.23.4 has a fix, so I vote we just skip 0.23.3

Once fastp is up on opengene, I will change this to a real PR and request a review.

**Comment by erinyoung** [comment]
fastp is up on opengene! This PR is ready for review!

**Review by kapsakcj — APPROVED** [review]
Thanks for the PR and providing updates along the way as you were troubleshooting.

made a few minor changes for markdown formatting & consolidated 2 RUN layers in the test stage.

I'll merge and deploy to dockerhub & quay

don't forget to delete your dev branch

**Comment by kapsakcj** [comment]
deploy workflow here: https://github.com/StaPH-B/docker-builds/actions/runs/5195265151

**Pull request merged**
