### PR TITLE
adding procps to shigatyper

### PR DESCRIPTION
**Pull request by erinyoung**
```
Command 'ps' required by nextflow to collect task metrics cannot be found
```

If this doesn't fix all the issues, I'm rebuilding this with the micromamba image.

### CODE REVIEW

**Comment by kapsakcj** [comment]
Are you sure you have the latest version pulled? I think `ps` is already in the latest docker image

```
$ docker run staphb/shigatyper:2.0.1 ps
    PID TTY          TIME CMD
      1 ?        00:00:00 ps

$ docker run staphb/shigatyper:latest ps
    PID TTY          TIME CMD
      1 ?        00:00:00 ps
```

**Comment by erinyoung** [comment]
What about plasmidfinder? I'm getting the ps error with that one as well.

Although, I wonder if something is just off about my linux workstation

**Comment by kapsakcj** [comment]
I think it's the same with plasmidfinder, `ps` looks to be installed. Both when I run as root user and non-root

```
$ docker_run staphb/plasmidfinder:latest ps
    PID TTY          TIME CMD
      1 ?        00:00:00 ps
$ docker_run staphb/plasmidfinder:2.1.6 ps
    PID TTY          TIME CMD
      1 ?        00:00:00 ps
```

**Comment by kapsakcj** [comment]
also available in the ubuntu:focal base image

```
$ docker_run ubuntu:focal ps
    PID TTY          TIME CMD
      1 ?        00:00:00 ps
```

**Pull request closed without merging**
