### PR TITLE
Add ParSNP image and GitHub workflows for deploying image

### PR DESCRIPTION
**Pull request by SarahNadeau**
This pull request is to add a ParSNP image. It also implements automated image deployment with GitHub actions.

- Size comparison for the image built to different stages (only app stage gets deployed)
image_size_comparison

- Tests are ParSNP running on real data, results must look similar to a reference phylogeny for the data

- The deploy workflow requires GitHub secrets `DOCKER_HUB_USERNAME` and `DOCKER_HUB_ACCESS_TOKEN`. See https://docs.docker.com/ci-cd/github-actions/#set-up-a-docker-project for instructions.

You can see the deploy workflow in action in my fork, where I just swapped the staphb docker hub repo for my own (see [here](https://github.com/SarahNadeau/docker-builds/blob/parsnp-with-deploy-wf/.github/workflows/deploy-parsnp.yml#L34)) and ran the workflow. Results are [here](https://github.com/SarahNadeau/docker-builds/actions/workflows/deploy-parsnp.yml).

### CODE REVIEW

**Comment by SarahNadeau** [comment]
@fanninpm I don't have your email but I just reached out to @lskatz to see if I can help somehow wrapping the different GH workflow testing ideas into a coherant strategy.

**Comment by k-florek** [comment]
@SarahNadeau Based on PR #280 will this PR need a couple tweaks to utilize the `build-to-test` workflow? Additionally if I understand this all correctly we would want a `build-to-test` workflow for building and testing an image and a `build-to-deploy` workflow that would then assuming the test passed build the image and push it to docker hub?

Should we wait to review and merge these changes once we have the testing and deploying workflows established in the repo?

**Comment by SarahNadeau** [comment]
> Additionally if I understand this all correctly we would want a `build-to-test` workflow for building and testing an image and a `build-to-deploy` workflow that would then assuming the test passed build the image and push it to docker hub?

Yes, exactly. Would it make sense to add build-to-deploy to #280 so this would be a clean PR for just ParSNP?

> Based on PR #280 will this PR need a couple tweaks to utilize the `build-to-test` workflow? ... Should we wait to review and merge these changes once we have the testing and deploying workflows established in the repo?

Yes please hold off on reviewing! I would like to update this PR after #280 is incorporated.

**Comment by k-florek** [comment]
> Yes, exactly. Would it make sense to add build-to-deploy to #280 so this would be a clean PR for just ParSNP?

@SarahNadeau For the build to deploy feel free to include it here or in a separate PR, whichever is easiest!

**Comment by SarahNadeau** [comment]
Ugh, sorry about all the messy force push history changes. But the PR is now cleaned up for review.

**Comment by k-florek** [comment]
I fixed the conflict in `make_containers.md`

**Review by erinyoung — COMMENTED** [review]
I'd love to review this, and it looks like it makes sense. I'd like to set up a call to discuss things so I have a better understanding.

**Review by erinyoung — APPROVED** [review]
Thanks for meeting with me!

**Pull request merged**
