### PR TITLE
add kaptive 2.0.7 & custom Vibrio parahaemolyticus serotyping db, take 2

### LINKED ISSUE #661: [Request An Update]: kaptive 2.0.7 + V. parahaemolyticus databases
### What container needs an update?

upgrade to kaptive 2.0.7 and add capability to serotype V. parahaemolyticus using newly-released databases

original tweet that I saw: https://twitter.com/DrKatHolt/status/1653795878077968386

publication: https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.001007

github repo for where V. parahaemolyticus databases live: https://github.com/aldertzomer/vibrio_parahaemolyticus_genomoserotyping

would be good to also add a test to the `test` stage that downloads a V. parahaemolyticus genome and runs `kaptive` on it with the new databases

### PR DESCRIPTION
**Pull request by kapsakcj**
This PR will close #661 

This PR adds a dockerfile for Kaptive v2.0.7 and adds a new database for Vibrio parahaemolyticus locus typing.

Differences from previous dockerfile:

- Added Vp databases (GBK files) to container filesystem
- Added tests for analyzing 2 Vp genomes with new Vp databases
- added default `CMD` to end of `app` stage
- moved test commands to write to `/test` in filesystem
- quieted down `wget` and `gunzip` commands

CC @stitam - please let us know if you have any feedback. Wanted to give you a heads up since you originally wrote the dockerfile

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
I've pushed the docker image to my personal dockerhub in case anyone wants to test it out before we merge the PR.

https://hub.docker.com/r/kapsakcj/kaptive

`kapsakcj/kaptive:2..0.7`

The tests (Vp genomes included) run successfully, but I have not tested the new database extensively. Would be nice to run on more genomes before merging this PR. (not required but nice to do)

**Comment by erinyoung** [comment]
I think it works as expected. I was hoping an identification of O groups, but that doesn't seem to be what this database is for (or perhaps my test files were faulty).

Can we move the Vibrio database to /kaptive/reference_database to be with the rest of them, though?

**Comment by kapsakcj** [comment]
> Can we move the Vibrio database to /kaptive/reference_database to be with the rest of them, though?

Sure, I don't see any issue with that.

Feel free to push commits here, or I can get to it in the near future (next week or so)

**Comment by kapsakcj** [comment]
also if we move the database the readme.md will need to be updated accordingly too

**Comment by kapsakcj** [comment]
closing this since these databases were added in https://github.com/StaPH-B/docker-builds/pull/844

**Pull request closed without merging**
