### PR TITLE
Adds vadr 1.6.3

### PR DESCRIPTION
**Pull request by nawrockie**
Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] DID NOT TEST: The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by nawrockie** [comment]
@kapsakcj : vadr 1.6.3 is now available along with the flu models (https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/flu/). Note that I made a new vadr release (1.6.3) but wasn't able to update the name of this PR, so it is still `Adds vadr 1.6.2`. 

I think I've completed or addressed everything on your TODO list above, but see my comment about not using NCBI datasets below.

`vadr/1.6.2/Dockerfile` changes:

- [x]  add code to download VADR Flu model files similar to how it's done for RSV, with a new ARG near the top of the dockerfile & a similar code block to lines 85-90 for RSV. Will have to be done in the `app` stage of the build of course.
- [x]  add test near bottom of dockerfile to test Flu functionality
  - [x] download test genome using NCBI datasets. Anyone know of a good genome we could use to test? Perhaps a recently (w/in last 3 years?) sequenced Flu sample? ***Instead of using datasets, I added `wget` of sample flu sequence file***
  - [x]  run /opt/vadr/vadr/miniscripts/fasta-trim-terminal-ambigs.pl to trim terminal ambiguous nucleotides
  - [x] run v-annotate.pl with the recommended options for Flu & Flu model files

`vadr/1.6.2/README.md` changes:

- [x] add links to VADR docs on Flu (if any are available)

**Comment by kapsakcj** [comment]
Everything looks great, thank you for making those changes! Totally fine about using `wget` instead of NCBI `datasets` 👍 

Looks like tests are passing successfully in the GHActions workflow 👍 

----

For our future reference, when the docker image is built to the `app` stage (which is the final stage of the docker image that's published to dockerhub & quay, does not include the `test` stage) looks to be 6.5 GB uncompressed & 885 MB compressed. `staphb/vadr:1.5.1` docker image is 857 MB compressed

I believe this mostly is due to the size of the VADR model files. It's a little bit more bloated than I'd like but it is way more convenient than bringing in the model files into the container at runtime (i.e. during a nextflow or WDL workflow). This also helps ensure the model files are kept static.

**Comment by kapsakcj** [comment]
The most recent GHActions log will not be useful, as the docker image building is cached (we need to fix this), but the original GHActions log has the STDOUT that we need: https://github.com/StaPH-B/docker-builds/actions/runs/7280186063/job/19838140580

The output looks to match that listed on the wiki here: https://github.com/ncbi/vadr/wiki/Influenza-annotation#example-annotation-of-flu-sequences-1

For other's reference, the test sequences used in the dockerfile have 2 sequences that pass and 1 that fails (as expected)

🎉  I have no further comments/suggestions. I will now merge this PR, and trigger the workflow to deploy the docker image to dockerhub and quay

**Comment by kapsakcj** [comment]
oh whoops! need to update the main README.md before merging. I'll push a commit in a moment

**Review by kapsakcj — APPROVED** [review]

**Comment by kapsakcj** [comment]
Thank you for you contribution (in addition to developing VADR!) to this repo! This tool has been super useful to public health labs amidst the COVID19 pandemic, the recent Mpox outbreaks, Dengue, RSV, other viral genomic surveillance, and now available for Flu surveillance. This is very timely as more and more labs are building Influenza sequencing capacity & submit more data to NCBI & other repositories

If you're curious to see the progress of the deployment to dockerhub and quay, you can view the log here: https://github.com/StaPH-B/docker-builds/actions/runs/7293071694

But in ~15 or so minutes we will have the same docker image deployed in 2 places, under 4 different docker image tags:
1. `staphb/vadr:1.6.3` (dockerhub)
2. `staphb/vadr:latest` (dockerhub)
3. `quay.io/staphb/vadr:1.6.3`
4. `quay.io/staphb/vadr:latest`

**Comment by nawrockie** [comment]
Thanks, @kapsakcj ! I added links to dockerhub and quay here: 
https://github.com/ncbi/vadr/wiki/influenza-annotation

**Pull request merged**
