### PR TITLE
Updating Datasets and MultiQC

### PR DESCRIPTION
**Pull request by erinyoung**
THERE'S A NEW VERSION OF DATASETS OUT!!!

I copied the files from 15.31.1 and changed the version ARG.

There have been a lot of minor improvements.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by Kincekara** [comment]
@erinyoung multiqc interfered with your pull request.

**Comment by erinyoung** [comment]
@Kincekara Oh snap!!!

I didn't realize I put these on the same branch. 

For MultiQC 1.19, I just copied the files from 1.18 and changed the ARG.

Do you want me to remove those from this PR and put them into another one?

**Comment by Kincekara** [comment]
It's a little confusing to see multiple dockerfiles in a single PR. There is no need to separate them this time.  I will merge this PR as it is.

**Review by Kincekara — APPROVED** [review]

**Comment by Kincekara** [comment]
Thank you for your PR!
datasets: https://github.com/StaPH-B/docker-builds/actions/runs/7478801729
multiqc: https://github.com/StaPH-B/docker-builds/actions/runs/7478791820

**Pull request merged**
