### PR TITLE
adds pbptyper 1.0.4

### PR DESCRIPTION
**Pull request by kapsakcj**
Adds dockerfile and README.md for `pbptyper` 1.0.4. The changes include addition of `fastANI` as a screening step & the new flag `pbptyper --check` to check tblastn and fastANI dependencies.

The test layer was altered slightly from the previous dockerfile, mainly so that all outputs are dumped into `/test` instead of a few different sub-directories.

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
If anyone has time to review this, I'd appreciate it. Dockerfile is nearly identical to the previous version (1.0.1)

**Review by erinyoung — APPROVED** [review]
Looks like everything worked. Made it to the last test without issues.
```
#12 [test 4/4] RUN pbptyper --help &&  pbptyper --check &&  pbptyper --version
#12 0.255                                                                                 
#12 0.255  Usage: pbptyper [OPTIONS]                                                      
#12 0.255                                                                                 
#12 0.256  In silico Penicillin Binding Protein (PBP) typer for Streptococcus pneumoniae  
#12 0.256  assemblies                                                                     
#12 0.256                                                                                 
#12 0.273 ╭─ Options ────────────────────────────────────────────────────────────────────╮
#12 0.273 │    --version                  Show the version and exit.                     │
#12 0.273 │ *  --assembly        TEXT     Input assembly in FASTA format (gzip is OK)    │
#12 0.273 │                               [required]                                     │
#12 0.273 │    --db              TEXT     Path to the input database                     │
#12 0.273 │                               [default: /opt/conda/share/pbptyper-1.0.4]     │
#12 0.273 │    --prefix          TEXT     Prefix to use for output files                 │
#12 0.273 │                               [default: basename of input]                   │
#12 0.273 │    --outdir          TEXT     Directory to save output files [default: ./]   │
#12 0.273 │    --min_pident      INTEGER  Minimum percent identity to count a hit        │
#12 0.273 │                               [default: 95]                                  │
#12 0.273 │    --min_coverage    INTEGER  Minimum percent coverage to count a hit        │
#12 0.273 │                               [default: 95]                                  │
#12 0.273 │    --min_ani         INTEGER  Minimum S. pneumoniae ANI to predict PBP Type  │
#12 0.273 │                               [default: 90]                                  │
#12 0.273 │    --check                    Check dependencies are installed, then exit    │
#12 0.273 │    --quiet                    Suppress all output                            │
#12 0.273 │    --help                     Show this message and exit.                    │
#12 0.273 ╰──────────────────────────────────────────────────────────────────────────────╯
#12 0.273 
#12 0.450 Checking dependencies...
#12 0.451 Found fastANI at /opt/conda/bin/fastANI
#12 0.452 Found tblastn at /opt/conda/bin/tblastn
#12 0.452 You are all set!
#12 0.625 pbptyper, version 1.0.4
#12 DONE 0.7s
```

**Comment by erinyoung** [comment]
I'll push this to quay and dockerhub

**Comment by kapsakcj** [comment]
thank you thank you!

**Pull request merged**
