### PR TITLE
adding ivar 1.4

### PR DESCRIPTION
**Pull request by erinyoung**
Supposedly the lengthy time of ivar trim has been resolved (https://github.com/andersen-lab/ivar/releases/tag/v1.4).

EDIT: the following statement does not, yet, apply, but could in a future release.

<del>
Also of note, 
> Alignment file (Sorted/Unsorted SAM/BAM) can now be piped into ivar trim. Further, if no prefix using -p is specified, ivar trim will output trimmed SAM to stdout. This enables going from alignment to consensus using a one-liner. For example,
bwa mem idx read1.fq reads2.fq | ivar trim -b test.bed -x 3 -m 30 | samtools sort - | samtools mpileup -aa -A -Q 0 -d 0 - | ivar consensus -p test_consensus -m 10 -n N -t 0.5

So I'm really tempted to include bwa and minimap2 in the ivar container.

I have left them out for now.

</del>

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Also, this Dockerfile is an exact copy of `1.3.2`. I only changed the ivar version variable.

**Comment by kapsakcj** [comment]
I vote that we include the latest versions of bwa and minimap2, that looks to be super handy

**Comment by erinyoung** [comment]
Converting to draft for now. I'm going to be adding in bwa and minimap2.

**Comment by erinyoung** [comment]
I have changed this back to being ready for review. Apparently the advertised piping feature isn't fully ready yet. 

This is from a conversation I had with Karthik on slack today (March 20, 2023):
> Sorry, this is an issue that was introduced because we now sample the first 1000 reads to get an estimate of the read length which interferes with the piping. We should push a patch in the next 2-3 days. I'll keep you updated!

So I'll include bwa and minimap2 in a later release, but not this one.

**Pull request closed without merging**
