### PR TITLE
Adds mykrobe 0.12.1 and new genotyphi version 2.0

### PR DESCRIPTION
**Pull request by kapsakcj**
Added a new dockerfile for mykrobe that includes the latest version of genotyphi, v2.0.

Changes from previous dockerfile:

- updated base image to `mambaorg/micromamba:1.4.1`
- added `ARG GENOTYPHI_VER="2.0"` since last dockerfile used git commit hash instead of downloading a `.tar.gz` release from github
- updated LABELs
- removed `git` from `apt-get install` since it's no longer required
- downloading genotyphi code by `wget`'ing from github release tarball instead of `git clone` and `git checkout` to a specific commit hash
- added stage based on docker image `ncbi/sra-tools:3.0.1` for downloading test FASTQs for both Salmonella Typhi and Shigella sonnei
- added 2 new tests at bottom of dockerfile for running `mykrobe` on each of the test FASTQ pairs & testing both the genotyphi & sonneityping parsing scripts to ensure functionality.

Due to the added tests, it will take a little bit longer to run the test suite than before. I didn't spend too much time looking for tiny test FASTQ files, so it may be a bit slow to test on the GH Actions runners. 

🚨 Since this is not a new version of Mykrobe, I propose that we overwrite the `staphb/mykrobe:latest` docker image tag and generate a new tag `staphb/mykrobe:0.12.1-mykrobe-2.0 ` (instead of overwriting the `staphb/mykrobe:0.12.1` tag) 🚨 

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
One more thing to note - whenever review is completed, can we please update `/mykrobe/0.12.1-genotyphi-2.0/README.md` on line 21 to list the date `YYYY-MM-DD`? Just so that we accurately capture when docker image was built

Obviously will need to occur before merging the PR

**Comment by kapsakcj** [comment]
This PR will fix issue #505 when merged

**Review by erinyoung — APPROVED** [review]
I don't see any changes to recommend.

The tests look like they all worked.

I have edited the readme to include today's date.

I am going to 
- merge this PR
- deploy to dockerhub and quay using the tag '0.12.1-mykrobe-2.0'
- overwrite the 'latest' tag

**Comment by kapsakcj** [comment]
awesome, thank you so much!

**Comment by erinyoung** [comment]
I edited the readme, so the tests have been re-started. If the tests still pass (which is likely), then I will push to Dockerhub and quay.

**Pull request merged**
