### PR TITLE
add new NCBI-AMRFinderPlus v3.11.18 & database 2023-08-08.2

### PR DESCRIPTION
**Pull request by kapsakcj**
PR adds a new dockerfile for the latest version of NCBI-AMRFinderPlus v3.11.18 & database `2023-08-08.2`. Only minor edits to prior dockerfile

Changelog for new database: https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.11/2023-08-08.2/changelog.txt

Here's the overview of database changes:
```
- A major review and revision of macrolide / lincosamide / pleuromutilin / streptogramin class and subclass designations
- Additional phenotype curation of class/subclass and product name for some blaOXA genes and other beta-lactamases
- As usual, new named alleles for those genes whose allele nomenclature NCBI curates
```

Changes from previous dockerfile:

- upgraded versions on lines 3&4 for amrfinder version and database
- upgraded to ncbi-blast+ v2.14.0 from 2.13.0 on line 5

I propose we use the new docker image tag of `3.11.18-2023-08-08.2` and overwrite the `latest` tag

This will close issue #705 

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Review by erinyoung — APPROVED** [review]
Tests worked. All files and recommendations are present. 

Looks good!

I am going to 
- Approve this PR
- Merge this PR
- deploy to dockerhub and quay with the tag '3.11.18-2023-08-08.2'
- overwrite the latest tag

**Comment by erinyoung** [comment]
You can check the status of your image at https://github.com/StaPH-B/docker-builds/actions/runs/5835647413

Thank you for your contribution!

**Comment by erinyoung** [comment]
Just kidding! I didn't realize the tag and the directory were slightly different. 

You can check the status of your image at https://github.com/StaPH-B/docker-builds/actions/runs/5835671684

**Comment by kapsakcj** [comment]
Whoops, sorry! that was a typo in the path, it has an extra `.2` that should not be there.

Thank you for re-launching the workflow

**Pull request merged**
