### PR TITLE
adding version 1.19 for samtools/bcftools/htslib

### PR DESCRIPTION
**Pull request by erinyoung**
I did not do anything to the files from 1.18 other than copy them over and change the version arg.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
That issue probably isn't resolved. I have no experience with bcftools plugins and I am unsure how to check if anything is working.

**Comment by erinyoung** [comment]
@Kincekara , I THINK I'VE DONE IT!!! BCFTOOLS HAS ITS PLUGINS!

This is what I learned about bcftools plugins : 
1. They are part of the repo and there doesn't seem to be a way to download them after the fact
2. It appears that they work just fine if I copy them from the builder layer

**Review by Kincekara — APPROVED** [review]
Closes #755 
@erinyoung Thank you for fixing the issue. I will merge and deploy this PR!

**Comment by Kincekara** [comment]
Thank you for your contribution!
Please follow the links below to check the deployment status.
samtools: https://github.com/StaPH-B/docker-builds/actions/runs/7489855790
bcftools: https://github.com/StaPH-B/docker-builds/actions/runs/7489868134
htslib: https://github.com/StaPH-B/docker-builds/actions/runs/7489875948

**Pull request merged**
