### PR TITLE
adding bbtools versions 39.06

### PR DESCRIPTION
**Pull request by erinyoung**
There's a new version of bbtools!

I am unclear as to what is new in this version because I couldn't find the changenotes, but I'm sure it's something worthwhile.

I have adjusted the dockerfile for 39.01 substantially:
1. The base in now ubuntu:jammy
2. I removed most of the tools installed via apt-get
3. Samtools is now copied from staphb/samtools:1.19 (I can turn this to a builder stage instead)
4. I added a CMD line
5. Added /bbmap to PATH instead of using links

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by Kincekara** [comment]
Are samtools and sambamba required for any tools?

**Comment by erinyoung** [comment]
That's actually a good question. I can't remember. I included them because they were in the prior Dockerfiles, but they aren't in the installation instructions on the bbtools website.

@fanninpm , do you know why sambamba and samtools are normally included in the images for bbtools?

**Comment by fanninpm** [comment]
> @fanninpm , do you know why sambamba and samtools are normally included in the images for bbtools?

From `bbmap/docs/TableOfContents.txt`: "BBTools can also benefit from samtools, sambamba, pigz, pbzip2, lbzip2, bzip2, and bgzip, though none are required.  Specifically, .bam files can only be read or written if samtools or sambamba is in the path; .bz2 files require pbzip2, lbzip2, or bzip2; block-gzipping (often used for vcf files) requires bgzip in the path; and compression and decompression of .gz files is much faster with pigz in the path."

I suppose we probably don't need _both_ samtools _and_ sambamba.

**Comment by erinyoung** [comment]
@fanninpm Thank you!!!

I added pigz, pbzip2, lbzip2, bzip2, and bgzip back in.

**Comment by Kincekara** [comment]
@fanninpm Thank you! They are somehow required from my perspective. 
@erinyoung We can add a note to the dockerfile as a reminder.

**Comment by erinyoung** [comment]
@Kincekara , I've added in htslib for bgzip and the other dependencies through apt-get. 

Let me know if there's anything else I should add!

**Review by Kincekara — APPROVED** [review]
Looks good! I am merging this PR, and deploying the image.

**Comment by Kincekara** [comment]
Thank you for pulling all this together!
You can check the image deployment from here: https://github.com/StaPH-B/docker-builds/actions/runs/8365763655.

**Pull request merged**
