### PR TITLE
Mykrobe 0.13.0

### PR DESCRIPTION
**Pull request by erinyoung**
I only need Mykrobe for the mycobacteria, and there's a new version of mykrobe, so this is an image of the current version of mykrobe with the current databases, and none of those extra tools.

I did attempt to install mykrobe from source (see nonworking_Dockerfile) but ran into issues installing mccortex.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
Can't review today, but happy to do it sometime next week

**Comment by erinyoung** [comment]
Closes https://github.com/StaPH-B/docker-builds/issues/737

**Comment by kapsakcj** [comment]
Do you want to remove `mykrobe/0.13.0/nonworking_Dockerfile` from the PR if it's not functional? I'd prefer to not to include it, but understand if you'd like to revisit it later. Up to you.

I'm going to merge `main` back into this PR and resolve merge conflicts.

Apologies for the delay on reviewing this!

**Comment by erinyoung** [comment]
Thank you for resolving conflicts! I've removed the nonworking dockerfile.

**Review by kapsakcj — APPROVED** [review]
Thank you!

**Comment by kapsakcj** [comment]
deploy workflow here: https://github.com/StaPH-B/docker-builds/actions/runs/6947059423

I used `0.13.0` as the docker image tag.

Please delete your dev branch if you are finished with it

**Comment by erinyoung** [comment]
Thank you! Would you like me to make Dockerfiles for the other databases?

**Comment by kapsakcj** [comment]
I appreciate the offer, but that's OK. I can make one if the need arises. 

I haven't checked to see if any of those additional tools have had significant updates since I wrote the last dockerfile anyways

**Pull request merged**
