### PR TITLE
add shigapass 1.5.0

### PR DESCRIPTION
**Pull request by jvhagey**
This PR includes a Dockerfile for ShigaPass v1.5.0

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`) -- they are in the container as they come with the software
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
Thanks for the PR. Could you please add a step in the `app` stage to index the database so that users do not need to index prior to running the tool? Perhaps add in another `RUN` command after line 44 in the dockerfile

I see you have the `-u` option used in the test stage but it would be helpful to have that done independently in the `app` stage

**Comment by jvhagey** [comment]
Need to change permissions on the database folder for use. I will update shortly.

**Comment by jvhagey** [comment]
@kapsakcj ok, you had a good suggestion so I incorporated that and provided details in the readme. Hopefully, its clear.

**Comment by kapsakcj** [comment]
Thanks for making those changes! Will save users from doing an important step. And thank you for documenting that in the README 👍 

The tool-specific README looks great, thank you for putting that together. I made few small changes to this readme as well as the main `/README.md` table 

I tested with a handful of S flexneri, S sonnei, and S dysenteriae genomes and ShigaPass ran without issue and correctly predicted serotypes.

My only complaint is the....semi-colon....delimited output format, but that's not within the scope here

**Review by kapsakcj — APPROVED** [review]

**Comment by kapsakcj** [comment]
Deploy workflow is here: https://github.com/StaPH-B/docker-builds/actions/runs/10712655108

The docker image should be available on dockerhub and quay.io shortly. Thank you!

**Pull request merged**
