### PR TITLE
add dragonflye 1.0.14

### PR DESCRIPTION
**Pull request by kapsakcj**
~~_setting as a draft for now, needs further testing!_~~

Ready for review

This PR is for a new-to-this-repo tool, `dragonflye`. The dockerfile uses micromamba as the base image and relies upon the bioconda recipe for installation - there are a lot of dependencies and Robert does a great job of maintaining the recipe in bioconda so I'm not worried about long term support.

I have created empty repo's on dockerhub and quay in preparation for deployment

The test layer is quite thorough, if it takes too long to run, I will likely remove a few of the test commands to shorten the run time.

Also need to test with some real datasets before I'm ready to request review for this docker image.

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
GHAcitions workflow ook about ~22 minutes to build the docker image with test layer included but it passed.

I'm OK with keeping the thorough tests as long as this does not fail frequently in future builds

**Comment by kapsakcj** [comment]
I've tested this image on some real nanopore & ILMN data using `flye`, `miniasm`, and `raven` as assemblers and various other trimming & polishing options and everything seems to run as expected.

If we find issues later, we can always patch the dockerfile, but I'm comfortable with releasing the first iteration of this docker image

**Comment by erinyoung** [comment]
Looks like the tests passed

**Review by erinyoung — APPROVED** [review]
I have no changes to recommend. I'm going to 
- merge this PR
- push to dockerhub and quay (sounds like you've already created the quay repo)

**Pull request merged**
