### PR TITLE
adds dockerfile for pangolin 4.0.6 and pangolin-data 1.6

### PR DESCRIPTION
**Pull request by kapsakcj**
- [x] This comment contains a description of what is in the pull request.

also adds GH actions workflows for testing and deployment. also updates main README

Marked as a draft because I'm waiting for pangolin-assignment v1.6 to be released so that all dependencies/reference materials are in sync. Watching here: https://github.com/cov-lineages/pangolin-assignment/releases

- [x] Build your own docker image using a Dockerfile
  - [x] Directory structure should be name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. spades/3.12.0/Dockerfile)
  - [x] Includes the recommended LABELS
- [x] (Optional) Dockerfile is built with best practices and has been approved by a linter (such as https://hadolint.github.io/hadolint/)
- [x] Edit main README.md
- [x] Ensure tool is listed in Program_Licenses.md
- [x] Create a simple container-specific README.md in the same directory as the Dockerfile (i.e. spades/3.12.0/README.md)
- [x] Update GitHub actions workflow if needed
- [x] Any files required for building are located in the same directory as the Dockerfile (i.e. spades/3.12.0/my_spades_tests.sh)
- [x] Have successfully run the workflow "Test <program name> image" in your forked repository

### CODE REVIEW

**Comment by kapsakcj** [comment]
as of right now 2022-04-21 10am eastern, pangolin-assignment v1.3 is installed alongside everything else. Not a problem if you aren't using the assignment-cache with `--use-assignment-cache` option, but will be if you are since it's slightly out of date.

**Comment by fanninpm** [comment]
https://github.com/cov-lineages/pangolin-assignment/releases/tag/v1.6

**Comment by kapsakcj** [comment]
OK, pangolin-assignment updated to 1.6 be in sync with pangolin-data 1.6

Also updated constellations to 0.1.8

Anyone fancy a review?

**Review by erinyoung — APPROVED** [review]
Looks good to me.

Five is a lot of versions to keep track of. I pity the maintainers.

**Pull request merged**
