### PR TITLE
adds pbptyper 1.0.0

### PR DESCRIPTION
**Pull request by kapsakcj**
Just FYI @rpetit3 . You've made it super easy to install, test, and use this tool. So straight forward and seamless. Thank you!!! 🙌 

This PR adds:

- a dockerfile for a new tool, pbptyper, which is used for in silico Penicillin Binding Protein (PBP) typing for Streptococcus pneumoniae assemblies
- a README.md with basic usage and links to original GH repo
- updates main README.md and Program_Licensees.md

I've already created blank repos on dockerhub and quay in preparation for deployment. Also granted the quay robot admin permissions so that it can push the docker image to the quay repo.

https://hub.docker.com/r/staphb/pbptyper
https://quay.io/repository/staphb/pbptyper?tab=info

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Review by erinyoung — COMMENTED** [review]
I don't have any specific files to test with this, but it looks good, and it looks like the tests worked well.

**Review by erinyoung — APPROVED** [review]

**Comment by rpetit3** [comment]
Heads up this is available from Bioconda now, incase you want to simplify the conda install step

**Comment by kevinlibuit** [comment]
> Heads up this is available from Bioconda now, incase you want to simplify the conda install step

I like pulling from @rpetit3's repo for now as it includes that handy test data

**Comment by kapsakcj** [comment]
we'll likely switch it to pulling directly from bioconda for the next version; and additionally download the test data directly from the pbptyper GH repo.

This works for now though.

Kevin just deployed to dockerhub and quay

**Pull request merged**
