### PR TITLE
adds MIDAS 1.3.2

### PR DESCRIPTION
**Pull request by Kincekara**
Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Is Samtools intended to be part of this PR as well?

**Comment by erinyoung** [comment]
Right now I think everything looks good.

I'm just not sure that the Samtools Dockerfile was intended to be part of this PR.

**Comment by Kincekara** [comment]
Samtools shouldn't be part of this PR. I am trying to understand why it shows in commits.

**Comment by erinyoung** [comment]
Thanks for looking into that. It looks like the test works, so I'm going to 
1. merge this PR
2. deploy to dockerhub and quay to create the 'latest' and '1.3.2' tags.

Let me know if you run into any issues!

**Review by erinyoung — APPROVED** [review]

**Pull request merged**
