### PR TITLE
Kaptive version 2.0.8

### PR DESCRIPTION
**Pull request by erinyoung**
There's a new version of Kaptive!

I've actually been using the image created by @kapsakcj that's been in this PR : https://github.com/StaPH-B/docker-builds/pull/694 . In theory, I should just add to that PR, but there's a new version of Kaptive, so I've made a new branch and new PR.

My apologies for any confusion that may arise from this.

I made a few adjustments from @stitam and @kapsakcj 's files:
- updated the base image to jammy (I tried to update blast, too, but that broke things)
- added biopython version
- changed the tests
- moved the vibrio files

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
I think this PR probably 
Closes https://github.com/StaPH-B/docker-builds/issues/661
Closes https://github.com/StaPH-B/docker-builds/pull/694

**Comment by kapsakcj** [comment]
thanks for the PR, I will aim to get this reviewed by the end of next week. Currently in the middle of moving so time is limited

**Comment by erinyoung** [comment]
@kapsakcj , when you get time, it'd be awesome if you could review this.

**Comment by kapsakcj** [comment]
thanks for the reminder, I'll take a look as soon as I have time

**Comment by kapsakcj** [comment]
I took a look at the GHActions workflow log here, which was triggered ~6 days ago and ran through the tests (i.e. it didn't use the cache): https://github.com/StaPH-B/docker-builds/actions/runs/7836200690/job/21383295535

everything ran as expected so I'm good to merge and deploy. I'll close PR #694 

thank you for the PR and for your patience. Sorry it took me so long to review!

**Review by kapsakcj — APPROVED** [review]

**Comment by kapsakcj** [comment]
deploy workflow here, it should be up on dockerhub and quay shortly: https://github.com/StaPH-B/docker-builds/actions/runs/7881702560

**Pull request merged**
