### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by erinyoung**
- [X] This comment contains a description of what is in the pull request.

I'm updating docker-builds by going through the scripts that used to be used with travis and putting them into their corresponding dockerfile.

- [X] Build your own docker image using a Dockerfile
- [ X] Includes the recommended LABELS
- [X] (Optional) Dockerfile is built with best practices and has been approved by a linter (such as https://hadolint.github.io/hadolint/)
- [X] Ensure tool is listed in Program_Licenses.md
- [X] Ensure a simple container-specific README.md exists in the same directory as the Dockerfile (i.e. spades/3.12.0/README.md)
- [X] Update GitHub actions workflow if needed
- [X] Any files required for building are located in the same directory as the Dockerfile (i.e. spades/3.12.0/my_spades_tests.sh)
- [X] Have successfully run the workflow "Test <program name> image" in your forked repository

### CODE REVIEW

**Comment by erinyoung** [comment]
This repo, by the way, is rather large.

**Comment by erinyoung** [comment]
My apologies. I made this a little too large. I think I need to get this approved before I continue to work on it.

**Comment by erinyoung** [comment]
The goal of this update is to
1) improve the template of both the deploy and test yml files. This means I went through all the existing ones and updated them so that they would match. 
2) move the travis tests into the dockerfile - which really should be a separate PR (so only includes abricate at the moment)
3) update some directory changes such as making "VIBRANT" directory lowercase and moving seqyclean's adapter file (which meant I needed to update the dockerfile... )

**Comment by kapsakcj** [comment]
Is this PR ready for review? if not, can you please switch it to a draft state?

**Comment by erinyoung** [comment]
Yes. It's ready to review. 

I should have this one accepted before I go through more travis tests.

**Comment by erinyoung** [comment]
With https://github.com/StaPH-B/docker-builds/pull/355, many of these files are not needed anymore. I've changed it back to draft until that one is merged, and then I will adjust my files.

**Comment by erinyoung** [comment]
The test template and files are still here. I need to get something pushed that will auto-detect new dockerfiles. Once I do that, I'll set up this request for review.

**Pull request closed without merging**
