### PR TITLE
Adds pangolin 4.3.1 with new version of pangolin-data v1.26

### PR DESCRIPTION
**Pull request by kapsakcj**
Differences from previous dockerfile:

- upgraded base image to `mambaorg/micromamba:1.6.7`
- upgraded to pangolin-data v1.26 (from v1.25.1)
- removed `--analysis-mode usher` from all `pangolin` test commands as it's unnecessary (as per @AngieHinrichs)
- added `sed` line to pin the version of `pulp` used to 2.7.0. When I first built this image, the conda/mamba solver automatically upgraded to pulp 2.8.0 which resulted in a error when running Pangolin. The pangolin code seems to be incompatible with pulp 2.8.0.

explicit differences in code:

```
$ diff pangolin/4.3.1-pdata-1.25.1/Dockerfile pangolin/4.3.1-pdata-1.26/Dockerfile 
1c1
< FROM mambaorg/micromamba:1.5.6 as app
---
> FROM mambaorg/micromamba:1.5.7 as app
12c12
< ARG PANGOLIN_DATA_VER="v1.25.1"
---
> ARG PANGOLIN_DATA_VER="v1.26"
18c18
< LABEL base.image="mambaorg/micromamba:1.5.6"
---
> LABEL base.image="mambaorg/micromamba:1.5.7"
48a49
> # pin specific versions of usher, scorpio, pangolin-data, constellations, and pulp
53a55
>  sed -i "12 a\  - pulp=2.7.0" /pangolin/environment.yml && \
89c91
< RUN pangolin /pangolin/pangolin/test/test_seqs.fasta --analysis-mode usher -o /data/test_seqs-output-pusher && \
---
> RUN pangolin /pangolin/pangolin/test/test_seqs.fasta -o /data/test_seqs-output-pusher && \
99c101
< RUN pangolin /test-data/SRR13957123.consensus.fa --analysis-mode usher -o /test-data/SRR13957123-pusher && \
---
> RUN pangolin /test-data/SRR13957123.consensus.fa -o /test-data/SRR13957123-pusher && \
116c118
<  pangolin ON924087.1.genomic.fna --analysis-mode usher -o ON924087.1-usher && \
---
>  pangolin ON924087.1.genomic.fna -o ON924087.1-usher && \
127c129
<  pangolin OQ381818.1.genomic.fna --analysis-mode usher -o OQ381818.1-usher && \
---
>  pangolin OQ381818.1.genomic.fna -o OQ381818.1-usher && \
136c138
< pangolin OR177999.1.genomic.fna --analysis-mode usher -o OR177999.1-usher && \
---
> pangolin OR177999.1.genomic.fna -o OR177999.1-usher && \
145c147
< pangolin OR461132.1.genomic.fna --analysis-mode usher -o OR461132.1-usher && \
---
> pangolin OR461132.1.genomic.fna -o OR461132.1-usher && \
154c156
< pangolin OR598183.1.genomic.fna --analysis-mode usher -o OR598183.1-usher && \
---
> pangolin OR598183.1.genomic.fna -o OR598183.1-usher && \
165c167
< pangolin OR716684.1.genomic.fna --analysis-mode usher -o OR716684.1-usher && \
---
> pangolin OR716684.1.genomic.fna -o OR716684.1-usher && \
175c177
< pangolin PP189069.1.genomic.fna --analysis-mode usher -o PP189069.1-usher && \
---
> pangolin PP189069.1.genomic.fna -o PP189069.1-usher && \
```

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Review by erinyoung — APPROVED** [review]
I have no changes to recommend

**Comment by erinyoung** [comment]
I'm going to 
1. merge this PR
2. push to dockerhub and quay using the tag '4.3.1-pdata-1.26'
3. overwrite the 'latest' tag

**Comment by erinyoung** [comment]
Thank you for putting this together! (And my apologies for taking so long to review this!)

You can check the status of the deploy here : https://github.com/StaPH-B/docker-builds/actions/runs/8283786141

**Comment by kapsakcj** [comment]
No apologies necessary! Thank you for reviewing and deploying 🙌

**Pull request merged**
