### PR TITLE
adding assembly_snptyper version 0.1.1

### PR DESCRIPTION
**Pull request by erinyoung**
Hi! I've found this tool useful for identification of SNPs, especially those of the M1UK emm type (it's a GAS thing). 

This script isn't on bioconda, so there's no biocontainer.

The final uncompressed size is expected to be 371MB, which is mostly the reference fasta file.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Closes https://github.com/StaPH-B/docker-builds/issues/939

**Comment by kapsakcj** [comment]
Looks like everything was installed correctly and the tests passed. Here's some snippets from the automated build & test:
```
#13 1.153 Building wheels for collected packages: assembly-snptyper
#13 1.154   Building wheel for assembly-snptyper (setup.py): started
#13 1.310   Building wheel for assembly-snptyper (setup.py): finished with status 'done'
#13 1.311   Created wheel for assembly-snptyper: filename=assembly_snptyper-0.1.1-py3-none-any.whl size=6349 sha256=c92097f5f9b1fa81eb913398faffc17e22e913f928d8e2cb39e01e8766de1818
#13 1.311   Stored in directory: /tmp/pip-ephem-wheel-cache-0pvk9x56/wheels/65/c1/3e/ee22e326693abea96f97a3227c210ab0724ea9c7de841989c0
#13 1.313 Successfully built assembly-snptyper
#13 1.316 Installing collected packages: assembly-snptyper
#13 1.327 Successfully installed assembly-snptyper-0.1.1

...


#15 [test 1/4] RUN assembly_snptyper --help &&     assembly_snptyper --version
#15 0.393 usage: assembly_snptyper [-h] --vcf VCF --reference REFERENCE --list_input
#15 0.393                          LIST_INPUT [-p PROCESSES] [-v] [--version]
#15 0.393 
#15 0.393 options:
#15 0.393   -h, --help            show this help message and exit
#15 0.393   --vcf VCF             VCF file with variants that determine the type
#15 0.393                         (default: None)
#15 0.393   --reference REFERENCE
#15 0.393                         Reference genome (default: None)
#15 0.393   --list_input LIST_INPUT
#15 0.393                         List of input assemblies (default: None)
#15 0.393   -p PROCESSES, --processes PROCESSES
#15 0.393                         Number of processes passed to multiprocessing
#15 0.393                         (default: 1)
#15 0.393   -v, --verbose         Verbose output, can be used multiple times. 0 =
#15 0.393                         warning, 1 = info, 2 = debug (default: 0)
#15 0.393   --version             show program's version number and exit
#15 0.767 assembly_snptyper 0.1.1

...

#17 [test 3/4] RUN wget -q https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/475/035/GCA_900475035.1_41965_F01/GCA_900475035.1_41965_F01_genomic.fna.gz &&     gunzip GCA_900475035.1_41965_F01_genomic.fna.gz &&     ls *genomic.fna > fastas.txt &&     assembly_snptyper --list_input fastas.txt -p 4 --reference /assembly_snptyper/data/MGAS5005.fa --vcf /assembly_snptyper/data/M1UK.vcf > m1uk.txt &&     head m1uk.txt
#17 1.734 sample	matching_variants	wt_variants	variants_in_scheme	variants_missing	variants_multiple_cov
#17 1.734 GCA_900475035.1_41965_F01_genomic	0	23	27	4	0
```

and finally the bash script tests completed successfully `bash tests/test_e2e.sh` as far as I can tell. Looks like it tries to re-install `assembly-snptyper` using `pip`, which is unnecessary since everything is already installed.

**Review by kapsakcj — APPROVED** [review]
Thanks for this PR, I'll merge and deploy now

**Comment by kapsakcj** [comment]
deploy workflow here. I used the image name and tag `staphb/assembly_snptyper:0.1.1`

https://github.com/StaPH-B/docker-builds/actions/runs/11109330332

**Comment by erinyoung** [comment]
Thank you!

**Pull request merged**
