### PR TITLE
Updated panaroo from 1.2.10 to 1.3.4

### PR DESCRIPTION
**Pull request by evagunawan**
Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

I also removed the unnecessary add ons in the yml file that were not needed for panaroo to function.

### CODE REVIEW

**Comment by erinyoung** [comment]
Did you intend to have both tbprofiler and panaroo Dockerfiles in this PR? (I'm just double checking)

**Comment by erinyoung** [comment]
Closes https://github.com/StaPH-B/docker-builds/issues/739 and https://github.com/StaPH-B/docker-builds/issues/451

**Comment by erinyoung** [comment]
Thank you for your contribution!

I have made some changes to this PR and would like your approval before I merge these files into master.

- I removed the panaroo test files that you uploaded. Instead, I adjusted the Dockerfile so that the files uploaded in the prior version are downloaded with wget. I think this will improve future updates so that we don't have to keep track of so many files.
- I added tb-profiler to the main README.md (prior there was only panaraoo)
- I added the tb-profiler database version back into the Dockerfile (I guess not all commits come with working database files)
- I simplified the panaroo Dockerfile so that it no longer uses the environmental.yml file. The file just seemed to follow the defaults on conda.

**Comment by evagunawan** [comment]
Hi Dr. Young!
All of that is completely fine with me. I'm going to go through your changes to the files so that way I learn a bit more from them.

Thank you!

**Review by erinyoung — APPROVED** [review]

**Pull request merged**
