### PR TITLE
add recipe for shovill-se

### PR DESCRIPTION
**Pull request by rpetit3**
This PR adds Shovill-SE (haha the existing `shovill` Dockerfile made it super easy) which is a [fork](https://github.com/rpetit3/shovill) I maintain to support single-end reads. With `shovill-se` the `--r1` and `--r2` parameters have been replaced by `--se`.,

There's an open PR over at Shovill (https://github.com/tseemann/shovill/pull/105) and I've also gotten the blessing from Torsten and Anders (haha albeit lost to Slack message limits) for the [Bioconda release](https://bioconda.github.io/recipes/shovill-se/README.html).

Example
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data shovill-se:1.1.0 shovill-se
SYNOPSIS
  De novo assembly pipeline for Illumina single-end reads
USAGE
  shovill-se [options] --outdir DIR --se SE.fq.gz
GENERAL
  --help          This help
  --version       Print version and exit
  --check         Check dependencies are installed
INPUT
  --se|single XXX Single-end reads (default: '')
  --depth N       Sub-sample --R1/--R2 to this depth. Disable with --depth 0 (default: 150)
  --gsize XXX     Estimated genome size eg. 3.2M <blank=AUTODETECT> (default: '')
OUTPUT
  --outdir XXX    Output folder (default: '')
  --force         Force overwite of existing output folder (default: OFF)
  --minlen N      Minimum contig length <0=AUTO> (default: 0)
  --mincov n.nn   Minimum contig coverage <0=AUTO> (default: 2)
  --namefmt XXX   Format of contig FASTA IDs in 'printf' style (default: 'contig%05d')
  --keepfiles     Keep intermediate files (default: OFF)
RESOURCES
  --tmpdir XXX    Fast temporary directory (default: '')
  --cpus N        Number of CPUs to use (0=ALL) (default: 8)
  --ram n.nn      Try to keep RAM usage below this many GB (default: 16)
ASSEMBLER
  --assembler XXX Assembler: skesa megahit spades velvet (default: 'spades')
  --opts XXX      Extra assembler options in quotes eg. spades: '--sc' ... (default: '')
  --kmers XXX     K-mers to use <blank=AUTO> (default: '')
MODULES
  --trim          Enable adaptor trimming (default: OFF)
  --nocorr        Disable post-assembly correction (default: OFF)
HOMEPAGE
  https://github.com/tseemann/shovill - Torsten Seemann
```

### CODE REVIEW

**Comment by kapsakcj** [comment]
awesome! I'll merge and build on dockerhub and quay.

I can add a row in the table on the README for this afterwards

**Comment by rpetit3** [comment]
Crap I knew I forgot something, apologies!

**Comment by kapsakcj** [comment]
s'all good :)

**Comment by kapsakcj** [comment]
we should probably have a checklist or PR template to help with remembering all the things

**Pull request merged**
