### PR TITLE
adding flye version 2.9.5

### PR DESCRIPTION
**Pull request by erinyoung**
There's a new version of flye!

I think this may be a minor update? According the to the [release notes](https://github.com/mikolmogorov/Flye/releases/tag/2.9.5) python2 support was dropped.

I think this means a few functions have been rewritten, so this may behave differently than 2.9.4.

I just copied the file from 2.9.4 and updated the software version arg.

```
 $ diff flye/2.9.4/Dockerfile flye/2.9.5/Dockerfile 
2c2
< ARG FLYE_VER="2.9.4"
---
> ARG FLYE_VER="2.9.5"
```

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by Kincekara** [comment]
Bioconda image is less than 100 MB while ours is ~250MB. I think it may be good to try a staged build or mamba for this.

**Comment by kapsakcj** [comment]
If we want to reduce the size, I think a staged build will be best since the compilation stuff `gcc g++ make` etc. things likely won't be needed at runtime

I can work on this at some point in the near future if you're OK with me pushing commits here

**Comment by erinyoung** [comment]
I'm okay with having commits pushed here. I'm unsure when I'll have time to work on this.

**Comment by erinyoung** [comment]
TA DA!

I have added a builder stage, and everything appears to run as normal. Now the image is MUCH smaller.

When built to app: 191 MB, flye's image on biocontainers is 238 MB.

```
$ docker image ls
REPOSITORY                   TAG                     IMAGE ID       CREATED          SIZE
flye                         app                     67b2b2e89238   4 minutes ago    191MB
quay.io/biocontainers/flye   2.9.5--py39hdf45acc_1   998863804506   8 weeks ago      238MB
```

**Comment by erinyoung** [comment]
Also, I realized this image was missing a CMD line, so I added it.

**Review by Kincekara — APPROVED** [review]

**Comment by Kincekara** [comment]
Looks great! Thank you for putting all these together and making the image much smaller.

**Comment by Kincekara** [comment]
Deploy link: https://github.com/StaPH-B/docker-builds/actions/runs/11581356184

**Comment by Kincekara** [comment]
76.68 MB on dockerhub. Great improvement!  👏

**Pull request merged**
