### PR TITLE
Moving all dockerfiles into a "build-files" directory

### PR DESCRIPTION
**Pull request by erinyoung**
This is updating the main file structure for this repository.

After a little consideration, I think updating the file structure is required BEFORE updating the github actions looking for new dockerfiles - otherwise each Dockerfile would be built.

### CODE REVIEW

**Comment by erinyoung** [comment]
This PR is very large, but only because so many files were renamed.

Notable changes:
1. The github actions that operate through cron jobs now will only run if connect to StaPH-B/docker-builds (not on any forks)
2. All bioinformatic tools are in the `recipes` directory - so 99% of the changes are renaming files
3. parsnp/README.md was deleted as this file is found in each version subdirectory
4. artic-ncov2019-medaka and artic-ncov2019-nanopolish now have a 1.1.0 subdirectory and their Dockerfile has been moved into that subdirectory
5. `chmod -x` was run on all Dockerfiles to remove all executability

**Comment by Kincekara** [comment]
@erinyoung where are the dockerfile templates?

**Comment by erinyoung** [comment]
Oh no! I didn't think I did anything to them! Did I accidentally delete them?

**Comment by Kincekara** [comment]
I couldn't see them. In any case, it may be good to have those templates outside the recipes folder.

**Comment by erinyoung** [comment]
The subdirectory is now 'build-files'!

**Review by Kincekara — APPROVED** [review]

**Pull request merged**
