### PR TITLE
Getting Trycycler up to date

### PR DESCRIPTION
**Pull request by erinyoung**

### CODE REVIEW

**Comment by kapsakcj** [comment]
Could you please adjust the sub-directory name `/trycycler/0.5.5` to match the version of Trycycler? I believe it should be `0.5.0` which is the most current release

**Comment by erinyoung** [comment]
Sorry! That was a typo. Thank you for catching it.

**Comment by kapsakcj** [comment]
No worries!

OK if I push a commit? `${MINIASM_VER}` needs to be in the miniasm install steps since the variables are lower case at the moment and thus the image doesn't build.

**Comment by erinyoung** [comment]
This error suggests that I actually just uploaded one of my rough drafts instead of the working file. Hang on a second. I want to be sure that this is the one that builds.

**Comment by erinyoung** [comment]
Alright, this one builds "for me". Sorry about the typos!

**Comment by kapsakcj** [comment]
builds for me too 👍 Thanks for that change.

How does it run? Does it produce the outputs that you would expect?

Let me know when you are ready to merge and I can build on dockerhub & quay

**Comment by erinyoung** [comment]
I think it runs like it should. I creates assemblies just fine. (I'm still working on the later steps)

**Comment by kapsakcj** [comment]
I got the dockerfile to build, but received an error when pulling up help options. I was able to resolve the error by installing the python package `pillow`. Looks like Ryan W. added this to the `setup.py` AFTER the v0.5.0 release, so we'll need to install manually in order to get things to run properly on v0.5.0

**Comment by kapsakcj** [comment]
Also got this error, complaining about `ape` R package:
```
Checking required software:
      Mash: v2.3
         R: v3.4.4
       ape: v?

Error: unable to run R - make sure that R is correctly installed, then try again.
```

**Comment by kapsakcj** [comment]
👎 boo, looks like we'll have to upgrade the version of R in order to install `phangorn` package:
```
> library(phangorn)
Error in library(phangorn) : there is no package called 'phangorn'
> install.packages("phangorn")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
Warning message:
package 'phangorn' is not available (for R version 3.4.4)
```

Going to try out `ubuntu:hirsute` as a base image to see if that will bring R to a version compatible with `phangorn`

**Comment by kapsakcj** [comment]
OK, I made another commit with some changes, and re-built the docker image. I then ran through the tutorial with the "Great Dataset" here https://github.com/rrwick/Trycycler/wiki/Great-dataset-analysis

All commands worked as expected and output files look fine.

The only odd thing was that when running the following command, `trycycler` couldn't determine the versions for `ape` and `phangorn` likely because of some weirdness with R 4.x.x. 
```
$ trycycler cluster --reads reads.fastq.gz --assemblies assemblies/*.fasta --out_dir trycycler

Starting Trycycler clustering (2021-09-13 23:58:38)
    Trycycler cluster is a tool for clustering the contigs from multiple different assemblies (e.g. from different
assemblers) into highly-similar groups.

Input assemblies:
  A: assemblies/assembly_00.fasta (1,051,794 bp, 2 contigs)
  B: assemblies/assembly_01.fasta (1,051,803 bp, 2 contigs)
  C: assemblies/assembly_02.fasta (1,051,824 bp, 2 contigs)
  D: assemblies/assembly_03.fasta (1,051,822 bp, 2 contigs)
  E: assemblies/assembly_04.fasta (1,051,828 bp, 2 contigs)
  F: assemblies/assembly_05.fasta (1,051,924 bp, 2 contigs)
  G: assemblies/assembly_06.fasta (1,051,927 bp, 2 contigs)
  H: assemblies/assembly_07.fasta (1,051,944 bp, 2 contigs)
  I: assemblies/assembly_08.fasta (1,051,915 bp, 2 contigs)
  J: assemblies/assembly_09.fasta (1,051,927 bp, 2 contigs)

Creating output directory: trycycler

Input reads: reads.fastq.gz
  43,662 reads (210,403,674 bp)
  N50 = 7,768 bp

Checking required software:
      Mash: v2.3
         R: v4.0.4
       ape: v?
  phangorn: v?
```
It continued to run after this part, I just noticed the `v?`'s and thought it was a little odd.

**Comment by erinyoung** [comment]
I thought you had forgotten about this, and it looks like I never pushed my latest commits. 

I just compared what I've been using on quay with your commits, and they basically look the same. I, however, get the versions of the sub tools : 

```
Checking required software:
      Mash: v2.3
         R: v4.1.0
       ape: v5.5
  phangorn: v2.7.1

```

I'm not really sure why that is.

**Comment by kapsakcj** [comment]
Ah sorry about pushing the commit, I was just trying to get the last version of the dockerfile running. Thanks for correcting it. I'll test it out.

**Comment by kapsakcj** [comment]
Got this warning while building the docker image (with your most recent commit):
```
Warning message:
package 'phangorn' is not available (for R version 3.4.4)
```
and then an error when running trycycler:
```
$ trycycler cluster --reads reads.fastq.gz --assemblies assemblies/*.fasta --out_dir trycycler -t 8

Starting Trycycler clustering (2021-09-14 14:18:52)
    Trycycler cluster is a tool for clustering the contigs from multiple different assemblies (e.g. from different
assemblers) into highly-similar groups.

Input assemblies:
  A: assemblies/assembly_00.fasta (1,051,794 bp, 2 contigs)
  B: assemblies/assembly_01.fasta (1,051,803 bp, 2 contigs)
  C: assemblies/assembly_02.fasta (1,051,824 bp, 2 contigs)
  D: assemblies/assembly_03.fasta (1,051,822 bp, 2 contigs)
  E: assemblies/assembly_04.fasta (1,051,828 bp, 2 contigs)
  F: assemblies/assembly_05.fasta (1,051,924 bp, 2 contigs)
  G: assemblies/assembly_06.fasta (1,051,927 bp, 2 contigs)
  H: assemblies/assembly_07.fasta (1,051,944 bp, 2 contigs)
  I: assemblies/assembly_08.fasta (1,051,915 bp, 2 contigs)
  J: assemblies/assembly_09.fasta (1,051,927 bp, 2 contigs)

Creating output directory: trycycler

Input reads: reads.fastq.gz
  43,662 reads (210,403,674 bp)
  N50 = 7,768 bp

Checking required software:
      Mash: v2.3
         R: v3.4.4
       ape: v?

Error: unable to run R - make sure that R is correctly installed, then try again.
```

What docker image are you using from Quay? Is it this biocontainer? https://quay.io/repository/biocontainers/trycycler?tab=tags

**Comment by erinyoung** [comment]
This one : https://quay.io/repository/uphl/trycycler

**Comment by kapsakcj** [comment]
thanks for the link. How did you get trycycler running in that container? 

I'm getting the same errors when trying it out. Am I doing something wrong? I copied the `trycycler cluster` command directly from the wiki https://github.com/rrwick/Trycycler/wiki/Great-dataset-analysis
```
$ docker run --rm -v $PWD:/data -u $(id -u):$(id -g) -ti quay.io/uphl/trycycler:latest
Unable to find image 'quay.io/uphl/trycycler:latest' locally
latest: Pulling from uphl/trycycler
e4ca327ec0e7: Already exists
f985825f3ac3: Already exists
75d601ccd2a5: Already exists
4c6d818a2b27: Already exists
5e2ccb2784df: Already exists
5f4ccbf5a3fb: Already exists
2eaf485cf616: Pull complete
Digest: sha256:02f9801393e6e5a059bd94dff13bcadd52d69e4b58694dc3303d59137d0313c8
Status: Downloaded newer image for quay.io/uphl/trycycler:latest
groups: cannot find name for group ID 1002
I have no name!@f68032afcc2d:/data$ trycycler cluster --reads reads.fastq.gz --assemblies assemblies/*.fasta --out_dir trycycler -t 8

Starting Trycycler clustering (2021-09-14 15:50:47)
    Trycycler cluster is a tool for clustering the contigs from multiple different assemblies (e.g. from different
assemblers) into highly-similar groups.

Input assemblies:
  A: assemblies/assembly_00.fasta (1,051,794 bp, 2 contigs)
  B: assemblies/assembly_01.fasta (1,051,803 bp, 2 contigs)
  C: assemblies/assembly_02.fasta (1,051,824 bp, 2 contigs)
  D: assemblies/assembly_03.fasta (1,051,822 bp, 2 contigs)
  E: assemblies/assembly_04.fasta (1,051,828 bp, 2 contigs)
  F: assemblies/assembly_05.fasta (1,051,924 bp, 2 contigs)
  G: assemblies/assembly_06.fasta (1,051,927 bp, 2 contigs)
  H: assemblies/assembly_07.fasta (1,051,944 bp, 2 contigs)
  I: assemblies/assembly_08.fasta (1,051,915 bp, 2 contigs)
  J: assemblies/assembly_09.fasta (1,051,927 bp, 2 contigs)

Creating output directory: trycycler

Input reads: reads.fastq.gz
  43,662 reads (210,403,674 bp)
  N50 = 7,768 bp

Checking required software:
      Mash: v2.3
         R: v3.4.4
       ape: v?

Error: unable to run R - make sure that R is correctly installed, then try again.
```

**Comment by erinyoung** [comment]
That's... awesome...

Maybe it's because I pull these and use them in singularity?

**Comment by erinyoung** [comment]
I'm testing this new version of ubuntu on my end. 

Here's hoping the R package version numbers just fix themselves...

Although, is this really a bug if the package installs and works properly?

**Comment by kapsakcj** [comment]
Oh fun. So I tried with Singularity instead of Docker and got the same error. 

Do you have R 4.1, `ape`, `phangorn` installed locally? Perhaps R & R packages are getting into the container by the automatic mounting your $HOME directory? (do you use the `singularity exec --no-home` option?)

error:
```
$ singularity build uphl-trycycler.sif docker://quay.io/uphl/trycycler:latest
INFO:    Starting build...
Getting image source signatures
Copying blob e4ca327ec0e7 done
Copying blob f985825f3ac3 done
Copying blob 75d601ccd2a5 done
Copying blob 4c6d818a2b27 done
Copying blob 5e2ccb2784df done
Copying blob 5f4ccbf5a3fb done
Copying blob 2eaf485cf616 done
Copying config d1bafb40c8 done
Writing manifest to image destination
Storing signatures
2021/09/14 16:16:27  info unpack layer: sha256:e4ca327ec0e73c737201b7a6d7b2df779a3ccf34fe9cf1b0c031e767f6464240
2021/09/14 16:16:28  info unpack layer: sha256:f985825f3ac350155b7b856c0d4d041eb1fb6fab468c1832a4c8b99868849bd2
2021/09/14 16:16:38  info unpack layer: sha256:75d601ccd2a54bd8e7a96357926d0382b4a6a53c87a1759edb5c45f55469d919
2021/09/14 16:16:38  info unpack layer: sha256:4c6d818a2b277482e624e64eff295d11a0669910ea1eb497e05e8e59f4beaa81
2021/09/14 16:16:38  info unpack layer: sha256:5e2ccb2784df50eb629b055d39a5802993de8be41146b44a5362b08b592aec85
2021/09/14 16:16:38  info unpack layer: sha256:5f4ccbf5a3fb58aaaa6db106ffc6234796dcdca95a63ebea808af39e09260999
2021/09/14 16:16:38  info unpack layer: sha256:2eaf485cf616a9d7415f8d96368a13225fddc0e854766c7b5f53564fd1ddaf24
INFO:    Creating SIF file...
INFO:    Build complete: uphl-trycycler.sif

$ singularity shell --no-home -B $PWD:/data uphl-trycycler.sif

Singularity> trycycler cluster --reads reads.fastq.gz --assemblies assemblies/*.fasta --out_dir trycycler

Starting Trycycler clustering (2021-09-14 16:18:52)
    Trycycler cluster is a tool for clustering the contigs from multiple different assemblies (e.g. from different
assemblers) into highly-similar groups.

Input assemblies:
  A: assemblies/assembly_00.fasta (1,051,794 bp, 2 contigs)
  B: assemblies/assembly_01.fasta (1,051,803 bp, 2 contigs)
  C: assemblies/assembly_02.fasta (1,051,824 bp, 2 contigs)
  D: assemblies/assembly_03.fasta (1,051,822 bp, 2 contigs)
  E: assemblies/assembly_04.fasta (1,051,828 bp, 2 contigs)
  F: assemblies/assembly_05.fasta (1,051,924 bp, 2 contigs)
  G: assemblies/assembly_06.fasta (1,051,927 bp, 2 contigs)
  H: assemblies/assembly_07.fasta (1,051,944 bp, 2 contigs)
  I: assemblies/assembly_08.fasta (1,051,915 bp, 2 contigs)
  J: assemblies/assembly_09.fasta (1,051,927 bp, 2 contigs)

Output directory already exists: trycycler

Input reads: reads.fastq.gz
  43,662 reads (210,403,674 bp)
  N50 = 7,768 bp

Checking required software:
      Mash: v2.3
         R: v3.4.4
       ape: v?

Error: unable to run R - make sure that R is correctly installed, then try again.
```

I wouldn't necessarily call this a bug, I just think that the container doesn't have the correct dependencies installed

**Comment by erinyoung** [comment]
That might be it. I do have ape and other R packages installed locally.

**Comment by erinyoung** [comment]
Alright. This time I've got this in the build log:

```
installing to /usr/local/lib/R/site-library/00LOCK-ape/00new/ape/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ape)
* installing *source* package 'phangorn' ...
** package 'phangorn' successfully unpacked and MD5 sums checked
** using staged installation
** libs
```

I tried adding  r-base-dev to the installation (because of comments I read on stackoverflow and such), but the versions are still 
```
Checking required software:
      Mash: v2.3
         R: v4.0.4
       ape: v?
  phangorn: v?
```

According to Trycycler.

When I go into the container to look for these packages:
```
Singularity> 'R' '--quiet' '-e' 'packageVersion("ape")'
> packageVersion("ape")
[1] '5.5'
>
>
Singularity> 'R' '--quiet' '-e' 'packageVersion("phangorn")'
> packageVersion("phangorn")
[1] '2.7.1'
>
>
```
They are there. So I think the issue is with how Trycyler is parsing these.

This is how Trycycler is getting the version number (from https://github.com/rrwick/Trycycler/blob/main/trycycler/software.py):

https://github.com/rrwick/Trycycler/blob/98cc48164035b29e516e0c7bc3d9844820933129/trycycler/software.py#L83-L151

Is there something wrong with how these are getting parsed?

**Comment by kapsakcj** [comment]
OK I think this docker image is ready to go live.

I re-built the image with your most recent commit (upgrade to ubuntu:hirsute) and re-ran the "Great demo dataset" through the paces. All parts of Trycycler ran as expected and outputs matched what Ryan has listed in the tutorial.

The one quirk is that the r-package versions still show up oddly in the output of `trycycler cluster ...`, and yes I think it has to do with how trycycler parses those versions. We could raise an issue on Trycycler to let Ryan know.
```
Checking required software:
      Mash: v2.3
         R: v4.0.4
       ape: v?
  phangorn: v?
```

Have you had a chance to test on your side? OK if we merge and push the image to dockerhub and quay?

**Comment by erinyoung** [comment]
I tried some changes on my end that didn't work and then I had to work on something else.

If it works for your tests, I'll accept that. I vote we push the image!

 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Comment by kapsakcj** [comment]
OK. Sounds good. If we encounter any issues in the future we can tweak the dockerfile and re-build the image, but it seems stable in my hands

I'll merge and push to dockerhub and quay 👍 

Thanks for the PR! 🚀

**Pull request merged**
