### PR TITLE
Lyveset updates

### PR DESCRIPTION
**Pull request by erikwolfsohn**
Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [*tool version unchanged] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [*no update needed] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

Updated Dockerfile to restore functionality w/eutils & improve speed of apt package retrieval. Test layer runs Lyve-SET's built in test script.

### CODE REVIEW

**Comment by kapsakcj** [comment]
Hey Erik, nice work on this so far. You picked a challenging one!

It took quite a while to run the github actions workflow for building the docker image and I'm surprised it didn't hit a time ceiling. This is quite an involved installation, so no worries here. As long as we're able to build the docker image successfully this is OK.

Here are some suggested changes:

- [ ] Change line 4 to `LABEL dockerfile.version="4"`. This is a Curtis-specific LABEL that helps keep track of how many times we iterate upon a single dockerfile for a given version of a tool. More explanation [here](https://github.com/StaPH-B/docker-builds/issues/118)
- [ ] Change lines 10 & 11 to remove the `1` after maintainer. This will allow the LABEL checking step in the GHActions workflow to pass
```Dockerfile
LABEL maintainer="Kelsey Florek"
LABEL maintainer.email="kelsey.florek@slh.wisc.edu"
```

- [ ] Change line 13 to list my gmail instead of old cdc email `kapsakcj@gmail.com`
- [ ] Change line 27 to include `RUN apt-get install -y --no-install-recommends \` as an option. We have found this helps reduce the final image size. **There is a small chance that this will break things, so if that is the case, ignore this suggestion**
- [ ] Consolidate lines 52-55 so that all `apt-get` commands are in a single RUN layer. Like so:
```Dockerfile
    smalt && \
    apt-get clean && apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*
```
- [ ] Rename the tool-specific README.md to `/lyveset/1.1.4f/README.md` so the markdown is automatically rendered.
- [ ] Update the tool-specific README.md to have more information. We have [a template readme.md here to help get started](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) and you can view other tools for examples, [like SeqSero2's](https://github.com/StaPH-B/docker-builds/blob/master/seqsero2/1.2.1/README.md) . You can keep it simple, no need to deep dive into LYVE-set, just basic usage and links that are helpful for new users.

**Comment by erikwolfsohn** [comment]
Thanks again for all of your help with getting this image to build!

I updated the Dockerfile & README.md with most of the changes you suggested. `--no-install-recommends` did end up breaking something, so I had to remove that.

**Comment by erinyoung** [comment]
> Thanks again for all of your help with getting this image to build!
> 
> I updated the Dockerfile & README.md with most of the changes you suggested. `--no-install-recommends` did end up breaking something, so I had to remove that.

It's common to need to install ca-certificates when using `--no-install-recommends`, or did you run into a different error?

**Comment by kapsakcj** [comment]
OK, thanks for making those changes. I have just a few more recommendations (we're almost to the finish line, I promise)

- For lines 69 to 72, please replace `1.1.4f` with `${LYVESET_VER}`
- Some where near the top, between line 1 and 3, set a new ARG variable `ARG LYVESET_VER="1.1.4f"`. This way if a new version of lyve-set is released, it will be simple to upgrade to the next version
- Consolidate lines 25-27 so they occur in the same `RUN` layer. [Docker's offical docs](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get) state that `apt-get update` and `apt-get install` commands should always be done in the same layer to avoid issues


I can see the tests have all passed now, so the hard part is done 🎉

**Comment by erikwolfsohn** [comment]
> It's common to need to install ca-certificates when using `--no-install-recommends`, or did you run into a different error?

It causes dependency issues further down when installing the Perl module "Bio::FeatureIO" - I'm not positive on this but my guess is one of the recommended packages for libxml-simple-perl are required by the XML modules that are in turn required by FeatureIO. I attached the cpanm error log if you want to take a look. 
[cpanm_log.txt](https://github.com/StaPH-B/docker-builds/files/10703149/cpanm_log.txt)

**Comment by erinyoung** [comment]
I'd like to merge this PR. 

@kapsakcj , do you have other recommendations?

**Review by erinyoung — APPROVED** [review]

**Comment by kapsakcj** [comment]
Nope, looks good to me. Thanks for making those changes, Erik!

**Review by kapsakcj — APPROVED** [review]

**Comment by erinyoung** [comment]
Perfect!

Then I'll 
- merge this PR
- deploy to dockerhub and quay with the '1.1.4f' tag
- overwrite the 'latest' tag

**Comment by erinyoung** [comment]
You can watch progress here : https://github.com/StaPH-B/docker-builds/actions/runs/4188715991

**Pull request merged**
