### PR TITLE
Add Vadr 1.4 dockerfile

### PR DESCRIPTION
**Pull request by kapsakcj**

### CODE REVIEW

**Comment by kapsakcj** [comment]
Passed VADR test script `do-install-tests-local.sh`
<details>

```
$ /opt/vadr/vadr/testfiles/do-install-tests-local.sh >do-install-tests-local.log 2>&1
$ tail do-install-tests-local.log
# List of executed commands saved in:                  vt-d5-local.vadr.cmd
# List and description of all output files saved in:   vt-d5-local.vadr.list
#
# All output files created in directory ./vt-d5-local/
#
# Elapsed time:  00:01:15.22
#                hh:mm:ss
#
[ok]
Success: all tests passed [do-install-tests-local.sh]
```
</details>


Passed VADR test script `do-all-tests.sh`:
<details>

```
$ /opt/vadr/vadr/testfiles/do-all-tests.sh >do-all-tests.log 2>&1
$ tail do-all-tests.log
# List and description of all output files saved in:   vt-iss47-productparantheses.vadr.list
#
# All output files created in directory ./vt-iss47-productparantheses/
#
# Elapsed time:  00:00:00.44
#                hh:mm:ss
#
[ok]
Success: all tests passed [do-issue-tests.sh]
Success: all tests passed [do-all-tests.sh]
```
</details>

Tested fine with an Alpha/B.1.1.7 from Utah:
<details>

```
$ v-annotate.pl -f --noseqnamemax --split --cpu 2 --glsearch  -s -r --nomisc --mkey sarscov2 --lowsim5seq 6 --lowsim3seq 6 --alt_fail lowscore,insertnn,deletinn ../../testdata/sarscov2/SRR13957 123.B.1.1.7.consensus.VADR-trimmed.fasta alpha-B.1.1.7-test
# v-annotate.pl :: classify and annotate sequences using a model library
# VADR 1.4 (Dec 2021)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# date:              Wed Dec 22 18:56:36 2021
# $VADRBIOEASELDIR:  /opt/vadr/Bio-Easel
# $VADRBLASTDIR:     /opt/vadr/ncbi-blast/bin
# $VADREASELDIR:     /opt/vadr/infernal/binaries
# $VADRFASTADIR:     /opt/vadr/fasta/bin
# $VADRINFERNALDIR:  /opt/vadr/infernal/binaries
# $VADRMODELDIR:     /opt/vadr/vadr-models
# $VADRSCRIPTSDIR:   /opt/vadr/vadr
#
# sequence file:                                                                  ../../testdata/sarscov2/SRR13957123.B.1.1.7.conse nsus.VADR-trimmed.fasta
# output directory:                                                               alpha-B.1.1.7-test
# force directory overwrite:                                                      yes [-f]
# specify that alert codes in <s> cause FAILure:                                  lowscore,insertnn,deletinn [--alt_fail]
# .cm, .minfo, blastn .fa files in $VADRMODELDIR start with key <s>, not 'vadr':  sarscov2 [--mkey]
# in feature table for failed seqs, never change feature type to misc_feature:    yes [--nomisc]
# lowsim5s/LOW_SIMILARITY_START minimum length is <n>:                            6 [--lowsim5seq]
# lowsim3s/LOW_SIMILARITY_END minimum length is <n>:                              6 [--lowsim3seq]
# align with glsearch from the FASTA package, not to a cm with cmalign:           yes [--glsearch]
# use top-scoring HSP from blastn to seed the alignment:                          yes [-s]
# replace stretches of Ns with expected nts, where possible:                      yes [-r]
# split input file into chunks, run each chunk separately:                        yes [--split]
# parallelize across <n> CPU workers (requires --split or --glsearch):            2 [--cpu]
# do not enforce a maximum length of 50 for sequence names (GenBank max):         yes [--noseqnamemax]
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Validating input                                                                                          ... done. [    0.0 seco nds]
# Splitting sequence file into chunks to run independently in parallel on 2 processors                      ... done. [    0.0 seco nds]
# Executing 1 script to process 1 partition(s) of all 1 sequence(s)                                         ... done. [    2.1 seco nds]
# Merging and finalizing output                                                                             ... done. [    0.1 seco nds]
#
# Summary of classified sequences:
#
#                                           num   num   num
#idx  model      group         subgroup    seqs  pass  fail
#---  ---------  ------------  ----------  ----  ----  ----
1     NC_045512  Sarbecovirus  SARS-CoV-2     1     1     0
#---  ---------  ------------  ----------  ----  ----  ----
-     *all*      -             -              1     1     0
-     *none*     -             -              0     0     0
#---  ---------  ------------  ----------  ----  ----  ----
#
# Summary of reported alerts:
#
#     alert     causes   short                   per    num   num  long
#idx  code      failure  description            type  cases  seqs  description
#---  --------  -------  ------------------  -------  -----  ----  -----------
1     cdsstopn  yes*     CDS_HAS_STOP_CODON  feature      1     1  in-frame stop codon exists 5' of stop position predicted by homo logy to reference
2     cdsstopp  yes*     CDS_HAS_STOP_CODON  feature      1     1  stop codon in protein-based alignment
#---  --------  -------  ------------------  -------  -----  ----  -----------
#
# Output printed to screen saved in:                              alpha-B.1.1.7-test.vadr.log
# List of executed commands saved in:                             alpha-B.1.1.7-test.vadr.cmd
# List and description of all output files saved in:              alpha-B.1.1.7-test.vadr.filelist
# esl-seqstat -a output for input fasta file saved in:            alpha-B.1.1.7-test.vadr.seqstat
# 5 column feature table output for passing sequences saved in:   alpha-B.1.1.7-test.vadr.pass.tbl
# 5 column feature table output for failing sequences saved in:   alpha-B.1.1.7-test.vadr.fail.tbl
# list of passing sequences saved in:                             alpha-B.1.1.7-test.vadr.pass.list
# list of failing sequences saved in:                             alpha-B.1.1.7-test.vadr.fail.list
# list of alerts in the feature tables saved in:                  alpha-B.1.1.7-test.vadr.alt.list
# fasta file with passing sequences saved in:                     alpha-B.1.1.7-test.vadr.pass.fa
# fasta file with failing sequences saved in:                     alpha-B.1.1.7-test.vadr.fail.fa
# per-sequence tabular annotation summary file saved in:          alpha-B.1.1.7-test.vadr.sqa
# per-sequence tabular classification summary file saved in:      alpha-B.1.1.7-test.vadr.sqc
# per-feature tabular summary file saved in:                      alpha-B.1.1.7-test.vadr.ftr
# per-model-segment tabular summary file saved in:                alpha-B.1.1.7-test.vadr.sgm
# per-alert tabular summary file saved in:                        alpha-B.1.1.7-test.vadr.alt
# alert count tabular summary file saved in:                      alpha-B.1.1.7-test.vadr.alc
# per-model tabular summary file saved in:                        alpha-B.1.1.7-test.vadr.mdl
# alignment doctoring tabular summary file saved in:              alpha-B.1.1.7-test.vadr.dcr
# seed alignment summary file (-s) saved in:                      alpha-B.1.1.7-test.vadr.sda
# replaced stretches of Ns summary file (-r) saved in:            alpha-B.1.1.7-test.vadr.rpn
#
# All output files created in directory ./alpha-B.1.1.7-test/
#
# Elapsed time:  00:00:02.21
#                hh:mm:ss
#
[ok]
```

</details>

Tested fine with a BA.1 pulled from GISAID and pre-trimmed by VADR (removal of Ns from terminal ends):
<details>

```
/data/outputs/2021-12-22-vadr-1.4-testing$ v-annotate.pl -f --noseqnamemax --split --cpu 2 --glsearch -s -r --nomisc --mkey sarscov2 --lowsim5seq 6 --lowsim3seq 6 --alt_fail lowscore,insertnn,deletinn ../../testdata/sarscov2/EPI_ISL_6825395-B.1.1.529-omicron.vadr-trimmed.fasta omicron-BA.1-test
# v-annotate.pl :: classify and annotate sequences using a model library
# VADR 1.4 (Dec 2021)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# date:              Wed Dec 22 18:57:27 2021
# $VADRBIOEASELDIR:  /opt/vadr/Bio-Easel
# $VADRBLASTDIR:     /opt/vadr/ncbi-blast/bin
# $VADREASELDIR:     /opt/vadr/infernal/binaries
# $VADRFASTADIR:     /opt/vadr/fasta/bin
# $VADRINFERNALDIR:  /opt/vadr/infernal/binaries
# $VADRMODELDIR:     /opt/vadr/vadr-models
# $VADRSCRIPTSDIR:   /opt/vadr/vadr
#
# sequence file:                                                                  ../../testdata/sarscov2/EPI_ISL_6825395-B.1.1.529-omicron.vadr-trimmed.fasta
# output directory:                                                               omicron-BA.1-test
# force directory overwrite:                                                      yes [-f]
# specify that alert codes in <s> cause FAILure:                                  lowscore,insertnn,deletinn [--alt_fail]
# .cm, .minfo, blastn .fa files in $VADRMODELDIR start with key <s>, not 'vadr':  sarscov2 [--mkey]
# in feature table for failed seqs, never change feature type to misc_feature:    yes [--nomisc]
# lowsim5s/LOW_SIMILARITY_START minimum length is <n>:                            6 [--lowsim5seq]
# lowsim3s/LOW_SIMILARITY_END minimum length is <n>:                              6 [--lowsim3seq]
# align with glsearch from the FASTA package, not to a cm with cmalign:           yes [--glsearch]
# use top-scoring HSP from blastn to seed the alignment:                          yes [-s]
# replace stretches of Ns with expected nts, where possible:                      yes [-r]
# split input file into chunks, run each chunk separately:                        yes [--split]
# parallelize across <n> CPU workers (requires --split or --glsearch):            2 [--cpu]
# do not enforce a maximum length of 50 for sequence names (GenBank max):         yes [--noseqnamemax]
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Validating input                                                                                          ... done. [    0.0 seconds]
# Splitting sequence file into chunks to run independently in parallel on 2 processors                      ... done. [    0.0 seconds]
# Executing 1 script to process 1 partition(s) of all 1 sequence(s)                                         ... done. [    4.1 seconds]
# Merging and finalizing output                                                                             ... done. [    0.1 seconds]
#
# Summary of classified sequences:
#
#                                           num   num   num
#idx  model      group         subgroup    seqs  pass  fail
#---  ---------  ------------  ----------  ----  ----  ----
1     NC_045512  Sarbecovirus  SARS-CoV-2     1     1     0
#---  ---------  ------------  ----------  ----  ----  ----
-     *all*      -             -              1     1     0
-     *none*     -             -              0     0     0
#---  ---------  ------------  ----------  ----  ----  ----
#
# Zero alerts were reported.
#
# Output printed to screen saved in:                              omicron-BA.1-test.vadr.log
# List of executed commands saved in:                             omicron-BA.1-test.vadr.cmd
# List and description of all output files saved in:              omicron-BA.1-test.vadr.filelist
# esl-seqstat -a output for input fasta file saved in:            omicron-BA.1-test.vadr.seqstat
# 5 column feature table output for passing sequences saved in:   omicron-BA.1-test.vadr.pass.tbl
# 5 column feature table output for failing sequences saved in:   omicron-BA.1-test.vadr.fail.tbl
# list of passing sequences saved in:                             omicron-BA.1-test.vadr.pass.list
# list of failing sequences saved in:                             omicron-BA.1-test.vadr.fail.list
# list of alerts in the feature tables saved in:                  omicron-BA.1-test.vadr.alt.list
# fasta file with passing sequences saved in:                     omicron-BA.1-test.vadr.pass.fa
# fasta file with failing sequences saved in:                     omicron-BA.1-test.vadr.fail.fa
# per-sequence tabular annotation summary file saved in:          omicron-BA.1-test.vadr.sqa
# per-sequence tabular classification summary file saved in:      omicron-BA.1-test.vadr.sqc
# per-feature tabular summary file saved in:                      omicron-BA.1-test.vadr.ftr
# per-model-segment tabular summary file saved in:                omicron-BA.1-test.vadr.sgm
# per-alert tabular summary file saved in:                        omicron-BA.1-test.vadr.alt
# alert count tabular summary file saved in:                      omicron-BA.1-test.vadr.alc
# per-model tabular summary file saved in:                        omicron-BA.1-test.vadr.mdl
# alignment doctoring tabular summary file saved in:              omicron-BA.1-test.vadr.dcr
# seed alignment summary file (-s) saved in:                      omicron-BA.1-test.vadr.sda
# replaced stretches of Ns summary file (-r) saved in:            omicron-BA.1-test.vadr.rpn
#
# All output files created in directory ./omicron-BA.1-test/
#
# Elapsed time:  00:00:04.20
#                hh:mm:ss
#
[ok]
```

</details>

**Comment by kapsakcj** [comment]
Kelsey and/or Erin I could use a quick review on this one. I'm confident this container runs as expected, but please test on your end if you have the bandwidth.

I assigned myself as I can set up the image on dockerhub and quay once the dockerfile has been reviewed & approved by at least one of you.

**Comment by erinyoung** [comment]
I'll volunteer to look at this

**Review by erinyoung — COMMENTED** [review]
I always forget the readme

**Comment by erinyoung** [comment]
History:
I built the dockerfile locally and mounted a directory with some premade fastas.

Step 1.
```
fasta-trim-terminal-ambigs.pl --minlen 50 --maxlen 30000 combined.fasta > trimmed.fasta
```
Works as intended



Step 2.
```
v-annotate.pl --split --cpu 8 --glsearch -s -r --nomisc --mkey sarscov2 --lowsim5seq 6 --lowsim3seq 6 --alt_fail lowscore,insertnn,deletinn --mdir /opt/vadr/vadr-models -mkey sarscov2 trimmed.fasta
```

Works as intended.

**Review by erinyoung — APPROVED** [review]

**Pull request merged**
