### PR TITLE
adds vadr 1.5.1 (incl. new RSV models)

### LINKED ISSUE #602: [Request An Update]: VADR v1.5.1
### What container needs an update?

I know all of these containers are awesome, but VADR recently released version 1.5.1, which includes a couple of bug fixes that cropped up in RSV annotation.

(This would also be a good excuse to slim down the image, as `docker images` currently shows its `SIZE` as `6.03 GB`.)

### PR DESCRIPTION
**Pull request by kapsakcj**
~~__setting as a draft until I can get tests to pass. they pass fine locally but not via GHActions workflow....__~~

This PR adds a dockerfile for a new version of VADR v1.5.1. This version adds support for RSV annotation & the required model files are downloaded as part of the install.

⚠️  Caution: annotating RSV genomes may consume upwards of 30GB RAM - I had to comment out the code that tests this since it runs fine locally on my machine w 8CPUs & 32GB RAM, but fails in GH Actions workflows due to 7GB RAM allocation

Changes from previous dockerfile v1.5:

- upgraded base to `ubuntu:focal` - thought this would break things, but it didn't. `ubuntu:xenial` is EOL so I figured this would be a good chance to upgrade. also updated LABEL on line 27
- added line 7 and 85-90 for downloading RSV model files
- added RSV test on lines 150-end using FASTA file recommended by VADR author to use for testing

This PR fixes #602 . I'm not sure how else to get the docker image smaller unless we go with a minimal base image like `alpine`. It might be more work than it's worth

Uncompressed this docker image is 6.13GB where the image for v1.5 is 6.03GB. When compressed on dockerhub the image is ~860MB so I'm not too worried about the overall image size in its current state

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by fanninpm** [comment]
> I'm not sure how else to get the docker image smaller

Are the model files taking up gigabytes of space?

**Comment by kapsakcj** [comment]
Yes, I believe a large proportion is the model files.

4.7GB within `/opt` and you can see the breakdown of that at the bottom

Thankfully many of the files there compress well given that the compressed docker image size is around ~850MB
```
$ docker run -it kapsakcj/vadr:1.5.1

root@a5466dd2013c:/data# cd /

root@a5466dd2013c:/# du -sch *
0       bin
4.0K    boot
4.0K    data
0       dev
1.3M    etc
4.0K    home
0       lib
0       lib32
0       lib64
0       libx32
4.0K    media
4.0K    mnt
4.7G    opt
du: cannot access 'proc/9/task/9/fd/4': No such file or directory
du: cannot access 'proc/9/task/9/fdinfo/4': No such file or directory
du: cannot access 'proc/9/fd/3': No such file or directory
du: cannot access 'proc/9/fdinfo/3': No such file or directory
0       proc
20K     root
20K     run
0       sbin
4.0K    srv
0       sys
4.0K    tmp
331M    usr
4.0K    vadr-models-rsv-1.5-2
8.4M    var
5.0G    total

root@a5466dd2013c:/# du -sch /opt/vadr/*
36M     /opt/vadr/Bio-Easel
38M     /opt/vadr/fasta
82M     /opt/vadr/hmmer
182M    /opt/vadr/infernal
6.9M    /opt/vadr/minimap2
672M    /opt/vadr/ncbi-blast
308K    /opt/vadr/sequip
106M    /opt/vadr/vadr
955M    /opt/vadr/vadr-models
2.6G    /opt/vadr/vadr-models-flavi
4.7G    total

**Review by erinyoung — APPROVED** [review]
Thank you for the RAM warning with RSV. I had no changes to recommend.

I am going to 
- merge this PR
- deploy to dockerhub and quay with the tag 1.5.1
- overwrite the 'latest' tag

**Comment by erinyoung** [comment]
I wonder when we're going to need to separate vadr containers by model.

**Comment by fanninpm** [comment]
> I wonder when we're going to need to separate vadr containers by model.

A couple of months ago, when I emailed Eric Nawrocki about constructing one or more RSV models, I mounted my custom-made RSV model into the model directory VADR uses in order to test the possibility.

**Pull request merged**
