### PR TITLE
adds amrfinderplus 4.0.3 and db 2024-10-22.1. Includes stxtyper

### LINKED ISSUE #1086: [Container Request]: update ncbi-amrfinderplus to 4.0.3 and db version 2024-10-22.1
### What tool are you looking for and why?

New release, hot off the press. Includes stxtyper.

https://github.com/ncbi/amr/releases/tag/amrfinder_v4.0.3

I can update this one, unless someone else beats me to it.

### PR DESCRIPTION
**Pull request by kapsakcj**
~~Draft for now. Want to test as part of a workflow before marking ready for review. Feedback welcome if you have any while I'm testing!~~

Closes #1086 

This describes the changes in amrfinder v4.0.3: https://github.com/ncbi/amr/wiki/New-in-AMRFinderPlus

The biggest change imo is the addition of `stxtyper` which is used as part of amrfinder when using the `amrfinder -O Escherichia` option

The database has also been updated, and you can view the changelog here: https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/4.0/2024-10-22.1/changes.txt

Another important change is the changes in the output column headers, so important if you are parsing results on those headers.

Changes from previous dockerfile:
- restructured the test stage to use NCBI's test script instead of individually running commands within the test script
- Also quieted down some of the `wget` commands 
- added simple `echo` statements in place of showing `wget` output
- uppercase `AS` in `FROM` lines to silence warning

Here's the current `diff` from the previous dockerfile:
```bash
$ diff ncbi-amrfinderplus/3.12.8-2024-07-22.1/Dockerfile ncbi-amrfinderplus/4.0.3-2024-10-22.1/Dockerfile 
1c1
< FROM ubuntu:jammy as app
---
> FROM ubuntu:jammy AS app
3,4c3,4
< ARG AMRFINDER_VER="3.12.8"
< ARG AMRFINDER_DB_VER="2024-07-22.1"
---
> ARG AMRFINDER_VER="4.0.3"
> ARG AMRFINDER_DB_VER="2024-10-22.1"
25c25
< # ncbi-blast+ installed via apt is v2.12.0 - DISABLING so that we can manually install v2.14.0
---
> # ncbi-blast+ installed via apt is v2.12.0 - DISABLING so that we can manually install a more recent version
47,48c47,48
<   rm amrfinder_binaries_v${AMRFINDER_VER}.tar.gz && \
<   mkdir /data
---
>   rm -v amrfinder_binaries_v${AMRFINDER_VER}.tar.gz && \
>   mkdir -v /data
64c64,65
<   wget -q -P /amrfinder/data/${AMRFINDER_DB_VER} ftp://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.12/${AMRFINDER_DB_VER}/* && \
---
>   echo "Downloading amrfinder databases and indexing them now..." && \
>   wget -q -P /amrfinder/data/${AMRFINDER_DB_VER} ftp://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/4.0/${AMRFINDER_DB_VER}/* && \
75c76
< FROM app as test
---
> FROM app AS test
80,86c81,85
< # run recommended tests from amrfinder
< RUN amrfinder --threads 1 --plus -p /amrfinder/test_prot.fa -g  /amrfinder/test_prot.gff -O Escherichia --print_node > test_prot.got && \
<   diff /amrfinder/test_prot.expected test_prot.got && \
<   amrfinder --threads 1 --plus -n /amrfinder/test_dna.fa -O Escherichia --print_node > test_dna.got && \
<   diff /amrfinder/test_dna.expected test_dna.got && \
<   amrfinder --threads 1 --plus -n /amrfinder/test_dna.fa -p /amrfinder/test_prot.fa -g /amrfinder/test_prot.gff -O Escherichia --print_node > test_both.got && \
<   diff /amrfinder/test_both.expected test_both.got
---
> # run recommended tests from amrfinder; check that stx2a_operon is detected in outputs, meaning stxtyper ran correctly
> RUN cd /amrfinder && \
>   bash test_amrfinder.sh . && \
>   echo && echo "Checking for stx2a_operon string in test outputs..." && \
>   grep 'stx2a_operon' test_both.got
89c88,89
< RUN wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/010/941/835/GCA_010941835.1_PDT000052640.3/GCA_010941835.1_PDT000052640.3_genomic.fna.gz  && \
---
> RUN echo "Downloading Salmonella genome (GCA_010941835.1_PDT000052640.3) for testing now..." && \
>   wget -q https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/010/941/835/GCA_010941835.1_PDT000052640.3/GCA_010941835.1_PDT000052640.3_genomic.fna.gz  && \
95c95,96
< RUN wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/812/925/GCA_003812925.1_ASM381292v1/GCA_003812925.1_ASM381292v1_genomic.fna.gz && \
---
> RUN echo "Downloading Klebsiella oxytoca genome (GCA_003812925.1_ASM381292v1) for testing now..." && \
>   wget -q https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/812/925/GCA_003812925.1_ASM381292v1/GCA_003812925.1_ASM381292v1_genomic.fna.gz && \
```

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
If anyone wants to test the docker image themselves, I put one here: https://hub.docker.com/r/kapsakcj/amrfinder/tags

`docker pull kapsakcj/amrfinder:4.0.3`

**Comment by kapsakcj** [comment]
docker image ran successfully as part of a workflow ✅  Should be a drop in replacement for v3.x versions in workflows

**Comment by erinyoung** [comment]
I was going to suggest that we include an E. coli for the new stx feature, but that's already been done.

**Review by erinyoung — APPROVED** [review]
Thank you for putting this together

I adjusted the Dockerfile a little:
1. I changed cat to head for test2
2. I added head for the result file in the third test

Sorry about the failed GA test due to my typo!!!

I adjusted this so that it's easier to see which lines come from test1 and which ones come from test 2 as well as check the contents of the file for the last test.

Once this finishes running, I'll deploy to dockerhub and quay using the tags 'latest' and '4.0.3-2024-10-22.1'

**Comment by erinyoung** [comment]
Thank you for putting this together!!!

You can check the status of the deploy here : https://github.com/StaPH-B/docker-builds/actions/runs/11730094763

**Comment by kapsakcj** [comment]
thank you for the speedy review and improvement to the test stage!

**Pull request merged**
