### PR TITLE
add pangolin v4.3.1 with pangolin-data v1.27

### PR DESCRIPTION
**Pull request by kapsakcj**
differences from previous dockerfile: 

- updated base image to mambaorg/micromamba:1.5.8
- added test for JN.1.48 lineage, which is newly designated in pango-designation v1.27
- There are some slight upgrades in dependencies (minimap2, mafft, maybe others?)

same, but the code `diff`:

```
$ diff pangolin/4.3.1-pdata-1.26/Dockerfile pangolin/4.3.1-pdata-1.27/Dockerfile 
1c1
< FROM mambaorg/micromamba:1.5.7 as app
---
> FROM mambaorg/micromamba:1.5.8 as app
12c12
< ARG PANGOLIN_DATA_VER="v1.26"
---
> ARG PANGOLIN_DATA_VER="v1.27"
18c18
< LABEL base.image="mambaorg/micromamba:1.5.7"
---
> LABEL base.image="mambaorg/micromamba:1.5.8"
178a179,189
> 
> ## test for JN.1.48 (BA.2.86.x sublineage; full unaliased lineage is B.1.1.529.2.86.1.1.48) 
> # this lineages which was designated in pango-designation v1.27: https://github.com/cov-lineages/pango-designation/releases/tag/v1.27
> # see here for commit where it was designated https://github.com/cov-lineages/pango-designation/commit/67f48bf24283999f1940f3aee8159f404124ff3f
> # Here's the genome on NCBI: https://www.ncbi.nlm.nih.gov/nuccore/PP218754
> RUN datasets download virus genome accession PP218754.1 --filename PP218754.1.zip && \
> unzip PP218754.1.zip && rm PP218754.1.zip && \
> mv -v ncbi_dataset/data/genomic.fna PP218754.1.genomic.fna && \
> rm -vr ncbi_dataset/ README.md && \
> pangolin PP218754.1.genomic.fna -o PP218754.1-usher && \
> column -t -s, PP218754.1-usher/lineage_report.csv
\ No newline at end of file
```

README.md differences:

```
$ diff pangolin/4.3.1-pdata-1.26/README.md pangolin/4.3.1-pdata-1.27/README.md 
11,13c11,13
< - [pangolin-data](https://github.com/cov-lineages/pangolin-data) 1.26
< - [pangolin-assignment](https://github.com/cov-lineages/pangolin-assignment) 1.26
< - [minimap2](https://github.com/lh3/minimap2) 2.26-r1175
---
> - [pangolin-data](https://github.com/cov-lineages/pangolin-data) 1.27
> - [pangolin-assignment](https://github.com/cov-lineages/pangolin-assignment) 1.27
> - [minimap2](https://github.com/lh3/minimap2) 2.28-r1209
19c19
< - [mafft](https://mafft.cbrc.jp/alignment/software/) 7.520
---
> - [mafft](https://mafft.cbrc.jp/alignment/software/) 7.526
```

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by kapsakcj** [comment]
I propose we keep the existing docker image nomenclature, and use: `staphb/pangolin:4.3.1-pdata-1.27` as well as overwrite the `:latest` tag

**Comment by erinyoung** [comment]
I'm not going to copy out the results of each test (because most of the stdout is from testing, and it's over 2000 lines long), but it looks like the new test is working great.

```
#26 12.72 "PP218754.1 Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/USA/TX-CDC-QDX91407980/2024   complete genome"  JN.1.48   0.0                            Omicron (BA.2-like)  0.92              0.03           scorpio call: Alt alleles 57; Ref alleles 2; Amb alleles 0; Oth alleles 3  PANGO-v1.27       4.3.1            0.3.19                 v0.1.12        True       pass      Ambiguous_content:0.02  Assigned from designation hash.
```

**Review by erinyoung — APPROVED** [review]
I have no changes to recommend.

**Comment by kapsakcj** [comment]
thank you for the speedy review!

**Comment by erinyoung** [comment]
Thank you for putting this together so quickly!

You can check the status of the deploy here: https://github.com/StaPH-B/docker-builds/actions/runs/8913631223

**Pull request merged**
