### PR TITLE
adding minimap2 2.27

### PR DESCRIPTION
**Pull request by erinyoung**
There's a new version of minimap2! 

The "new" nanopore reads have a much higher accuracy, so there's a new preset for them!

~~This PR is currently in draft because I want to test this new preset. Everything else is basically the same as the prior dockerfile, although I did add the new preset to the README.md.~~

Edit: I have some Salmonella enterica (Livingstone serotype) files on zenodo that will probably work. I was hoping to find something more common/established, though.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Review by Kincekara — APPROVED** [review]

**Review by Kincekara — CHANGES_REQUESTED** [review]
Sorry, I didn't realize it was still a draft. I believe you want to test it with real samples. Let me know when you are finished.

**Comment by erinyoung** [comment]
@Kincekara , I've added in some test files from a zenodo repository. I was hoping for something more standard, but I can't find anything else.

**Comment by Kincekara** [comment]
It looks good to me. I am merging this...

**Review by Kincekara — APPROVED** [review]

**Comment by Kincekara** [comment]
Thank you for this PR!
You can check the image deployment from here: https://github.com/StaPH-B/docker-builds/actions/runs/8452112187.

**Pull request merged**
