### PR TITLE
Amrfinderplus 3.11.2 db version pin and add 3.11.4

### PR DESCRIPTION
**Pull request by kapsakcj**
### EDIT: Made some changes to this message to reflect the current state of the pull request

This PR adds 2 new dockerfiles for NCBI AMRFinderPlus 3.11.2 and 3.11.4 - both with the current database version `2023-02-23.1`

The primary motiviation for this is the database update that was released on 2023-02-23 & so that we are not overwriting older dockerfiles that are still functional and tied to an existing image (in this case only 3.11.2. The new version 3.11.4 dockerfile is brand new)

I propose that instead of overwriting the previous docker image tag (inherently not best practice), we create a new one that includes the database version at the time of build:

Format: `staphb/ncbi-amrfinderplus:<amrfinder-version>-<amrfinder-database-version>`
example: `staphb/ncbi-amrfinderplus:3.11.2-2023-02-23.1`
and `staphb/ncbi-amrfinderplus:3.11.4-2023-02-23.1`

Dockerfile changes:
- upgraded base image to `ubuntu:jammy` since `focal` has older versions of ncbi-blast+ and hmmer. ubuntu:jammy base image is used in previous versions of amrfinder, but was downgraded for 3.11.2 on accident
- added `procps` to `apt-get install` list
- added helpful comments
- added `ARG AMRFINDER_DB_VER="2023-02-23.1"` for pinning database versions going foward
- total rework of how databases are downloaded and indexed, no longer using `amrfinder -u` for reproducibility-sake. This is handled differently for each version since `amrfinder_index` is only available for v3.11.4:
  - 3.11.2 - database files are manually downloaded from NCBI FTP and indexed with `hmmpress` and `makeblastdb`
  - 3.11.4 - data base files are manually downloaded from NCBI FTP and indexed with `amrfinder_index`

amrfinder README.md changes:

-  updated database version and reformatted example output for readability
- Added section on docker image tags and the syntax moving forward

view the rendered readme.md's here: 
- https://github.com/StaPH-B/docker-builds/tree/cjk-amrfinderplus-update/ncbi-amrfinderplus/3.11.2-2023-02-23.1
- https://github.com/StaPH-B/docker-builds/tree/cjk-amrfinderplus-update/ncbi-amrfinderplus/3.11.4-2023-02-23.1

main README.md changes:

- updated main README.md with database version for last 2 docker images
- fixed formatting for last ncbi-datasets bullet point

view the rendered readme.md here: https://github.com/StaPH-B/docker-builds/blob/cjk-amrfinderplus-update/README.md

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
I like having the Dockerfile available for each tag, though, so I think if you want to use a different tag you should create a new dockerfile.

**Comment by kapsakcj** [comment]
Setting this PR as a draft so I can make the changes requested.

Planning on creating a new dockerfile for amrfinder v3.11.2 and database version 2023-02-23.1 

Also planning to add a new dockerfile for v3.11.4 & the same db. 

For 3.11.4, I'm thinking I will do the following instead of using `amrfinder -u` for downloading/installing the database
- download the db files manually, pinning the database version
- use the new `amrfinder_index` cmd for indexing the database

This will allow us to pin the database version going forward and create new dockerfiles when either new db's are released or when new code versions are released. Similar to how Pangolin & pangolin-data release cycles go

**Comment by kapsakcj** [comment]
OK I believe this PR is ready for review. Some notes/things to be aware of:

- Regarding the old 3.11.2 dockerfile `ncbi-amrfinderplus/3.11.2/Dockerfile`. I did not mean to adjust this dockerfile & README.md (I was trying to undo my original changes) and I do NOT want to re-deploy this docker image. Let's leave as is
- New 3.11.2 dockerfile `ncbi-amrfinderplus/3.11.2-2023-02-23.1/README.md`. 
  - I DO want to deploy a new docker image here and name it `staphb/ncbi-amrfinderplus:3.11.2-2023-02-23.1`. Let's skip overwriting the `:latest` tag for this one
- New 3.11.4 dockerfile `ncbi-amrfinderplus/3.11.4-2023-02-23.1/Dockerfile`
  - I DO want to deploy a new docker image and name it `staphb/ncbi-amrfinderplus:3.11.4-2023-02-23.1` as well as overwriting the `:latest` tag

Lastly - there's a lot going on here - please let me know if you have any questions or if I can clarify anything. I tried to update my initial PR message to reflect how the code stands currently, but I may have missed something.

**Review by erinyoung — APPROVED** [review]
I think this looks great.

I think it's going to be easy to control both the version of amrfinderplus and the database that it uses.

The changes in 3.11.2 don't seem to be major, so I'm just ignoring them. They aren't going to get pushed to dockerhub or quay anyway.

I'm going to approve and merge this, but I am going to let you deploy to dockerhub and quay. From what I understand, you're going to be using the 3.11.2-2023-02-23.1 and 3.11.4-2023-02-23.1 tags with 3.11.4-2023-02-23.1 overwriting the 'latest' tag.

**Comment by erinyoung** [comment]
I'm also going to let you delete your branch, if you're done with it.

**Pull request merged**
