### PR TITLE
Masurca version 4.1.0

### PR DESCRIPTION
**Pull request by erinyoung**
I didn't change anything in the Dockerfile other than the version and I added `-q` to the wget commands in test.

Pull Request (PR) checklist:
- [X] Include a description of what is in this pull request in this message.
- [X] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [X] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [X] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [X] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [X] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [X] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [X] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [X] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Should close https://github.com/StaPH-B/docker-builds/issues/567

**Comment by erinyoung** [comment]
Sorry about the addition after the PR. I tried to run masurca, in case anyone actually wanted to run masurca, and ran into an error because numactl wasn't installed. 

It _should_ work okay now.

POLCA (which is what I normally use this container for) worked fine prior.

**Review by kapsakcj — APPROVED** [review]
I made some minor formatting changes to the masurca readme.md and added `procps` to apt-get install just to be sure `ps` is available.

I'll merge and deploy this docker image to `staphb/masurca:4.1.0` and overwrite `:latest` tag on dockerhub and quay

**Comment by kapsakcj** [comment]
deploy workflow is here: https://github.com/StaPH-B/docker-builds/actions/runs/4457217713

I'll let you delete your dev branch if you're done with it

**Pull request merged**
