### PR TITLE
adds pbmm2

### PR DESCRIPTION
**Pull request by Kincekara**
pbmm2 is a SMRT C++ wrapper for minimap2's C API. It can work directly with PacBio's BAM format.

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by erinyoung** [comment]
Did the tests actually pass? I know the checks passed, but this was the message:

```
#10 [test 2/2] RUN pbmm2 index ref.fasta ref.mmi --preset HiFi &&    pbmm2 align -j 8 ref.mmi m64012_210821_095651.hifi_reads.bam mapped.hifi.reads.bam --preset HiFi
#10 0.067 >|> 20240328 20:39:07.992 -|- WARN -|- AlignSettings -|- 0x7f7e8cc3f000|| -|- Requested more threads for alignment (8) than system-wide available (4)
#10 DONE 238.9s
```

**Comment by Kincekara** [comment]
@erinyoung It was only a warning but I lowered the threads for alignment in any case. Now everything seems okay.

**Review by erinyoung — APPROVED** [review]
Thanks for making that change!

I'm going to 
1. approve this PR
2. merge this PR
3. deploy to dockerhub and quay using the tags '1.13.1' and 'latest'

**Comment by erinyoung** [comment]
You can check the status of the deploy here : https://github.com/StaPH-B/docker-builds/actions/workflows/manual-deploy.yml

**Pull request merged**
