### PR TITLE
add amrfinderplus 3.11.26 and db 2023-11-15.1

### PR DESCRIPTION
**Pull request by kapsakcj**
This PR adds a dockerfile and readme for amrfinderplus v3.11.26 and db 2023-11-15.1. also updated main readme.

Not much in the way of `amrfinder` code changes (small bugfix) but the updated database brings general updates & improvements in addition to 2 new `--organism` options for `Vibrio_parahaemolyticus` and `Vibrio_vulnificus`. Full changelog for db here: https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.11/2023-11-15.1/changelog.txt

Changes from previous dockerfile:

- updated ARG lines for amrfinder and db
- reverted test commands on [lines 79-80](https://github.com/StaPH-B/docker-builds/blob/master/ncbi-amrfinderplus/3.11.20-2023-09-26.1/Dockerfile#L79-L83) back to their previous form which uses the expected results files from the software release instead of downloaded from a specific commit made after v3.11.20 release

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [x] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [x] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [x] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [x] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [x] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [x] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [x] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

### CODE REVIEW

**Comment by Kincekara** [comment]
@kapsakcj NCBI's docker images are half the size of our images. I believe we don't need an extra layer for Blast. We can use apt if there is no specific reason.
You can check NCBI's recipe from https://github.com/ncbi/docker/blob/master/amr/Dockerfile

**Comment by kapsakcj** [comment]
There is a specific reason, blast from `apt` in ubuntu Jammy as well as other releases is v2.12.0: https://packages.ubuntu.com/search?keywords=ncbi-blast%2B&searchon=names&suite=all&section=all

...which does support multi-threading but has a bug for macOS: https://github.com/ncbi/amr/releases/tag/amrfinder_v3.11.8 so I opted to upgrade to a more recent version

**Comment by kapsakcj** [comment]
Our dockerfile is pretty similar to theirs, but we pin more exact versions (`ubuntu:jammy` vs `ubuntu` for base image): https://github.com/ncbi/docker/blob/master/amr/Dockerfile

We also pin the specific `amrfinder` database version

**Comment by Kincekara** [comment]
Thank you for the clarification! That's a very good reason. I am merging this PR 🚀

**Comment by kapsakcj** [comment]
Thank you for the review and appreciate the feedback 👍 314MB compressed docker image size is a little bulky, though not the biggest image I've ever seen. Perhaps we can try to shave off more unnecessary things in the next iteration.

**Comment by Kincekara** [comment]
It's updated frequently. We will have a chance to review it again. 
Thank you for your PR!

**Comment by erinyoung** [comment]
I saw this PR open yesterday, and went to review it this morning... but it was missing!!!

@Kincekara is way too fast! 

Thank you for reviewing this.

And thank you @kapsakcj for putting together a Dockerfile!

**Pull request merged**
